src/librpminspect/inspect.h, src/librpminspect/inspect_kernel.c, src/librpminspect/listfuncs.c
This implements the utility functions for checking for module PCI alias regressions, along with a couple of bug fixes to listfuncs.c.
This is not part of an inspection driver yet. I guess it could be, since it doesn't depend on creating file-level peers like the other module checks do, but I figured it would make more sense for all of the module checks to go in the same inspection.
=> Compare pciids

.travis.yml, src/librpminspect/badwords.c, src/librpminspect/files.c, src/librpminspect/init.c, src/librpminspect/inspect_desktop.c, src/librpminspect/inspect_elf.c, src/librpminspect/inspect_kernel.c, src/librpminspect/inspect_license.c, src/librpminspect/inspect_metadata.c, src/librpminspect/local.c, src/librpminspect/readelf.c, src/librpminspect/rmtree.c, src/librpminspect/rpminspect.h, src/rpminspect/builds.c, tests/librpminspect/Makefile.am, tests/librpminspect/elftest.c, tests/librpminspect/test-badwords.c, tests/librpminspect/test-inspect_elf.c
Change the badwords implementation to not use regexes, since there's no real reason to use them and it just adds another layer of complexity.
Also clean up a couple of things with the tests.
=> Badwords and misc tests

src/librpminspect/files.c
Noticed we had some extra parentheses after the bugfix in issue #19 so this strips those back out.
=> Strip extra () after bugfix for issue #19

README
I'm lazy and I like things I can copy and paste. :)
This provides `dnf install` copy/paste blocks for both build and runtime dependencies. It also documents the use of CUnit. 
Tested on a Fedora rawhide container image.
=> Update README to include dnf install instructions

src/rpminspect/rpminspect.c
When the user passes an obviously bogus release like:
rpminspect 42
`rindex(after, '.')` returns `NULL`, which then gets incremented to 0x1 and
assigned to `pos`. `strdup(pos)` then segfaults prior to the `NULL` check on
`after_product`.
I might think about the error message some more but that should be a later PR. I need to understand more what "build" means in the context of rpminspect (e.g., what artifacts it can be given -- it looks like package names and local RPMs) and if there's a better way of informing the user about their mistake that makes it clear what is wrong with their argument and what they could pass instead.
=> Fix SEGV in get_product_release

tests/Makefile.am
CI uses `make distcheck` to run the unit tests. In the previous commit,
distcheck fails because there is no rule to make `rpminspect-help.sh`;
this is because it isn't added to the dist archive.
Adding `TESTS` to `EXTRA_DIST` fixes this.
@dcantrell I'm not sure if this is the best approach to fix it, but it works on my system. Thoughts? 
=> Fix distcheck

tests/Makefile.am, tests/rpminspect-segv.sh
Ensure that builds without product releases don't cause a segfault. As
the text of the error might change in the future (or, 42 might become a
valid build id), only check that we get a non-SEGV return code and don't
check program output.
Regression test for #33. 
=> Add regression test for segfault

src/rpminspect/rpminspect.c
When a configuration file is passed on the command line, it should
always be used. In particular, that should mean erring out and telling
the user that their parameter was bad. When no config parameter was
passed, we should use the default if it exists. However, since
rpminspect is a new package (and choice of default `rpminspect-data-*`
depends on the distro), we should inform the user what they're missing.
The issue with the old behavior is, if an explicit configuration file was passed *and* the user lacked `rpminspect-data-fedora`, they'd default to using a file which doesn't exist. :-) 
=> Fix config file detection

README
Ninja is called ninja-build in Fedora, so the 'dnf install' command
had to be updated.
=> docs: update README with correct ninja-build package name

lib/init.c, lib/inspect_elf.c, lib/results.h, lib/rpminspect.h, lib/types.h
Use the new tests:ipv6_blacklist from the config file to enable checking
of IPv4-only function usage. When these functions are used, it likely
means the program isn't compatible with IPv6 addresses, which are
becoming increasingly more widely used.
Depends on https://github.com/rpminspect/rpminspect-data-fedora/pull/1. 
=> Add IPv6 blacklist check

lib/peers.c, lib/rpminspect.h, src/builds.c
When the path to the before or after RPM contained '..' in it,
rpminspect would previously segfault:
$ rpminspect ../koji/resteasy-3.0.19-9.fc30.noarch.rpm resteasy-3.0.26-1.fc32.noarch.rpm
*** Error extracting /var/tmp/rpminspect/local.6nixV7/before/../koji/resteasy-3.0.19-9.fc30.noarch.rpm: Path contains '..'
Segmentation fault (core dumped)
This is undesirable. To prevent the segfault, fix error handling in
add_peer and get_rpm_info in order to detect when extract_rpm fails.
This has the side effect of showing a bogus second error message though:
$ rpminspect ../koji/resteasy-3.0.19-9.fc30.noarch.rpm resteasy-3.0.26-1.fc32.noarch.rpm
*** Error extracting /var/tmp/rpminspect/local.hcZD52/before/../koji/resteasy-3.0.19-9.fc30.noarch.rpm: Path contains '..'
*** Error gathering build …
=> Fix segfault when path to RPM contains ..

lib/files.c, lib/inspect_ownership.c
I think this fixes #99 by updating the imports in file.c and inspect_ownership.c
The change builds locally and in mock. Some quick tests locally work with this patch.
=> updating imports to use libcap, matching BuildRequires in specfile

meson.build
Output example:
```
Found ninja-1.9.0 at /usr/bin/ninja
ninja: no work to do.
1/18 test-badwords                           OK       0.02 s 
2/18 test-koji                               OK       0.02 s 
3/18 test-tty                                OK       0.02 s 
4/18 test-strfuncs                           OK       0.01 s 
5/18 test-init                               OK       0.03 s 
6/18 test-inspect_elf                        OK       0.03 s 
7/18 rpminspect-test-suite.test_default      OK       0.32 s 
8/18 rpminspect-test-suite.test_desktop      OK      11.45 s 
9/18 rpminspect-test-suite.test_disttag      OK       2.27 s 
10/18 rpminspect-test-suite.test_emptyrpm     OK       2.87 s 
11/18 rpminspect-test-suite.test_kmod         OK      13.95 s 
12/18 …
```
=> Add possibility to run integration test suites separately

README
I noticed that the README was using both dnf and yum. As everything we perform works in yum-only environments, we should standardize on yum in the documentation unless dnf is required.
=> Unify the README with yum

.github/workflows/ci-python-style.yml, tox.ini
This runs flake8[0] for PEP8 conformance and Black[1] for style
checking. Black can automatically format code, and while its choices
aren't always my favorite, it's great for a uniform, easily enforceable
style. It has editor integration, can be run manually from the command
line, or as a pre-commit hook so it mostly stays out of your way.
[0] https://flake8.pycqa.org/
[1] https://black.readthedocs.io/
=> ci: Add Python linting jobs

.github/workflows/ci-shell-style.yml
ShellCheck[0] is a great linting tool for shell scripts and catches a
number of common problems.
[0] https://www.shellcheck.net/
=> ci: Add ShellCheck to lint shell scripts

test/baseclass.py
While skimming through the test interface to figure out what's required to implement a test, there were a few oddities that made me jump around the code a bit more than is strictly necessary. These changes are strictly equivalent, but somewhat more (in my opinion) idiomatic and clear.
=> Tidy up the test base classes

.github/.codecov.yml, .github/workflows/ci.yml
codecov provides a nice online code coverage tracker (with a badge!) so
that code coverage can be tracked over time and examined from the
browser. All that's necessary to enable this add the upload token[0] to
the repository secrets (Settings -> Secrets) with the name CODECOV_TOKEN
[0] https://codecov.io/gh/rpminspect/rpminspect/
An example report: https://codecov.io/gh/jeremycline/rpminspect/tree/c4866f0848cbf5516b17c6e9415e56ec9cbb503e
=> Upload coverage report to codecov

test/baseclass.py, test/test_disttag.py
While developing a new test, I provided the wrong waiver_auth and got a
test that failed with:
Traceback (most recent call last):
File "/home/jcline/devel/rpminspect/test/baseclass.py", line 419, in
runTest
self.assertTrue(
AssertionError: False is not true
It is indeed true that False is not true, but I had to do a bit of
digging to determine what was wrong with my test.
This changes check_results to raise an AssertionError with details about
what exactly was wrong with the results. For example, the issue that generated
the above error now generates:
Traceback (most recent call last):
File "/home/jcline/devel/rpminspect/test/baseclass.py", line 414, in runTest
check_results(self.results, self.label, self.result, self.waiver_auth)
File "/home/jcline/devel/rpminspect/test/baseclass.py", …
=> Improve the error reporting for test result checking

lib/init.c
In init_rpminspect, the data member rpminspect::cfgfiles of type
string_list_t is allocated less bytes than it should.  And then later
when the statement "TAILQ_INIT(ri->cfgfiles)" corrupts memory by
writing passed the (wrongly) allocated memory region.
Something similar happens to the entry that get appended to that
instance of string_list_t.  The entry gets allocated less bytes than
it should and then the statement "TAILQ_INSERT_TAIL(ri->cfgfiles, cfg,
items)" corrupts memory y writing passed the wrongly allocated memory
region.
These two memory corruptions further lead to inconsistent behaviour
down the road.
This patch fixes that by allocating the right amount of memory for
these two cases.
Signed-off-by: Dodji Seketeli <dodji@seketeli.org>
=> Fix memory corruption in init_rpminspect

include/readelf.h, lib/inspect_abidiff.c, lib/readelf.c
Sometimes, when comparing two packages the abidiff inspection can
wrongly attempt to compare ELF binaries that are not shared
libraries.  For instance, it can try to compare debuginfo files --
which are technically ELF files, but that we should obviously not
compare.  As a result, it sometimes emits spurious errors like this:
$ rpminspect -k -v  -T abidiff ./workdir/tmp/alsa-lib-1.2.2-2.fc33 ./workdir/tmp/alsa-lib-1.2.3.2-5.fc33
Running abidiff inspection...        FAIL
[...]
abidiff:
--------
1) Comparing from /usr/lib/debug/.dwz/alsa-lib-1.2.2-2.fc33.i386 to
/usr/lib/debug/.dwz/alsa-lib-1.2.3.2-5.fc33.i386 in package alsa-lib-debuginfo on
i686 revealed ABI differences.
Result: VERIFY
[...]
Details:
abidiff: failed to read input file …
=> Avoid comparing elf files that are not shared libraries

lib/builds.c, src/rpminspect.c
rpminspect can work on single RPMs or entire Koji builds.  For the
former, rpminspect expected the RPMs to be locally available.  But
there are times where you may want to compare against an RPM already
built and available for download somewhere.  This patch lets you
specify URLs to single RPM packages.  rpminspect will detect this and
download the package and perform the inspections as if you were
providing a local RPM.
=> Support single package URLs for before and after builds (#190)

src/rpminspect.c
This cleans up error reporting and just makes it fewer lines.
=> Use warnx(), errx(), and err() in src/rpminspect.c

TODO, data/generic.yaml, include/inspect.h, include/results.h, lib/inspect.c, lib/inspect_virus.c, lib/meson.build, meson.build, osdeps/centos7/reqs.txt, osdeps/centos8/reqs.txt, osdeps/fedora-rawhide/reqs.txt, osdeps/fedora/reqs.txt, osdeps/opensuse-leap/reqs.txt, osdeps/opensuse-tumbleweed/reqs.txt, po/POTFILES, po/rpminspect.pot, rpminspect.spec.in, test/meson.build, test/test_virus.py
The virus inspection checks every file in the after build (or the only
build if you are running rpminspect that way) using libclamav and
reports if a virus was found.  This inspection is expensive, but
that's how clamav works.  The inspection can be disabled via profiles,
the command line, or local configuration as needed.
If a virus is found, rpminspect reports the file that has the
suspected virus as well as the virus name returned by libclamav.  The
result severity level is BAD.
=> Implement the 'virus' inspection and add test cases for it.

osdeps/ubuntu/post.sh
Stop the service and run freshclam manually.
=> Stop the freshclam service for the Ubuntu gate job

lib/inspect_virus.c
libclamav version 0.100 or thereabouts do not have a struct
cl_scan_options definition.  Instead the options are just a bitfield
that's an unsigned int.  In these older versions of libclamav there is
a macro called CL_SCAN_STDOPT.  So in the presence of that macro,
assume we don't have struct cl_scan_options and operate with the
previous API.  Otherwise use the newer API.  This gets the program
working on OpenSUSE Leap 15.2 which has clamav 0.100.
=> Support slightly older versions of libclamav in inspect_virus.c

include/constants.h, include/rpminspect.h, lib/checksums.c, lib/inspect_politics.c
Expand to cover SHA-244, SHA-384, and SHA-512.  Also make the library default a constant in constants.h.
=> Expand message digest support in librpminspect

data/generic.yaml, include/inspect.h, include/results.h, lib/inspect.c, lib/inspect_dsodeps.c, lib/meson.build
Most of the inspections carry short lowercase names.  DT_NEEDED stood
out a bit and it looked weird to me, so I renamed it to dsodeps.
=> Rename the 'DT_NEEDED' inspection to 'dsodeps'

data/generic.yaml, include/results.h, lib/inspect.c, test/test_lto.py
This was the last inspection named with all uppercase letters.  Rename
it using lowercase letters to fit in with the other inspection names.
=> Rename 'LTO' inspection to 'lto'

lib/inspect_permissions.c
Just return the result.  Without this, if permissions reports all INFO
results we will likely get a FAIL result for the inspection.
=> No need to check value of allowed in permissions_driver()

include/types.h, lib/files.c, lib/inspect_config.c
A number of problems here.  Make sure we pick up the file flags
correctly when unpacking the payload.  Next, fix the 'config'
inspection so it performs the comparision only when the before and
after file carry RPMFILE_CONFIG flags, not when their flag check
values are equal.  Without this, it was scanning every file in the
package.  Add in some more protections to skip over non-regular files
and non-symlinks.
=> Fix RPMFILE_FLAGS handling for %config files (#221)

include/types.h
rpmfiles.h does not exist in older releases of rpm, such as the
version in CentOS 7.  The types we needed are defined by including
rpmfi.h regardless of release, so make sure we do that.
=> Include rpm/rpmfi.h insted of rpm/rpmfiles.h

lib/inspect_doc.c
rpm marks man pages with RPMFILE_DOC, but we check man pages in the
'manpage' inspection so there's really no need to also check them in
the 'doc' inspection.  Exclude man pages here based on path matching
since there isn't anything like RPMFILE_MAN or something that we could
key off of.
=> Exclude man pages from the 'doc' inspection

lib/arches.c, lib/builds.c, lib/koji.c
rpminspect has had the -a option to restrict the architectures
examined during a run.  However, that was limited to the peer
detection code and not the download code.  rpminspect would still
always download every architecture and then later make the decision as
to whether or not to use it.  This patch extends the -a handling to
the download side so it covers downloading (or copying in the case of
locally cached builds) and peer detection.
=> Honor the -a command line option for downloads as well as runtime (#233)

TODO, data/generic.yaml, include/types.h, lib/free.c, lib/init.c, lib/inspect_abidiff.c, lib/inspect_annocheck.c, lib/inspect_changedfiles.c, lib/inspect_changelog.c, lib/inspect_config.c, lib/inspect_desktop.c, lib/inspect_doc.c, lib/inspect_kmidiff.c, lib/inspect_patches.c, lib/inspect_upstream.c
This is a new feature allowing runtime overrides of the userspace
tools that rpminspect invokes.  There are default command names in the
code if you do not define the settings, but if you need to refer to
one of these tools in a different installed location, you can.
=> Allow optional 'commands' block in the config file

lib/abi.c
The read loop that creates the abi_list_t struct was not creating new
abi_pkg_entry_t structs for each package.  It was just using the same
one over and over.  That's because the end of the loop needs to reset
the pointer to NULL and continue.  This fixes up the final memory leak
shown in free_abi()
=> Avoid reusing the same abi_pkg_entry_t struct in read_abi()

data/generic.yaml, include/types.h, lib/free.c, lib/init.c, lib/inspect_pathmigration.c
Expand the 'pathmigration' inspection to support path exclusions.  For
example, the kernel package may deliver modules in /lib/modules.  We
may not want rpminspect to warn about modules needing to be in
/usr/lib even if we have set up the rules to warn about libraries in
/lib.  The path exclusions are flexible enough to handle those cases.
The pathmigration section of the configuration file can now have a
block called 'excluded_paths' which lists the excluded path prefixes.
All paths listed must end with a '/'.  rpminspect will add one if it
does not see one at the end of the prefix.  This is to avoid something
like "/lib/modules" matching
"/lib/modulessddfgwerqwefwercver/oopsfile" and ignoring it.
=> Allow a set of excluded path prefixes in 'pathmigration'

src/rpminspect.c
Fix two problems with the -w option on rpminspect(1)
1) The test within the '-w' option handler to pick up relative
directory paths was incorrect.  Relative directory paths start with
../ or ./.  The test was missing an extra set of parentheses.
2) The use of realpath(3) in the '-w' option handler should only be
used if the directory specified exists.  Otherwise take the path as
specified by the user and let the mkdirp() call handle it
gather_builds().
=> [fix] Correctly handle the -w option on rpminspect(1) (#256)

osdeps/opensuse-leap/post.sh, osdeps/opensuse-leap/reqs.txt
opensuse-leap lacks an installable package for the 'rc' shell.  What I
was doing was fetching it from Fedora's RPM repos, then using rpm2cpio
to unpack the package manually and just copy the 'rc' executable in
place.  This is failing now because of generally yum unpleasantries.
Since rc is small, just download the source from Debian and build it
within the instance.  I'm already doing that for mandoc, so I can do
that for rc.
=> [ci] Build and install 'rc' from source on opensuse-leap

doc/git.md
Contributors should avoid merge commits in pull requests, so explain
one manner to track the upstream repo and rebase your copy to it
periodically.
=> [doc] Update doc/git.md on how to track upstream

osdeps/opensuse-leap/post.sh, osdeps/opensuse-tumbleweed/post.sh
Suppress the curl progress output and use -L so any redirects are
followed.
=> [ci] Adjust curl(1) command line used for 'rc' in opensuse CI jobs

osdeps/centos8/defs.mk
CentOS 8 has renamed the 'PowerTools' repo to 'powertools'.  Still the
same thing.  Keeping the previous name would have also been useful.
Or patching dnf to be case-insensitive on repo names.
=> [ci] s/PowerTools/powertools/g in the centos8 PKG_CMD definition

osdeps/opensuse-leap/post.sh, osdeps/opensuse-tumbleweed/post.sh
The output of html2text is different on opensuse-leap and
opensuse-tumbleweed than it is Fedora, so the same ridiculous
pipelines cannot be used between the two systems.
=> [ci] The output of html2text on opensuse systems is different

data/generic.yaml, include/inspect.h, include/readelf.h, include/results.h, include/rpminspect.h, include/types.h, lib/debug.c, lib/free.c, lib/init.c, lib/inspect.c, lib/inspect_badfuncs.c, lib/inspect_elf.c, lib/meson.build, lib/readelf.c, po/POTFILES, po/rpminspect.pot, test/lib/test-inspect_elf.c, test/meson.build, test/test_badfuncs.py, test/test_elf.py
This breaks out the forbidden ipv6 function check in to a dedicated inspection that checks for any function listed in the badfuncs section of the config file.  For now it will just check for the forbidden ipv6 functions, but this could be expanded in the future (like maybe checking for gets() usage).
=> Create the 'badfuncs' inspection

lib/inspect_filesize.c, test/test_filesize.py
No need to check size changes on debug package files.  When displaying
the percentage change, show the absolute value and exclude the + or -
sign.
=> [fix] Skip debug packages in 'filesize', display changes correctly

lib/readelf.c
Commit 336d66d511fcbbd89092eeaab8e2ad904f4d29e2 introduced a
regression where the `get_elf_section` function would fail to traverse
ELF sections of `ET_REL` objects and thus fails the execstack check,
which looks for the GNU-stack note.
This fix continues to avoid the memcpy as the commit intended and
always traverses section headers to look for the requested section.
=> Fix spurious execstack failure

lib/listfuncs.c
Handle the delimiter first, but skip for the first element of a list.
A 1-element list will properly end up being a strdup() of the single
element's data member with no delimiter.
=> [fix] Simplify list_to_string() so it handles 1-elements lists right

include/rpminspect.h, lib/abspath.c, lib/meson.build, test/lib/test-abspath.c, test/lib/test-main.h, test/lib/test-strfuncs.c, test/meson.build
The abspath() function is similar to realpath(), but does not rely on
the filesystem.  All it does is read the actual path string and do
things like back up when it encounters a ".." and skip things like
".".  It is important to note that this function DOES NOT check to see
if the canonicalized path actually exists on the filesystem or not.
The purpose of this function is to reduce a complicated path with
.. redirects down to what it actually means.
This commit also adds some unit tests for the abspath() function.
The caller is responsible for freeing the returned string.
=> [lib] Add abspath() to canonicalize path strings

lib/inspect_doc.c
Do not assume all %doc files in a package are text files.  Only show
the diff(1) output if the files are text files (and both of them).
For all other file types, just report if the content changed and leave
it at that.
=> In the doc inspection, only show diff(1) output for text files (#254)

include/rpminspect.h, lib/output_xunit.c, lib/strfuncs.c, test/lib/test-strfuncs.c
Add strxmlescape() to strfuncs.c along with test cases.  This finds and escapes the 5 XML special characters.  The replacements are substrings, so the caller is responsible for freeing the newly allocated string returned.  Change the xunit output to use CDATA within the system-out blocks.
=> Add strxmlescape() and fix the xunit output for rpminspect results

.github/workflows/extra-ci.yml, osdeps/debian/post.sh, osdeps/debian/reqs.txt, osdeps/ubuntu/reqs.txt
Need to make sure rustc is installed on Debian.  Both platforms need
patchelf.  Ubuntu needs an explicit install of libmagic-dev.  And drop
the sudo usage in the Ubuntu environment setup.
=> [ci] Fixes for GitHub Actions on Debian and Ubuntu

.github/workflows/extra-ci.yml, osdeps/arch/defs.mk, osdeps/centos7/defs.mk, osdeps/centos8/defs.mk, osdeps/debian/defs.mk, osdeps/debian/post.sh, osdeps/debian/reqs.txt, osdeps/fedora-rawhide/defs.mk, osdeps/fedora/defs.mk, osdeps/opensuse-leap/defs.mk, osdeps/opensuse-leap/reqs.txt, osdeps/opensuse-tumbleweed/defs.mk, osdeps/opensuse-tumbleweed/reqs.txt, osdeps/ubuntu/defs.mk, utils/determine-os.sh
Pass CRYPTOGRAPHY_DONT_BUILD_RUST=1 in the environment for PIP_CMD so
that Python modules installed with pip skip Rust parts.  Remove rustc
from the reqs.txt files that had that listed.
In the Ubuntu job, we have to use sudo because it's the only one not
running in a container.
In osdeps/debian/post.sh replace the pgrep/pkill with 'systemctl stop
clamav-freshclam.service'.
Add patchelf to the reqs.txt files for opensuse-leap and
opensuse-tumbleweed.
=> [ci] Disable Rust support in pip modules, more extra-ci fixes

osdeps/centos7/defs.mk, osdeps/centos7/pre.sh, osdeps/centos8/defs.mk, osdeps/centos8/pre.sh, osdeps/debian/defs.mk, osdeps/debian/pre.sh
In the pre.sh scripts for those platforms, make sure pip and
setuptools are updated with pip before proceeding.  We want to make
sure we have the latest pip so that it will install wheels when
available.  If we use source dists with pip, it builds locally and
that will require rustc and many other things.
=> [ci] Make sure pip is updated on debian, centos7, and centos8

.github/workflows/extra-ci.yml, osdeps/arch/defs.mk, osdeps/arch/pre.sh, osdeps/arch/reqs.txt, osdeps/centos8/pre.sh, osdeps/debian/pre.sh
Arch Linux needs the initialization process to create the
/var/lib/pacman directory.  centos7 and centos8 had the freshclam call
in pre.sh, which was wrong.  It runs from post.sh.  And debian needed
the '-y' switch to apt-get in pre.sh when installing pip.
=> [ci] Fixes for extra-ci on arch, centos7, centos8, and debian

.github/workflows/extra-ci.yml, README.md, osdeps/gentoo/defs.mk, osdeps/gentoo/pip.txt, osdeps/gentoo/post.sh, osdeps/gentoo/pre.sh, osdeps/gentoo/reqs.txt
Drop the latest for tumbleweed.  Not sure if that will make a
difference, but that image looks broken right now.
For arch, try the base-devel image.
=> [ci] Adjust docker image names for opensuse and arch

include/results.h, lib/inspect_runpath.c
ELF objects should not have both DT_RPATH and DT_RUNPATH.  If they
happens, it indicates a linker error and should be handled
accordingly.  If rpminspect finds both symbols in the ELF object, the
runpath inspection fails with an unwaivable BAD result.
=> [new] In the runpath inspection, fail if DT_RPATH and DT_RUNPATH exist

include/meson.build, include/uthash.h, lib/files.c
Add the uthash has table header to the code base and begin migrating
away from the search.h functions provided by glibc.  The search.h
functions are not universally available in all C libraries and uthash
is a little easier to work with in the code.
This patch moves the file peering code over to uthash.
=> [lib] Add uthash and move the file matching code to it.

lib/inspect_badfuncs.c, lib/inspect_runpath.c, lib/readelf.c
badfuncs and runpath both had some memory leaks.  Fix those up with
this patch.
=> [fix] Fix some memory leaks found by valgrind

utils/mkannounce.sh
I summarize changes in release announcements and group them by rough
category to break things up a bit.  Now that I have git category
markers, I can script the generation of the draft announcement and
then go from there.
=> [bld] Create mkannounce.sh to help make release announcements easier

lib/readelf.c
elf_end() and close() were possibly called twice for successful runs
of init_elf_data().  Calling elf_end() more than once on an opened
libelf entity is undefined.  It could crash or it could run forever.
Point is, don't do it.
=> [fix] Remove duplicate elf_end() call in init_elf_data() (#303)

src/rpminspect.c
The program reports the command line used to invoke itself.  Also
include the version of rpminspect.
=> [new] Report the program version number in the results (#309)

lib/inspect_manpage.c, lib/uncompress.c, test/test_manpage.py
A couple of fixes in this patch.  First, make sure uncompress_file()
handles compressed but empty files.  Because libarchive returns
ARCHIVE_EOF on archive_read_next_header() when the payload is empty,
my function was erroring out and returning NULL.  That caused an
assert() failure higher up in the manpage inspection.  So, teach
uncompress_file() how to handle compressed zero-length files.  Since
uncompress_file() creates a temporary file to write the uncompressed
payload to, use fdopen() and fclose() to create a zero-length file in
the case of a compressed empty file.  ARCHIVE_FAILED and ARCHIVE_FATAL
are still handled, but I also treat ARCHIVE_RETRY the same way and
just fail out.  I have not seen ARCHIVE_RETRY triggered in the wild
and in our cases it really only means you can restart …
=> [fix] Handle compressed but otherwise empty man pages (#308)

lib/inspect_virus.c
Set some options before the virus inspection calls libclamav.  Disable
the broken ELF heuristic, which is generating a lot of false
positives.  We don't really need it considering we have almost a half
dozen other ELF-specific checks in rpminspect.  Also disable the size
limit so that we don't get false positives on very large packages.
=> [new] Disable broken ELF heurisitic and size limit in libclamav

lib/debug.c, src/rpminspect.c
Modify the dump_cfg() function to just write YAML to stdout.  Remove
the leading header and replace it with a comment.  Remove the 4
character indent on every line as well.
Also modify the handling of the -D option.  If you specify -D with no
build identifiers, rpminspect will dump the configuration and exit 0.
This also works if you want to pass it a configuration file to use but
just want to see what the final runtime configuration looks like.
You can use "rpminspect -D > config.yaml" to campture the runtime
configuration to a file.
=> [new] Modify dump_cfg() to write valid YAML to stdout (#306)

include/rpminspect.h, include/types.h, lib/abi.c, lib/debug.c, lib/files.c, lib/free.c, lib/init.c, lib/inspect_abidiff.c, lib/inspect_annocheck.c, lib/inspect_elf.c, lib/inspect_javabytecode.c, lib/inspect_kmidiff.c, lib/inspect_pathmigration.c, lib/listfuncs.c, lib/readelf.c, lib/runcmd.c, src/rpminspect.c
This is an internal changeup to use uthash.h over the glibc provided
hsearch hash table routines.  It's just an implementation change and
not a functional change.  This commit gets most of what remains, but
not everything.
=> [lib] Migrate more code off hsearch and to uthash

include/types.h, lib/kmods.c
Another bit of code refactoring in the kmod inspection.  Drop the use
of the hsearch routines in kmods.c.  The entire
finalize_module_aliases() function can be removed and the data
structure simplified.  It's now just one hash table as opposed to a
struct, a linked list, an int, and a hash table with a char * key and
a linked list value.
=> [lib] Replace hsearch() with uthash in the kmod inspection

MISSING, TODO
Note what parts of the rpmdiff TEST_METADATA check are implemented and
which parts are not.
=> [doc] Update TEST_METADATA status in TODO and MISSING

include/rpminspect.h, include/types.h, lib/abi.c, lib/inspect_abidiff.c, lib/listfuncs.c
The data structures have been replaced with a single abi_t hash table.
=> [lib] Replace hsearch() with uthash in the abidiff inspection

lib/inspect_annocheck.c, src/rpminspect.c
I recently replaced the hsearch() usage with uthash.  There were two
places where I neglected to replace the 'entry->data' variable with
'hentry->key' to match the new variables and types.  This patch fixes
the SIGSEGV caused by that problem.
=> [fix] Correct misuse of 'entry' with 'hentry' variables (#321)

lib/inspect_pathmigration.c
Another mistake I made converting this over from hsearch() to uthash.
=> [fix] Use hentry->key over hentry->value in 'pathmigration'

lib/init.c, osdeps/arch/post.sh
I was not properly keeping track of where I was in the YAML configuration file.  Since I have block names that match inspection names, this is important when reading a subset configuration file (such as a profile).  What I've done is add a level counter and increment and decrement that based on the YAML tokens I get back from libyaml.  The stream technically starts at level 0, but you'll never get back to that before descending again so I let it count up to 1 and beyond but then only ever decrement back to 1 before the stream ends.  The result here is that when you return to level 1 then the block and group indicators are reset which allows reading a new section in the configuration file.
=> [fix] In read_cfgfile(), keep track of block depth correctly (#329)

rpminspect.spec.in
This addresses some bugs found in libabigail 1.8 and 1.8.1.  Increase
the RPM dependency here so installed versions of rpminspect use the
correct version of libabigail.
=> [bld] Recommend or Require libabigail >= 1.8.2

TODO, lib/builds.c, lib/checksums.c, lib/copyfile.c, lib/debug.c, lib/files.c, lib/init.c, lib/inspect_changedfiles.c, lib/inspect_changelog.c, lib/inspect_emptyrpm.c, lib/inspect_javabytecode.c, lib/inspect_kmod.c, lib/inspect_license.c, lib/inspect_lostpayload.c, lib/inspect_manpage.c, lib/inspect_ownership.c, lib/inspect_runpath.c, lib/inspect_shellsyntax.c, lib/inspect_symlinks.c, lib/inspect_virus.c, lib/koji.c, lib/local.c, lib/output_json.c, lib/output_text.c, lib/pic_bits.sh, lib/uncompress.c, lib/unpack.c
Migrate most of the error reporting to warn(), warnx(), err(), and
errx().  This drops the use of fprintf, fflush, and sometimes abort in
cases where I wanted to stop execution.  The err.h functions will
handle strerror() for me and in cases where that doesn't happen I use
the called library's error string function if available.
=> [lib] Finish normalizing all the error reporting statements

lib/builds.c, lib/koji.c, src/rpminspect.c
Also make sure we don't leak in download_build() in cases where the
build does not exist in Koji.
=> [fix] Get rid of invalid free() in get_product_release()

include/inspect.h, lib/init.c, lib/inspect.c
Given an inspection name, return its ID number as used in
librpminspect.  This is part of a larger coming that will track
per-inspection includes and excludes.
=> [lib] Add inspection_id() to librpminspect

lib/inspect_patches.c
Use long unsigned int variables to report file size changes in the
patches inspection.
=> [fix] Use long unsigned int to report size changes in 'patches'

lib/readelf.c
For the purposes of determining if a file is a shared library or not,
the is_elf_shared_library() looks at the ELF type and looks for a
DT_SONAME value.  While it is possible to build a shared library
without a DT_SONAME, the whole point is for providing a shared library
to other programs.  So we will not consider an ELF object a shared
library unless it is ET_DYN and has a non-NULL DT_SONAME value.
=> [fix] Check DT_SONAME in is_elf_shared_library()

lib/inspect_abidiff.c
There are no ABI guarantees for debuginfo and debugsource packages.
=> [fix] Skip debuginfo and debugsource files in abidiff

test/test_abidiff.py
Using rpmfluff, make sure the test libraries set a DT_SONAME since
is_elf_shared_library() now requires that in order for the abidiff
inspection to run on the file.
=> [tst] Make sure abidiff test cases add a DT_SONAME to the test lib

lib/inspect_changedfiles.c
Some systems have versions of libmagic (and the magic database) that
do not register all compression file types.  In this case I noticed an
Arch Linux system will report "application/octet-stream" for
xz-compressed files.  So as a fail safe, add an additional check that
looks for application/octet-stream and the filename ending.  Not
perfect.
=> [fix] Handle old or broken versions of libmagic in 'changedfiles'

include/rpminspect.h, lib/builds.c, lib/files.c, lib/inspect_changedfiles.c, lib/inspect_removedfiles.c, lib/inspect_shellsyntax.c, lib/inspect_virus.c, lib/listfuncs.c, lib/output_xunit.c, lib/strfuncs.c
When I originally wrote this it was just to append single strings on
to another.  But I find I might want to append more than one.  Change
it to work as a variadic function.  Everything still has to be a
string to append.  I'm not doing a format string or anything.
Terminate the list of strings to append with NULL.  Also, the first
argument must be an allocated char *.  strappend() will realloc this
string.  You can't start it with NULL.  If you want to start it with
an empty string, then pass it a strdup("").  The caller still has to
free what strappend returns, but that was always the case.
=> [lib] Change strappend() to work as a variadic function

lib/init.c, lib/inspect_javabytecode.c
init.c was not reading the javabytecode block correctly, so the
javabytecode inspection failed to run since ri->jvm was then NULL.
=> [fix] Fix reading of the javabytecode block in the config file

include/rpminspect.h, lib/inspect_elf.c, lib/listfuncs.c, lib/pic_bits.sh
I initially thought the problem here was with the function generated
by our pic_bits.sh script.  It generates is_pic_reloc() based on the
contents of the build system's elf.h file.  But this function was
working correctly.  The issue came down to improper use of my own list
structures and always treating missing PIC data in the after build as
a loss of -fPIC at build time.
I have corrected inspect_elf.c so it makes better use of the list
functions in listfuncs.c.  The listfuncs.c functions have also been
modified to return NULL when there is no data rather than always
returning an empty list.  Likewise, in inspect_elf.c, the
elf_archive_iterate() calls can take a NULL list parameter and
initialize if necessary.
=> [fix] Catch missing/losing -fPIC correctly on .a ELF objects (#352)

src/rpminspect.c
If multiple builds are specified, they were being written to the first
build's download directory.  This patch ensures each build is written
to workdir as specified with the -w option.
=> [cmd] Fix fetch only mode download directory

lib/builds.c
I'm going to add a slightly different verbose mode progress indicator
here, but not now.  Just stub it out first.
=> [lib] Stub out libcurl download progress callback function

lib/fileinfo.c, lib/inspect_ownership.c
The fileinfo files carry what is basically an 'ls -l' style output of
files we package that carry special permissions and ownerships.  The
ownership inspection then checks files found against that list to make
sure they are allowed.  The inspection was performing a local name
lookup on the owner and group and also comparing the UID and GID
values, but that is not guaranteed.  Some packages will dynamically
create the owner and/or group via a package scriptlet.  The RPM header
records the symbolic name as do our fileinfo files, so just perform
matching based on that.
=> [fix] Perform symbolic owner and group matching in 'ownership' (#364)

lib/ignore.c, lib/init.c
The following inspections all per-inspection ignore lists in the
configuration file:
elf, manpage, xml, desktop, changedfiles, addedfiles, ownership,
shellsyntax, filesize, lto, annocheck, javabytecode,
pathmigration, files, abidiff, kmidiff, badfuncs, runpath
This patch enables reading in those blocks if they exist and adding
them to the ri->inspection_ignores hash table.  Note that we still
have global ignores.  This is just another refinement of specifying
glob(7)'s to ignore on a per-inspection basis.
=> [lib] Read per-inspection ignore lists from the config file.

data/generic.yaml
For all of the inspections that allow per-inspection ignore lists, add
commented out blocks to generic.yaml to show that it is a valid
configuration setting.
=> [cfg] Add commented out per-inspection ignore blocks

lib/inspect_annocheck.c
Failures in annocheck return a non-zero exit code, so make sure we
handle that correctly for reporting.
=> [fix] Report annocheck failures correctly in librpminspect.

data/generic.yaml, lib/inspect_files.c
This one operates a little differently than the other ignore lists.
Since the 'files' inspection is reading the %files lists in spec
files, we need to treat the ignore list here as a list of path
prefixes to ignore rather than a list of glob(7) specifications to
match.  Adjust the comment to reflect that.  Modify the inspection
code to make use of the ignore list since this inspection does not use
foreach_peer_file().
=> [lib] Check ignore list in 'files' for path prefixes to ignore (#360)

data/generic.yaml, include/types.h, lib/free.c, lib/init.c, lib/inspect_emptyrpm.c
Some packages build meta packages which have empty payloads but serve
as a way to control what packages are installed.  This patch adds a
way to list the expected empty RPMs so the emptyrpm inspection still
runs, but does not fail when it encounters expected empty packages.
=> [lib] Support a list of expected empty RPMs in the config file (#355)

src/rpminspect.c
Do not assume the argument to -c will specify a valid file.  Handle
cases where we lack any configuration file to get things going and
exit with code 2.
=> [cmd] Do not crash with the -c option specifies a non-existent file

test/test_manpage.py
I did this for some tests but not all.  Explicitly disable it where I
expect rpmbuild to not compress man pages.  I really don't like that
default behavior of rpmbuild, but whatever.
=> [tst] Make sure brp-compress is disabled in test_manpage.py

rpminspect.spec.in
That is what rpminspect needs, no need to know the package name.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1941131
=> Require/Recommend /usr/bin/annocheck

data/generic.yaml
If size_threshold is 'info' in the config file, the filesize
inspection will report all filesize changes at the INFO reporting
level.
=> [cfg] Note size_threshold can be the keyword 'info'

lib/inspect_xml.c
libxml does not always give an error string during validation, so
don't assume we have something we can strdup().
=> [fix] Ensure ctxt->lastError.message is not NULL before strdup (#382)

lib/init.c
Leave the code block in place, but disable by default.  I am leaving
this here because the ignore list code is relatively new and I want to
have this handy in case bug reports come in where I need to dig in to
a per-inspection ignore list.
=> [lib] Disable debugging output for the ignore lists in init.c

lib/inspect_xml.c
It was a bit too verbose for debugging output to ship.
=> [lib] Drop debugging output in the 'xml' inspection

src/rpminspect.c
If rmtree() errors here, just proceed.  In most cases it means there's
another rpminspect job running and the working directory is in use.
=> [cmd] Remove what working directories we can

lib/inspect_upstream.c
In the upstream inspection, be sure to only look at the list of
RPMTAG_SOURCE entries when looking for what source files have been
removed.  The foreach_peer_file() iterator is going over every file in
an SRPM, which includes patches.  So if patches disappear, that is
incorrectly reported as a disappearing SourceN file.
=> [fix] Only look at RPMTAG_SOURCE entries for removed sources

include/rpminspect.h, lib/arches.c, lib/builds.c, lib/init.c, lib/inspect_disttag.c, lib/inspect_emptyrpm.c, lib/inspect_lto.c, lib/inspect_ownership.c, lib/inspect_patches.c, lib/inspect_pathmigration.c, lib/inspect_runpath.c, lib/inspect_shellsyntax.c, lib/inspect_upstream.c, lib/listfuncs.c, lib/rebase.c
There is a regular thing I do in librpminspect which is "check this
list to see if the following string is in it".  I added a function to
do this so I don't have to remember how to construct the TAILQ_FOREACH
each time.  An added bonus is this deletes 62 lines of code.
=> [lib] Add list_contains() to librpminspect

include/inspect.h, lib/inspect_arch.c, lib/inspect_upstream.c, lib/listfuncs.c, lib/rpm.c
The arch inspection is meant to alert developers to lost target
architectures between one build and the next.  Usually in the context
of product maintenance.  Loss of a noarch package should not be
considered the same thing as those are not really architectures in the
context of this inspection.
=> [fix] Ignore noarch packages in the 'arch' inspection

lib/inspect_emptyrpm.c
Make sure we skip source packages in the emptyrpm inspection.  The
purpose of this inspection is to catch built RPMs with empty payloads.
At the very least a source RPM will always have a payload that at
least consists of the spec file.
=> [lib] Skip source packages in 'emptyrpm'

lib/inspect_desktop.c, test/test_desktop.py
According to the desktop-entry-spec [1], menu implementations may ignore a desktop file in case it has a `TryExec` key, and what is mentioned there either does not exist, or it is not executable.
Hence, in case `Exec` does not exist in the inspected RPMs, check whether `TryExec` was specified: if so, then only report the missing `Exec` as INFO, rather than VERIFY.
Includes some mostly no-op code refactoring that makes the fixes much easier to develop & review.
[1] https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
Fixes: #395
=> [fix] desktop: demote as INFO a missing Exec w/ TryExec (#395)

include/rpminspect.h, lib/diags.c, lib/meson.build, po/POTFILES, po/rpminspect.pot, src/rpminspect.c, test/test_upstream.py
This section lists the command line used to invoke the program and
also version information for dependent libraries and external
programs.  Not everything is listed here because some libraries lack
an API call to get version information.  For now this report excludes
desktop-file-validate, libkmod, libelf, libmandoc, and libcap.  But
what is there is an improvement and should help when debugging issues
and answering questions for users.
=> [new] Output new 'diagnostics' section in rpminspect report (#280)

lib/ignore.c, lib/init.c
Two main things:
1) Allow relative file globbing in the ignore lists.
2) Support a per-inspection ignore list for 'types'.
=> Support relative file globbing and a types inspection ignore list

lib/diags.c, meson.build
Extend the API support in meson.build so we can build with older
versions of libmagic, libarchive, and libcrypto.
=> [ci] Support older libraries on CentOS 7

lib/diags.c
Older versions of OpenSSL lack this definition in the headers.
=> [ci] Define OPENSSL_VERSION to 0 if it's undefined

lib/builds.c, lib/init.c
This function returns 0 if there's an error.  We need to do that to
find malformed YAML input files and then bail.  Otherwise the YAML
parsing loops in librpminspect will run indefinitely.
=> [fix] Check return code of yaml_scan_parser()

lib/inspect_patches.c
In the patches inspections, we should always report new patches at the
INFO level.  The threshold counting for number of files or number of
lines triggering a VERIFY reporting level is still there.  New patches
can appear in maintenance or rebase builds, but should be taken as
addressing one or more bug fixes.  Reporting levels should not change
until we can examine patch size changes.
=> [lib] Report new patches at the INFO level only

lib/abi.c, lib/inspect_disttag.c, lib/macros.c, po/rpminspect.pot, test/data/SPECS/good.spec
This one was failing to pick up %{?dist} coming from other defined
macros.  Caused by my use of Python regex syntax in C.  Ooops.
=> [fix] Use a simpler and correct regexp for the disttag inspection (#412)

README.md
I no longer make any effort to ensure rpminspect works with LibreSSL.
This library began as a drop-in replacement (mostly) for OpenSSL, but
over time it has diverged in to its own API.  If anyone wants to
submit patches that ensure rpminspect works with LibreSSL, I am happy
to review them.
=> [doc] Drop mention of LibreSSL from README.md

lib/inspect_types.c
The libmagic MIME type for spec files tends to vary and there is no
MIME type for an RPM spec file.  But that really doesn't matter
because the types inspection can just ignore spec files.  If we have a
built RPM or a Koji build, then there was a valid spec file provided
in the first place.
The purpose of the types inspection is to catch type changes for
runtime data used by programs or examples provided.  We let it run
across all files for completeness but in this case we can ignore spec
files in source RPMs.
=> [fix] Skip .spec files in the types inspection

lib/inspect_metadata.c, test/test_metadata.py
It's not uncommon for the package Descriptions or Summary lines to
change in a maintenance build.  These changes are now reported at the
INFO level.  Previously they were reported at the INFO level if the
builds compared were a rebase, otherwise it would report them as
VERIFY.  The idea here I think was to restrict non-code changes in
maintenance builds, but personally I feel that Description and Summary
changes are ok in a maintenance build.
The bad words check is still there and any matches trigger a BAD
result.
=> [fix] Description and Summary changes are reported as INFO

lib/inspect_license.c, test/data/licenses/test.json, test/test_license.py
If the fedora_abbrev and spdx_abbrev values are missing for a license
entry, then fall back on doing a full string match of the License tag
value and the fedora_name value.  Some packages, like linux-firmware
in Fedora, use a special value in the License tag that we lack any
official abbreviation for.  There will likely be others.  There always
are.
=> [fix] Fall back on full license name if there are no abbrevs

include/inspect.h, lib/inspect_addedfiles.c, lib/inspect_capabilities.c, lib/inspect_changedfiles.c, lib/inspect_ownership.c, lib/inspect_permissions.c, lib/inspect_removedfiles.c, src/rpminspect.c
Some inspections produce results that librpminspect marks with
WAIVABLE_BY_SECURITY.  This is simply a categorization type thing.
Any result in this category is broadly considered "important for
security purposes".  That means that disabling an inspection via the
config file or command line option will still run it anyway if it
could possibly generate a security result.  If the inspection is
disabled, the non-security results are skipped and only security
results would show up.
The main reason for this change is to shift control of
WAIVABLE_BY_SECURITY findings to be controlled by settings in the
rpminspect-data package.  That ways changes to the vendor's data
package can have a workflow applied to ensure the security changes are
validated by some security team or group or something. …
=> [lib] Always run inspections with possible security results

lib/macros.c, test/data/SPECS/good.spec
This is a mini macro parser for the purposes of reading the Release
tag value.  Just make sure we skip over "complex" macro lines to avoid
trying to parse them here.
=> [fix] Ignore "complex" spec file macros in get_macros()

include/meson.build, include/secrules.h, include/types.h, lib/free.c
The security_t data structure will hold the product security rules as
found in the vendor data directory.  Each entry will contain a package
name, version, release, and a secrule_t hash table.  A secrule_t will
contain a secrule type and action.
=> [lib] Define security_t and secrule_t in librpminspect

src/rpminspect.c
Use the sigaction() POSIX API for signal handlers rather than the
older signal() API.
=> [cmd] Use sigaction() instead of signal() in rpminspect(1)

include/rpminspect.h, lib/koji.c, lib/mkdirp.c, lib/rmtree.c, src/rpminspect.c
Clean up the librpminspect usage of xmlrpc-c.  All xmlrpc_value
variables need to be cleared using xmlrpc_DECREF since the library
does this whole reference counting thing.  *but* other variable types
from the library, so as those created with a *_new() function usually
(but not always) have a corresponding *_free() function.  What I have
found is that if you get an xmlrpc_value back from a function, then
you need to DECREF it.  Otherwise look for a free type function and
use that.
Also clean up some other memory management mishaps in the downloading
code and the rpminspect command line program.
=> [fix] Fix a lot of xmlrpc-c memory leaks in builds.c

lib/builds.c
At least on CentOS 7 systems and system very much like CentOS 7, I
need to support the old API for displaying download progress bars.
=> [fix] Support the legacy libcurl API in librpminspect

osdeps/centos7/defs.mk
Similar to the Debian-derived platforms, pass this environment
variable to avoid pip installs dragging in a ton of Rust stuff that
won't build.
=> [ci] Pass CRYPTOGRAPHY_DONT_BUILD_RUST=1 to pip on centos7

osdeps/centos7/pre.sh, osdeps/centos7/reqs.txt
Not sure why this was not working in my test environment earlier, but
this is what I need to be doing so restore the behavior.
=> [ci] Restore previous centos7 pip and setuptools behavior

lib/inspect_emptyrpm.c
If a user declares a list of expected empty RPM packages, the emptyrpm
inspection should return successfully if all RPMs pass.
Resolves #430
=> [fix] Adjust where the 'good' bool is set in the emptyrpm loop

src/rpminspect.c
I can't remember why I added this, but I think it was for reporting in
the log output.  At any rate, this really isn't needed now so I am
just going to remove it.
Fixed #433
=> [cmd] Discontinue realpath() call on argv[0]

include/inspect.h, src/rpminspect.c
When I modified librpminspect to always run the security checks, I
also modified the command so any inspection with a security check
can't be skipped.  This is not very intuitive given the -T and -E
options, so this patch restores the -T and -E behavior.  However, if
an inspection runs with security checks then those security checks are
always run regardless of settings in a config file.
=> [cmd] Honor -T/-E correctly even with security-focused checks

include/rpminspect.h, lib/inspect_ownership.c, lib/rpm.c
Turn the former static function in inspect_ownership.c in to a
function in rpm.c that can be used elsewhere.
=> [lib] Replace get_header_value() with get_rpm_header_value()

lib/inspect_capabilities.c, test/data/capabilities/GENERIC, test/meson.build, test/test_capabilities.py
librpminspect had been relying on libcap to read the actual extracted
file for capabilities(7) in the package.  This is a problem because
not all capabilities can be set by non-root users.  RPM deals with
this by taking file capabilities and putting them in the header so
they are applied when the package is installed or upgraded.
This patch changes the behavior of librpminspect to read packaged file
capabilities from RPMTAG_FILECAPS and compare those values with what
is in the rpminspect vendor package.
=> [fix] Read file capabilities from the RPM header

include/rpminspect.h, lib/files.c, lib/inspect_capabilities.c, lib/inspect_ownership.c, lib/inspect_runpath.c, test/data/capabilities/GENERIC, test/meson.build, test/test_capabilities.py, test/test_ownership.py
Discontinue reading the extracted file to gather capabilities(7) values.  These cannot be set on extracted files except by the root user.  So instead we gather capabilities(7) from the RPM header and compare them to the capabilities settings in the vendor data package.
=> Read capabilities(7) on packaged files from the RPM header

lib/inspect_runpath.c
This is a followup to 4ac9d0f00b20f28e6c3db0a062a09e4d2b752390 that
fixes the handling of DT_RUNPATH/DT_RPATH entries that are a directory
owned by the package itself.  The check for allowed here meant that
this block was only entered if the config file contained an
allowed_paths list under the runpath block, which is incorrect.  That
list is optional.  This patch fixes the behavior so it works correctly
if the list is present or missing, but still honors it correctly.
Fixes #454
=> [fix] Handle DT_RUNPATH/DT_RPATH owned directories correctly

lib/inspect_desktop.c
on libreoffice-startcenter.desktop rpminspect claims it references
icon 'libreoffice' but it really references 'libreoffice-startcenter'
because tmp points to the result of 'Exec' not 'Icon'
=> fix misleading output from desktop icon check

doc/configuration.rst
Rather than duplicating all of the content in generic.yaml, link to it
after the explanation of the config file.
Fixes #405
=> [doc] Link to generic.yaml from configuration.rst

data/security/GENERIC, doc/configuration.rst, include/constants.h, include/rpminspect.h, include/secrules.h, include/types.h, lib/init.c
This commit adds in the code that reads in the security rules for the
product during the initialization phase.  librpminspect will collect
all the rules first because it will need to use them across a variety
of inspections.
=> [lib] Add security rule reading code to librpminspect

include/secrules.h, include/types.h, lib/free.c, lib/init.c
Working on the rule implementation revealed that I actually need each
rule and can't use a hash table because there's no easy way to create
a key given an RPM header, so there's nothing to retrieve an element
with.
=> [fix] Convert the security rules from a hash table to a list

include/types.h, lib/strfuncs.c, test/lib/test-strfuncs.c
This has never been used and is out of place now.  The reason it
exists is from ideas originally obtained from rpmdiff.  The
implementation of rpminspect does deals with things rpmdiff called
waivers in a different way.
=> [lib] Removed RESULT_WAIVED from severity_t

include/results.h, include/rpminspect.h, include/types.h, lib/fileinfo.c, lib/free.c, lib/init.c, lib/inspect_addedfiles.c, lib/inspect_capabilities.c, lib/inspect_ownership.c, lib/inspect_permissions.c, lib/inspect_politics.c, lib/inspect_upstream.c, lib/results.c
For some inspections the correct thing to do may be to edit the data
file from the vendor data package.  Improve these remedy strings by
reporting what file to change and advise users to send a patch.  I say
send a patch here to avoid using git-specific terminology because I
know if I do that, then we'll replace git with something and the git
terminology will be outdated.
=> [lib] Improve remedy reporting to tell users what data file to edit

data/generic.yaml, lib/fileinfo.c, po/POTFILES, po/rpminspect.pot
Note that the types inspection can have a section with an ignore list
in the rpminspect.yaml file.  In the actual inspections, improve the
fileinfo reporting to note that an expected or unexpected value was
found.  In the case of unexpected values, report what was expected.
The previous wording was lifted from rpmdiff and did not mention what
the expected value was, just that there _was_ an expected value.
=> [lib] Improve permission and ownership reporting strings w/ fileinfo

lib/init.c
Subsequent config file block reads were not overriding previously
config file blocks, only merging them together.  This becomes a
problem for config file blocks that are lists.  For that to work,
subsequent file reads need to just override the previously read list.
This patch fixes that problem.
In issue #485, the problem is the 'badfuncs' list override in the
per-package rpminspect.yaml would not wipe the system-wide list before
performing the inspection.  It now does.
Fixes: #485
=> [lib] Properly override config file blocks in subsequent reads

rpminspect.spec.in
We now have translations, so pick those up at build time and include
them in the rpminspect package.  The translations span both the end
user program and the shared library, but I am putting them in the end
user program package.  If you install that, you also get the shared
library.
=> [bld] Add %find_lang to the package spec file

rpminspect.spec.in
Get rid of the separate changelog included as Source1.  Include the
detached signature (.asc) as Source1 instead and Source2 is the GPG
keyring used to validate the source archive signature.
In %prep, use %gpgverify and %autosetup.  And drop everything after
%changelog as that will be handled by the submit-koji-builds.sh script
so that changelog in the spec only exists downstream.
Fixes: #507
=> [bld] Update the spec file template

CHANGES.md, doc/release.rst, rpminspect.spec.in
Rather than keeping this in the spec file %changelog, create a regular
text file listing the changes per release.
Fixes #505
=> [doc] Add CHANGES.md file summarizing changes per release

data/generic.yaml, include/types.h, lib/free.c, lib/init.c, lib/inspect_disttag.c, lib/macros.c, rpminspect.spec.in, test/test_disttag.py
Add a new 'macrofiles' section to the config file.  This section is where you list the file paths (glob(7) syntax and RPM macros are allowed) of all the RPM macro files that should be used when running rpminspect.  This will vary by vendor and platform.
Add macro expansion via librpm to the disttag inspection.  The existing code just did a pass across macros defined in the package's spec file.  Now we load all macros available on the system with the exception of ~/.rpmmacros.  This allows the disttag inspection to work with things like %autorelease or other systemwide macros that handle the dist tag transparently.
We still keep the manual pass across local spec files macros to avoid loading the entire spec file as if we are running rpmbuild.
The rpminspect.spec.in template also adds a …
=> Support %autorelease and other system wide macros in the disttag inspection

lib/inspect_desktop.c, test/test_desktop.py
Be sure to check subpackages for icons and executables in the desktop
inspection.
Fixs: #467
=> [lib] Check subpackages when running the 'desktop' inspection

lib/fileinfo.c
This was leftover before I did some refactoring and is unnecessary.
Fixes: #526
=> [fix] Remove unnecessary assert() on fname in match_fileinfo_mode

lib/inspect_emptyrpm.c
If we came across expected empty RPMs and everything else looks good,
then this inspection falls through to reporting the overall "OK"
result.  But if we encountered any expected empties, then we already
got some information results.  In those cases suppress the generally
OK result.
Fixes: #530
=> [fix] Do not report 'OK' result in emptyrpm for expected empties

include/rpminspect.h, lib/inspect_annocheck.c, lib/paths.c
The debuginfo matching code was not taking in to account the fact that
a build may include multiple debuginfo subpackages.  A common practice
now in distributions like Fedora Linux is to have one debuginfo
package for each subpackage.  In older distributions the common
practice was to include a single debuginfo package for the entire
build which covered all subpackages.
This patch modifies librpminspect to handle both types of environments
since some RPM systems may still build a single debuginfo package for
the whole build while others may have one per subpackage.
The matching code may need further work in the future depending on how
distribution policies evolve.  A better long term solution would be to
find the matching executable in a candidate debuginfo tree and if that
is found, use …
=> [fix] Correctly match debuginfo trees to subpackages

lib/builds.c, lib/checksums.c, lib/copyfile.c, lib/files.c, lib/init.c, lib/inspect_changedfiles.c, lib/inspect_changelog.c, lib/inspect_desktop.c, lib/inspect_javabytecode.c, lib/inspect_kmod.c, lib/inspect_license.c, lib/inspect_manpage.c, lib/inspect_ownership.c, lib/inspect_patches.c, lib/inspect_runpath.c, lib/inspect_shellsyntax.c, lib/inspect_symlinks.c, lib/inspect_virus.c, lib/local.c, lib/mkdirp.c, lib/paths.c, lib/peers.c, lib/readelf.c, lib/rebase.c, lib/rpm.c, lib/uncompress.c, lib/unpack.c
This was an inconsistent thing for a while and I never could make up
my mind on the reporting style.  In the end I decided to do away with
messages like this:
fopen(): Unknown file
And it now will look like this:
fopen: Unknown file
The parens are unnecessary in the reporting.
=> [fix] Remove unnecessary '()' from function names in error messages

include/rpminspect.h, lib/diags.c, lib/inspect_abidiff.c, lib/inspect_annocheck.c, lib/inspect_changedfiles.c, lib/inspect_changelog.c, lib/inspect_config.c, lib/inspect_desktop.c, lib/inspect_doc.c, lib/inspect_kmidiff.c, lib/inspect_patches.c, lib/inspect_shellsyntax.c, lib/inspect_upstream.c, lib/runcmd.c
This PR contains a refactoring of the runcmd.c code away from using popen() and over to using a fork()/execvpe() model with pipe() and dup2() to redirect and collect stdout and stderr of the child process for reporting back to the caller.  The advantage we gain from this model is that run_cmd() can now detect if the child terminated due to a signal, such as SIGABRT.  popen() doesn't allow for that as it invokes commands with a 'sh -c' so any signal detection would be of the shell receiving signals and not the actual command you wanted to run.  In a way, this run_cmd() refactoring is building a custom popen() for use in librpminspect.
The exit code of the child process is handed back to the caller if requested, as is the combined stdout and stderr output.  Both of those can be ignored by …
=> Refactor runcmd and update the inspections that use it

lib/runcmd.c
This was not available until glibc 2.26 and anyways it's not part of
the standard, it's just a handy BSD extension.
=> [fix] Use realloc() instead of reallocarray()

MIT.txt, rpminspect.spec.in
Some of the code in librpminspect is adapted from examples on this
blog post:
https://begriffs.com/posts/2019-05-23-unicode-icu.html
The author has provided that code under the MIT license.  The
explanation, email, and a copy of the license are provided in the
MIT.txt file.
=> Add MIT.txt to the package for MIT-licensed code

.github/workflows/extra-ci.yml
At least test_unicode.py requires this on some older systems, so just
set it always.
=> [ci] Set LANG=en_US.UTF-8 when running the test suite

osdeps/alpine/reqs.txt
Adjust the package name that brings in the icu library and header
files for development.
=> [ci] icu -> icu-dev in reqs.txt for Alpine Linux

lib/inspect_license.c
In the license inspection, fallback on the fedora_name field if it
contains text and both fedora_abbrev and spdx_abbrev are empty.  An
abbrev field with text that begins with '#' is considered a comment
and the field is treated as empty in the code.
Fixes: #546
=> [fix] Fallback on fedora_name only if the _abbrev fields are empty

include/types.h, lib/free.c, lib/rpm.c, src/rpminspect.c
The header cache was a tailq, but convert it to a hash table since the
package name is used as a key anyway.  Also fix a small memory leak.
=> [lib] Convert RPM header cache to a hash table, fix leak

lib/inspect_desktop.c
Only display unambiguous warnings, not additional helpful tips "about things that might be improved"
f.e.
libreoffice-math.desktop: hint: value "Office;Education;Science;Math;" for key "Categories" in group "Desktop Entry" contains more than one main category; application might appear more than once in the application menu
=> run desktop-file-validate with --no-hints

lib/inspect_javabytecode.c
The maximum version check of 60 for Java bytecode now fails when
encountering valid bytecode from Java 17 (61) or Java 18 (62).  As
Java releases now occur on a six-month cycle, retaining the current
version check would mean bumping this line a couple of times a year.
It seems better to just remove the check as a maximum bound check is
already performed against supported_major, which can be configured
externally without rebuilding rpminspect.
=> [fix] Remove hardcoded maximum version check on Java bytecode

lib/builds.c, src/rpminspect.c, test/baseclass.py, test/test_types.py
rpmfluff provides SimpleRpmBuild which the test suite uses extensively.  But there are some test cases that just need to create an SRPM, or more importantly a bad SRPM.  I created the SimpleSrpmBuild class that inherits from SimpleRpmBuild but only creates an SRPM for use in the test cases.  This adjusts the class inheritance in baseclass.py but everything should still work as expected.  The SRPM-specific test cases throughout the test suite will now just have an SRPM built instead of all of the packages.
=> Create SimpleSrpmBuild class in the test suite and update tests

test/test_unicode.py
In cases where rpminspect cannot run the %prep section of the spec
file, it will fall back on manually unpacking any source archives
found and scanning all of the files in there.
=> [tst] Add unicode test cases covering rpmSpecBuild() failures

lib/inspect_unicode.c
In the unicode inspection, make sure librpm and librpminspect have
proper cleanups done on exit so we don't get valgrind errors.
=> [fix] Exit the manual_prep_source() child process correctly

lib/unpack.c
Use archive_read_free() instead of archive_read_close().  The
archive_read_free() function will call archive_read_close() if
necessary and then free allocated resources.
=> [fix] Use archive_read_free() in unpack.c

lib/readelf.c
is_elf() was only checking whether or not a file is an ELF shared
object, but it needs to also check for ELF archives.
This modifies the changedfiles inspection so it excludes *.a static
libraries.
=> [fix] Make sure is_elf() returns true for ELF archives (*.a)

test/baseclass.py
Systems like CentOS 7 use an older version of rpmfluff and as such our
test suite needs to try to work with it.  This modification is easy
enough to carry so we can still continue supporting CentOS 7 and
derivatives.
=> [tst] Support older versions of rpmfluff in baseclass.py

lib/inspect_desktop.c
If a desktop file names an explicit icon file, match the filename and
check the MIME type to see that it's an "image/" rather than looking
for a specific file extension.
=> [fix] Match MIME type on Icons in the desktop inspection

lib/inspect_removedfiles.c, lib/rebase.c
When comparing rebased builds, any files found by the removedfiles
inspection should be reported at the INFO level.
Fixes: #561
=> [fix] Report removed files at INFO level in rebase comparisons

include/rpminspect.h, lib/files.c, lib/inspect_doc.c, lib/inspect_emptyrpm.c, lib/inspect_lostpayload.c, test/test_emptyrpm.py
Packages that contain only %ghost entries in their %files section will
have an empty payload, but that is expected.  Expand the emptyrpm
inspection to honor this state so that you do not need to list it in
the rpminspect.yaml file as an expected empty payload.  The empty
payload will still be reported at the INFO level.
Fixes: #564
=> [lib] Expand the emptyrpm inspection to handle %ghost entries

lib/rebase.c
Followup to previous fix for the emptyrpm inspection.  The bn string
may be NULL, but if it isn't then an must match it.
=> [fix] Handle single build runs in is_rebase()

include/rpminspect.h, lib/builds.c, lib/local.c, test/baseclass.py
The -w option was added a while ago to allow users to specify an
alternate working directory.  This is most useful for the fetch mode
(-f).  However, it becomes a little clumsy if you fetch a build to
your current directory and then try to run rpminspect using that
locally cached build as input.  rpminspect actually downloads it
again...sometimes.
This patch sorts out the directory handling for fetch and non-fetch
modes of operation in rpminspect so the correct behavior happens.
Fixes: #529
=> [fix] Handle the -w option correctly for fetch and non-fetch modes

include/inspect.h, src/rpminspect.c
Brings it more in line with the other inspection reporting even though
the diagnostics reporting isn't strictly an inspection.
=> [lib] Replace direct use of "diagnostics" with NAME_DIAGNOSTICS

lib/abi.c
In the ABI files, honor blocks that begin with either "[level N]" or
"[level-N]".  The hyphen was required and that's sometimes left off in
the configuration file, but it's not strictly required.
=> [fix] Read ABI level blocks with "level N" or "level-N" names

include/output.h, include/rpminspect.h, include/types.h, lib/meson.build, lib/output.c, lib/output_summary.c
This commits adds a fourth output mode for rpminspect.  This one is
called 'summary' because each result is displayed on a single line
with the main thing that happened in the left most column followed by
a description of what happened (this may include the file in question
and/or the architecture) and finally the name of the inspection where
it happened in parens.
Originally requested as an enhancement in issue #26, this patch tries
to provide a similar functionality to the example rpmlint output shown
in that issue.
=> [lib] Add new 'summary' output mode (#26)

lib/inspect_annocheck.c, lib/inspect_badfuncs.c, lib/inspect_desktop.c, lib/inspect_disttag.c, lib/inspect_elf.c, lib/inspect_emptyrpm.c, lib/inspect_filesize.c, lib/inspect_license.c, lib/inspect_lostpayload.c, lib/inspect_manpage.c, lib/inspect_metadata.c, lib/inspect_politics.c, lib/inspect_unicode.c, lib/inspect_virus.c, lib/inspect_xml.c
I am having to go back and make sure all the add_result() calls set
fields used by the summary output mode.  I am working through those
now.  The output is functional, but you might see lines that begin
with "unknown" or contain "(null)" and stuff like that.  I'm just
working through those.
=> [fix] Ensure summary mode output works for a number of inspections

lib/inspect_abidiff.c, lib/inspect_addedfiles.c, lib/inspect_capabilities.c, lib/inspect_config.c, lib/inspect_dsodeps.c, lib/inspect_files.c, lib/inspect_filesize.c, lib/inspect_javabytecode.c, lib/inspect_kmidiff.c, lib/inspect_kmod.c, lib/inspect_lto.c, lib/inspect_movedfiles.c, lib/inspect_ownership.c, lib/inspect_pathmigration.c, lib/inspect_permissions.c, lib/inspect_removedfiles.c, lib/inspect_runpath.c, lib/inspect_shellsyntax.c, lib/inspect_specname.c, lib/inspect_symlinks.c, lib/inspect_types.c, lib/inspect_upstream.c, lib/output_summary.c
This is a final set of updates to librpminspect to support the
'summary' output mode.  There may need to be updates to the messages
it displays and such, but those can be addressed case-by-case.
Fixes: #26
=> [lib] Final update for librpminspect inspections and summary mode

include/rpminspect.h, lib/fileinfo.c, lib/inspect_addedfiles.c, lib/inspect_permissions.c, lib/peers.c
The addedfiles inspection runs for single builds or build comparisons.
The actual added files check only makes sense when comparing builds,
but the inspection runs in both conditions to check for security
related things.  This patch makes sure the addedfiles inspection does
not incorrectly report that every file in every package was added when
just running rpminspect on a single build.
=> [fix] Do not incorrectly report added files for single builds

lib/readelf.c
Drop the newline and use warnx() since there's not an errno to report.
=> [fix] Cleaner error reporting when elf_version() returns EV_NONE

lib/deprules.c, lib/inspect_rpmdeps.c
In build comparison runs that see the entire subpackage set change a
lot, the rpmdeps inspection can crash.  The reason is the inspection
code was assuming that there would at least always be an after peer,
but that's not how it works.  You can have a subpackage only present
in the before build and not the after.  So this patch fixes things up
so the rpmdeps inspection does not make that assumption.
=> [fix] Some build comparisons with missing peers crash 'rpmdeps'

lib/inspect_unicode.c, src/rpminspect.c
The one in validate_file() in inspect_unicode.c is incorrect.  The
ones in rpminspect.c are part of a prior code path where I was using
strstr(), but I removed all that but still kept all the free() calls
for needle.  Removed.
=> [fix] Remove unnecessary free() calls in librpminspect and rpminspect

include/constants.h, lib/inspect_rpmdeps.c
Fix two errors in the rpmdeps inspection:
1) Match the automatic shared library Requires correctly by checking
for both the "lib" prefix on the name and the ".so" suffix.
2) Avoid adding a Provide name to the list of providers if we already
have it.  The big problem here was getting duplicates because of the
different architectures.
=> [fix] Match shared lib Requires correctly & handle multiple Provides

include/rpminspect.h, include/types.h, lib/init.c, lib/output_json.c, lib/output_summary.c, lib/output_text.c, lib/output_xunit.c, lib/results.c, lib/strfuncs.c, src/rpminspect.1, src/rpminspect.c
This is a command line option you can use to filter the results
printed out by rpminspect in the 'text' and 'summary' output modes.
'json' and 'xunit' still output everything since those output modes
are intended for processing by other systems.
To only report results at the VERIFY severity or higher, pass "-s
VERIFY" on the command line.  By default you get all results.  If no
inspection has any results at or above the suppression level,
rpminspect will skip it in the output entirely.
This option is only for text output.  The exit code is still the same
and all of the results are still computed anyway.  The intent of this
option is to give users a way to just see what needs attention if they
are iterating over fixes and builds.  Eventually you will get to an
exit code of 0 and no output …
=> [cmd] Implement the -s/--suppress option in rpminspect

lib/inspect_rpmdeps.c
Seen while checking the a52dec package.  If a package carries the
correct explicit subpackage Requires dependency when rpmbuild picked
up an automatic shared library dependency, rpminspect should be ok
with that.  It is, except it was not handling the explicit subpackage
Requires syntax that uses %{_isa}, such as:
Requires: liba52%{_isa} = %{version}-%{release}
This patch fixes rpmdeps so it handles the above.
=> [fix] Handle explicit shared lib deps with %{_isa} notation

lib/inspect_rpmdeps.c
If a package generates automatic shared library dependencies but also
provides those dependencies, it does not need an explicit dependency
in the form of "Requires: NAME = VERSION-RELEASE" since it's the same
package.  The explicit dependency requirement is meant for SRPMs that
split the built files across multiple subpackages and ensuring the
entire set remains tied as users upgrade and remove packages.
=> [fix] Handle packages that provide automatic shared lib deps

include/types.h, lib/deprules.c, lib/inspect_rpmdeps.c
Note whether or not a dependency requirement is a rich dependency
string or not.  rpminspect does not parse these, but just reports the
changes for informational purposes.
=> [lib] Add is_rich_dep() to mark rich dependency strings in deprules

lib/inspect_annocheck.c
Per the discussion in BZ#2054115, flip this back over to reporting
annocheck failures as RESULT_VERIFY rather than RESULT_INFO.
=> [lib] Report annocheck failures as RESULT_VERIFY

data/generic.yaml, include/types.h, lib/debug.c, lib/init.c, lib/inspect_annocheck.c
Add a new config file setting under the 'annocheck' block called
'failure_severity'.  The default is VERIFY which means when annocheck
exits non-zero, rpminspect will report that result as VERIFY and
depending on the reporting threshold of rpminspect that may trigger a
non-zero exit code from rpminspect.  The user may modify the config
file for rpminspect and adjust the failure_severity to any valid
result severity.  The most common use case is to set it to INFO to
both report annocheck failures but not fail rpminspect.
=> [lib] Make annocheck failure reporting severity a config file setting

data/generic.yaml
rpminspect does not use diff anymore, so the config files do not need
to carry this setting.
=> [cfg] Drop diff(1) command setting from generic.yaml

lib/mkdirp.c, lib/rmtree.c, src/rpminspect.c
Longstanding bug.  On exit, rpminspect tries to clean up after itself
and part of that is wiping what it dumped in the workdir.  However the
cleanup was also removing the workdir.  If you were using the default
location this meant that /var/tmp/rpminspect would be removed and
recreated on each run.  But if you were using -w to specify your own
workdir that maybe you already created and other fun files in, then
rpminspect would also try to remove that directory too.  If it was
empty by the time it finished its FTW_DEPTH, then it would rmdir() it
and it was gone.
This patch fixes the cleanup behavior to not remove workdir itself but
otherwise do the contents cleanup.
I also moved the handling of the -w argument to use wordexp(3) instead
of glob(3) since it is entirely valid to pass a …
=> [cmd] Do not remove default or user-specified --workdir paths

lib/files.c
It is entirely possible for peer to be NULL, so don't assume it always
has a value.
=> [fix] Do not assume peer is not NULL in set_peer()

lib/debug.c, lib/init.c
Under the 'annocheck' block in the rpminspect config file, you can
define a failure_severity to control what result code annocheck
failures report through rpminspect.  The format of the annocheck block
in the rpminspect config file has changed a bit to accomodate this
setting, but I wanted to retain backwards compatibility with existing
blocks.  So the 'jobs:' section is optional for grouping the annocheck
job definitions.  I need to be careful how I handle parsing this block
to avoid picking up the string 'failure_severity' as a job name.
=> [fix] YAML parsing error for the failure_severity setting

lib/macros.c
Doing this drops any already loaded macros, which can cause problems
depending on how rpm is installed on the system.  With load_macros(),
rpminspect should just be piling up macros until it's time to exit and
then cleanup.
=> [fix] Do not call rpmFreeMacros() in load_macros()

doc/Doxyfile, doc/api.rst, doc/conf.py, doc/index.rst, include/constants.h, include/inspect.h, include/output.h, lib/inspect.c
For the next release I want to make sure the library API is documented
and automatically generated for readthedocs.io.  I can use Doxygen for
that, so I need to start updating the comments.  I am putting the API
comments in the public header files and then where necessary reducing
the comments in the library source.
=> [doc] Large set of Doxygen comments in header files

lib/inspect_kmidiff.c, lib/inspect_patches.c, lib/readfile.c
A couple of things.  Handle missing KABI files in the kmidiff test and in general avoid spurious warnings when file reads fail and we just return NULL.
=> Fix errors noted in issue #651

lib/output_xunit.c, lib/strfuncs.c
The output_xunit() function was not properly handling empty
result->msg strings, which could cause a SIGSEGV.
=> [fix] Handle NULL result->msg in output_xunit()

lib/readfile.c
No need to display a warning on stderr.  If we can't read the file by
the name specified, just return NULL.
Fixes: #661
=> [fix] On stat() failure in read_file_bytes(), just return NULL

lib/curl.c
CURLINFO_CONTENT_LENGTH_DOWNLOAD_T does not exist in older versions of
the library, so use CURLINFO_CONTENT_LENGTH_DOWNLOAD instead.
=> [fix] Use CURLINFO_CONTENT_LENGTH_DOWNLOAD on older libcurl releases

include/rpminspect.h, include/types.h, lib/builds.c, lib/peers.c
Split RPM extraction out to a new extract_peers() function and add a
disk space check that verifies the working directory has enough space
to hold all unpacked RPMs.
Fixes: #669
=> [lib] Check for enough disk space before unpacking RPMs

include/rpminspect.h, lib/builds.c, lib/peers.c, lib/strfuncs.c, src/rpminspect.c
Fix up the exit codes for rpminspect and add a function that can
return the descriptive string of an error code.  Add
RI_INSUFFICIENT_SPACE for situations where insufficient disk space is
available for the operation.  This is 4, so at the shell you can check
$? for 4 to see if rpminspect is telling you it needs more disk space.
=> [lib] Add strexitcode() and RI_INSUFFICIENT_SPACE exit code

src/rpminspect.c
Two errx() calls were missing the format string.  Add those in to
suppress various versions of gcc and their worriedness.
=> [cmd] Add missing format string to errx() calls

src/rpminspect.c
This bug affects a lot of packages.  Previously rpminspect lacked
support for dist tags with periods in them.  Let's say you had a dist
tag that looked like this:
.el8_2.2
rpminspect would try to match the product name using the substring
".2".  The reason for this is the match_product() function was taking
the substring from the rindex() position of '.' in the dist tag, which
assumes there's only ever the leading period.
This patch changes the behavior to increment past any and all leading
periods and using the resulting string for the match test.
=> [cmd] Match products with dist tags containing periods

include/rpminspect.h, lib/builds.c, lib/humansize.c, lib/meson.build, lib/peers.c, meson.build
Add human_size() to convert number of bytes in to a human-readable
size for the purposes of the error message before rpminspect exists
with RI_INSUFFICIENT_SPACE.
=> [lib] Display insufficient space messages in human readable sizes

src/rpminspect.c
Only wipe the working subdirectory rather than everything in the
working directory.  This allows multiple rpminspect jobs to run
concurrently.
=> [cmd] Careful cleanup with rmtree() on exit

include/constants.h, include/results.h, include/rpminspect.h, lib/inspect_filesize.c, lib/inspect_javabytecode.c, lib/inspect_movedfiles.c
Working on documenting the remedy strings in results.h, remove unused
strings but also add in some missing ones.  In the library code, make
sure to set remedy strings in inspections where they were missing.  I
guess if no one has reported these by now, no one really pays
attention to them.
=> [lib] Doxygen comment work but also add and use missing remedy strings

lib/inspect_kmod.c, lib/kmods.c, lib/listfuncs.c
This one was hiding in plain sight, but fortunately reported by a
kernel developer.  The code in librpminspect was correctly determining
the kernel module parameter lists differed between the before and
after build, but the reporting made no sense.  It said the module in
the after build both lost and gained the same parameter.
Digging in to it, I made the messages reported by the kmod inspection
a little more explicit.  Telling you what file the issue was found in
and what it was compared to.  The other problem was in
compare_module_parameters().  It was incorrectly computing a list of
added module parameters.  To get that list, the function should have
first intersected the list of before and after parameters, then
computed the difference between that list and the after parameter
list. …
=> [fix] Correct the reporting of kmod parameter differences

MISSING, data/generic.yaml, include/constants.h, include/types.h, lib/debug.c, lib/init.c, lib/inspect_patches.c, test/test_patches.py
The patches inspection no longer produces VERIFY results based on the
file_count_threshold and line_count_threshold settings in the config
file.  These checks were a carryover from rpminspect's ancestor, but
the core problem is that it is trying to enforce an arbitrary rule
across all packages for no good reason.  Who cares if a patch is
subjectively large if it actually fixes a problem?
The patches inspection still reports malformed patches as a BAD
result, but patch statistics are only reported at the INFO level now.
The test suite and example config file has been updated.  The
file_count_threshold and line_count_threshold settings are no longer
honored in the config file.
=> [lib] Drop the file count and line count checks in 'patches'

data/generic.yaml, lib/init.c, test/test_addedfiles.py, test/test_filesize.py
Previously the default was to report file size changes of 20% either
growing or shrinking would be reported at the VERIFY level.  The new
default is to report all changes at the INFO level.
The test cases still run with the setting in the config file at 20% to
ensure that users who want to enable the previous behavior of the
filesize inspection will get correct results.
=> [lib] Default the filesize inspection size_threshold to 'info'

lib/inspect_changedfiles.c
In the changedfiles inspection, the last attempt made is to compare
the checksums.  If they are different and it's not a rebase build,
report the change at the VERIFY level.  This doesn't makes sense, it
should be reported at the INFO level.  The critical reporting checks
are above this fallthrough, so really rpminspect should just be
reporting changes for non-rebased builds for informational purposes
only.
=> [fix] Do not report fallthrough changes as VERIFY in changedfiles

lib/init.c, lib/inspect_patches.c
The patch_ignore_list was incorrectly being reset for each entry read,
so it would be empty by the time all config files were read in.
Fixes: #683
=> [fix] Stop resetting the patch_ignore_list when reading config files

include/rpminspect.h, lib/free.c, lib/init.c, lib/peers.c
These function names were mildly annoying to me.  Renamed
init_rpmpeer() to init_peers() and free_rpmpeer() to free_peers().
=> [lib] Rename init_rpmpeer() and free_rpmpeer() functions

data/generic.yaml, include/rpminspect.h, lib/init.c, lib/paths.c
This is a large one.  First, a number of inspections were not honored
in the config file if you specified a per-inspection ignore list.
That has been fixed and all applicable inspections that can have a
per-inspection list now have one.  Some memory management fixes are
also present as well as a fix that prevents a reset of config file
settings as subsequent files are read.  Settings are now cummulative.
This may require additional work if we find it's really common for an
end user to need to override a config file block, but by and large the
most common case is appending so that's now how all settings are read
in.
The other change is with ignore path matching.  Previously all
matching was done using glob(3).  This is fine and works well, but it
does not allow a user to specify a single …
=> [fix] Honor all per-inspection ignore lists; match path prefix

lib/inspect_changelog.c
A bit of housekeeping.  The changelog inspection was littering on the
filesystem.
=> [fix] Remove temporary files in the 'changelog' inspection

include/readelf.h, lib/inspect_annocheck.c, lib/inspect_lto.c, lib/inspect_removedfiles.c, lib/readelf.c
The annocheck and lto inspections periodically have problems with
library archives.  The inspections were relying on the is_elf()
function, which returns true for any ELF type.  Modified readelf.c to
carry is_elf_file() and is_elf_archive() so that annocheck and lto are
restricted to ELF_K_ELF types and not both ELF_K_ELF and
ELF_K_ARCHIVE.
=> [lib] Restrict the annocheck and lto inspections to ELF files

lib/fileinfo.c
=> [fix] Double free removed in match_fileinfo_mode()

lib/inspect_rpmdeps.c
These show up in packages and are expected changes, so treat them like
the other expected changes.
=> [lib] Make the rpmdeps handle expected config() autodeps correctly

lib/readfile.c
Do not assume that paths given to this function are actually files.
They may be directories, devices, or really anything.  Verify the
input is both not zero length and a regular file before reading in
data.
Users cannot be trusted.
Fixes: #704
=> [fix] read_file_bytes() must be restricted to S_ISREG() files

lib/inspect_rpmdeps.c
Non-functional change.  Just adjust how the ISA substrings are trimmed
from requirement strings in RPM dependencies.
=> [lib] Adjust how the rpmdeps inspections trims ISA substrings

include/types.h, lib/deprules.c, lib/inspect_rpmdeps.c, test/test_rpmdeps_requires.py
If an explicit Requires is found that matches automatic shared library
dependencies but it happens to be new (i.e., it was not in the before
build), still just report it at the INFO level with the note that this
dependency is expected.
=> [fix] In rpmdeps, do not report new explicit Requires as VERIFY

lib/output_json.c, lib/output_summary.c, lib/output_text.c, lib/output_xunit.c, src/rpminspect.1, test/test_securitypath.py
The -s option was only working for the default text output mode.
Extend its support to the json, xunit, and summary output modes.
Fixes: #711
=> [cmd] Honor the -s/--suppress option on json, xunit, and summary modes

src/rpminspect.c
Some exit error conditions in rpminspect(1) were using errx() which is
unnecessary.  Also, one exit condition didn't actually explain what
happened so tell the user the product release was not specified and
could not be determined.
=> [cmd] Use errx() for RI_PROGRAM_ERROR conditions in rpminspect(1)

lib/inspect_addedfiles.c, test/test_securitypath.py
In the addedfiles inspection, the security path check only works if
there are two builds compared.  Otherwise rpminspect cannot determine
if a file is new or not.  The other addedfiles checks, such as
forbidden paths, work even for single build inspections.
Remove the non-applicable test cases from test_securitypath.py as
well.
=> [fix] Security path checking only applies to comparisons in addedfiles

src/rpminspect.c
When determining the product release string, do not assume
before_product and after_product could be determined.  They may still
be NULL.  This happens if you use, say, the rpminspect-centos wrapper
when comparing Fedora packages.  Without this patch, you get a
SIGSEGV.
=> [cmd] Do not assume before_product and after_product exist

include/rpminspect.h, lib/listfuncs.c
Given a string_list_t and a char *, list_remove will remove any
string_entry_t with data matching the char *.  Nothing is returned and
the string_list_t is modified in place.
=> [lib] Add list_remove() function to librpminspect

lib/listfuncs.c
Forgot to free the entry members and the entry itself.
=> [fix] Missing free() calls in the new list_remove() function

lib/rpm.c
=> Typo fix in a comment in lib/rpm.c

include/constants.h, include/results.h, include/types.h, lib/inspect_patches.c, test/test_patches.py
Expand the patches inspection to verify that all defined patches in
the RPM header are applied either with %autosetup, %autopatch, or a
corresponding %patchN macro.  If a defined patch is not found to have
a matching apply macro, it raises a VERIFY warning.
Fixes: #696
=> [lib] Expand the patches inspection to verify patches are applied

src/rpminspect.c
A followup to 21a29a221dbefa60e609f25ed9f72a092ccfe934 which fixed up
product release string detection.  I broke it for single build
analysis runs, which this patch restores functionality for.
=> [cmd] Restore product release matching for single build analysis

lib/inspect_patches.c
Fixed potential for a double free() in the patches inspection when
cleaning up the fields string_list_t.
=> [fix] Prevent double free() in the patches inspection

include/constants.h, include/rpminspect.h, lib/inspect_annocheck.c, lib/joinpath.c, lib/meson.build, lib/paths.c
The previous debuginfo path finding code relied on the common practice
of the debuginfo packages being named after their corresponding
subpackage name.  For example if you have a package named "tuna" with
subpackages "tuna-libs" and "tuna-devel" then you will probably find
debuginfo packages named "tuna-debuginfo", "tuna-libs-debuginfo", and
"tuna-devel-debuginfo" (subject to the contents of the subpackages).
The matching code simply looked for a debuginfo package name that
matched this naming style.  But that disregards any spec file that
changes where debuginfo files land.
This commit changes how librpminspect finds debuginfo subpackages by
looking for the actual file in question based on rpm's naming pattern.
My first approach was to match based on Build-ID from the ELF
metadata, but …
=> [lib] Change how debuginfo dirs are matched for files

lib/inspect_patches.c, test/test_patches.py
Some spec files may define patches like this:
Patch47:name-of-patch-file.patch
Which is fine, but rpminspect was expecting some whitespace after the
colon.  So adapt the inspection code to handle this case as well.  Add
some test cases for it too.
Fixes: #730
=> [fix] Handle PatchN: lines in spec files with no space after ':'

include/rpminspect.h, lib/strfuncs.c
Given an allocated string, strtrim() will trim leading and trailing
whitespace and then realloc() the resulting string and return a
pointer to that.  The string is modified in place.
=> [lib] Add strtrim() function to librpminspect

lib/strfuncs.c
When strsplit() tokenizes a string, exclude the empty string tokens
since those aren't really useful to callers anyway.  Or they shouldn't
be.
=> [lib] In strsplit(), skip empty string tokens

lib/strfuncs.c
strsplit() was missing a strdup() in the case of a NULL delim
parameter.  strtrim() was trying to realloc() an invalid pointer.  I
was missing a block to shift the leading stripped string back to the
's' pointer.
=> [fix] strtrim() and strsplit() memory management fixes

lib/inspect_disttag.c, lib/inspect_unicode.c
I see librpm using rpmPushMacro over rpmDefineMacro, so switching over
to that.  I am still seeing some lua lib errors when running through
valgrind, but nothing fatal.
=> [lib] Replace rpmDefineMacro usage with rpmPushMacro

lib/deprules.c, lib/inspect_rpmdeps.c
The kernel package has some additional deps that need handling by the
rpmdeps inspection.  Namely:
1) Ignore autodep rules of the form kernel(), modalias(), ksym(), and
kmod().  The kmod inspection handles what we need to check for kernel
modules.
2) Expected deprule changes may have the dependency version string end
with ".%{arch}", "+STRING", or ".%{arch}+STRING".  These cases are
checked for as well.
3) Some autodeps are names that do not map to a specific subpackage,
but are a virtual dependency and explicitly matches the package
version-release string.  In these cases the dependency change (if
there is one) is expected.
Fixes: #735
=> [fix] Handle more auto deps in the kernel package correctly

lib/inspect_metadata.c
Some INFO-only results in the metadata inspection were incorrectly
causing an rpminspect exit code of 1.
=> [fix] Make sure INFO results in metadata do not fail rpminspect

include/results.h, lib/inspect_patches.c, lib/paths.c, test/test_patches.py
I had incorrectly written this to ensure we were reading that macro from %prep, %build, %install, or %check.  But my else block match any other macro as a section and then stopped reading.  So while it found the macro, it didn't think it was in a valid section anymore.  My mistake.  This patch simplifies the spec file reading in the patches inspection.  rpminspect can't get too detailed here as spec files are difficult to parse.
This is still going to have problems with spec files that put %autopatch or %autosetup in a locally defined macro and then call that, but I guess I'll take care of that when it happens.
=> [fix] Correctly pick up the use of %autopatch or %autosetup

osdeps/slackware/post.sh, osdeps/slackware/reqs.txt, test/test_patches.py
The Slackware GHA job needed more packages in order to build clamav (it requires rust now).  Then test_patches.py needed to skip the %autopatch and %autosetup tests on systems that build rpm without liblua because lua is required for those macros.  I think this may also apply to Alpine Linux, but it at least applies to Slacwkare Linux.
=> Fix the Slackware GHA job and test_patches.py for some platforms

include/types.h, lib/builds.c, lib/peers.c, src/rpminspect.c
librpminspect computes the amount of disk space required to download
builds before performing the download.  If you don't have enough, it
errors out telling you why.  It then does the same thing before
unpacking.  This patch displays those totals in the diagnostics
results section for reference purposes.
Fixes: #682
=> [lib] In diagnostics, display download and unpack space reqs

lib/inspect_runpath.c
Technically runpath was failing any time ELF objects of types other
than ET_DYN or ET_EXEC were encountered, which was incorrect.  That
should be a no-op in the inspection and now it is.
=> [fix] Do not fail 'runpath' when comparing kernel builds

lib/inspect_changelog.c
In the changelog inspection, free before_output and after_output after
we actually use them.
=> [fix] free before_output and after_output *after* using them

include/inspect.h, lib/inspect_kmod.c, test/test_kmod.py
While working on fixing up rpminspect results for kernel package
builds, it occurred to me that the kmod inspection (which is derived
from what existed in rpminspect's ancestor) is attempting to enforce
some policies that would ensure the Kernel Module Interface remains
the same, unless it's a rebase comparison.  rpminspect's ancestor
predates the kmidiff tool:
https://sourceware.org/libabigail/manual/kmidiff.html
kmidiff is run by rpminspect as well, so the kmod inspection can be
used for reporting the changes between builds as information.  For
example, what module dependencies changed, what kernel parameters were
gained or lost, and so on.  None of those items impact the KMI, but
are of note for upgrades to the new kernel.  In general, removed
parameters are ignored when loading a …
=> [lib] Make the kmod inspection report changes as INFO only

lib/inspect_dsodeps.c
Just exit from the driver and keep on going.  It's not fatal.
=> [fix] Do not fail dsodeps if ELF type is not ET_DYN

osdeps/slackware/post.sh
Slackware Linux's json-c package does not provide a static library, so
just use the shared one.
=> [ci] Build clamav with '-D ENABLE_JSON_SHARED=ON' on Slackware

lib/inspect_addedfiles.c, test/test_addedfiles.py
In the addedfiles inspection, only report file additions in forbidden
paths at the VERIFY level.  For new files that show up when comparing
builds otherwise, just report that as INFO.
=> [fix] Only report forbidden path additions as VERIFY in addedfiles

lib/delta.c
Was missing a continue statement.  Also fix one valgrind-reported
issue.
=> [fix] Output unified diff correctly in delta_out()

include/results.h, lib/inspect_changedfiles.c
Report file reading errors at the RESULT_BAD level and
security-related path changes at the VERIFY level, but other changes
should be reported as INFO.  Regardless of the comparison being a
rebase or not.  In every instance, changes are deliberate, but we want
the warnings to catch changes to security-related paths.
=> [fix] Simplify severity reporting in the changedfiles inspection

lib/inspect_desktop.c
A followup for the desktop inspection fix from yesterday.  I added a
loop and created a temporary string for use in the loop, but neglected
to free() it.  Valgrind caught me.
=> [fix] Add missing free(tmp) calls in the desktop inspection

lib/curl.c
In the curl download progress bar callback, do not initialize the
total_width value each time.  Just do it once and then again if the
window is resized.  This keeps the progress bars aligned on the screen
and eliminates the off-by-one column behavior that periodically shows
up.
=> [fix] Minimize total_width initialization for download progress bar

lib/builds.c, lib/curl.c
rpminspect tries to determine the amount of storage space required of
all RPMs in a build before downloading it.  It does this by using
libcurl to get the download size of each package by URL.  If there's
an error, we get !CURLE_OK and the size is 0.  Report this, but don't
continue trying to download the packages.
Fixes: #770
=> [fix] Fail if we cannot read RPMs before downloading

lib/inspect_types.c, test/test_types.py
There was a bug in the types inspection that would cause it to
continually report partial results over and over making the log
impossible to read.  Also, these results are not security-focused, so
reduce to INFO reporting level.
=> [fix] Prevent repetitive results reporting in 'types'

lib/uncompress.c
In uncompress_file(), if archive_read_open_filename() returned
something other than ARCHIVE_OK, you'd get a warning on stderr and
then cleanup and NULL returned.  The program functions fine when it
can't uncompress something with libarchive, so the warning on stderr
is pointless.  Remove it.
Fixes: #775
=> [lib] Remove unnecessary archive_read_open_filename() warning

lib/output_text.c, lib/results.c
If the user specifies -s on the command to suppress results below a
certain severity level, still always output the diagnostics results
section.
Fixes: #781
=> [lib] Always output 'diagnostics' results even if -s specified

lib/init.c, src/rpminspect.c
This is a small optimization.  The optional local rpminspect.yaml was
read in from the rpminspect(1) code by calling init_rpminspect()
again.  The problem there is it runs through all the initialization
code again.  It doesn't hurt anything, but is unnecessary.  So move
the ./rpminspect.yaml read in to init_rpminspect().  In the
rpminspect(1) put one last failsafe in to try and read in a local
rpminspect.yaml file if no initialization has happened yet.
=> [lib] Move ./rpminspect.yaml reading to init_rpminspect()

data/generic.yaml
Clarify the syntax for entries in ignore blocks in the rpminspect
config files.  The ignore block, either the global one or any that go
under a specific inspection, can have entries that fit two
classifications:
* glob(7)-style syntax.  Matching is performed using fnmatch(3), so
not all aspects of glob(7) syntax apply because rpminspect is
matching against strings and not the actual filesystem.
* Path prefixes, which you get by ending the entry with a slash ('/')
Many people have already figured this out, but I wanted the default
config file template to explain it.
=> [cfg] Clarify the 'ignore' block in comments

include/constants.h, include/rpminspect.h, lib/init.c, src/rpminspect.c
This is a new thing that data packages can provide in addition to the
main configuration file and profiles.  rpminspect determines what
product release string to use for a specific job.  This string maps to
data files in the corresponding data package.  What this patch does is
adds support for the data package to deliver per-product-release
configuration profiles and have them automatically load.
These can now live in:
/usr/share/rpminspect/VENDOR/product-release/PRODUCT_RELEASE_STRING.yaml
For example.  Say Fedora wanted an fc36 configuration file in
rpminspect-data-fedora.  It could add:
/usr/share/rpminspect/fedora/product-release/fc36.yaml
If rpminspect is invoked with the fedora.yaml configuration file and
the job is for fc36 packages, it will check for the above fc36.yaml
file and …
=> [lib] Support optional product release configuration files

meson.build
Currently, meson doesn't do this by default.  Silences this warning from
meson:
WARNING: You should add the boolean check kwarg to the run_command
call.  It currently defaults to false, but it will default to true
in future releases of meson.
See-also: https://github.com/mesonbuild/meson/issues/9300
Signed-off-by: Robbie Harwood <rharwood@redhat.com>
=> [bld] check the results of meson's run_command()

lib/strfuncs.c
Allow NULL inputs to strprefix() and strsuffix().  Just return false
in these cases rather than crashing.
=> [fix] Allow NULL inputs to strprefix() and strsuffix()

lib/inspect_upstream.c, lib/paths.c
The way the upstream inspection is implemented requires special
handling of the per-inspection ignore list in rpminspect.yaml because
foreach_peer_file() is not used.
=> [fix] Get per-inspection ignore list working in 'upstream'

src/rpminspect.c
Honor POSIX extended regular expression syntax for product release
strings.
=> [lib] Use REG_EXTENDED in match_product()

data/generic.yaml, include/types.h, lib/free.c, lib/init.c, lib/inspect_badfuncs.c, test/test_badfuncs.py
Some programs and libraries deliberately use functions that have been
deemed forbidden by policy.  An example would be a library providing
runtime support for older software.  In cases like this, you can
specify an allowed block listing path globs and the specific forbidden
functions they are allowed to use.  It is adviseable to add a comment
idnicating why the forbidden function is allowed so future readers
will understand why the rpminspect.yaml file is configured that way.
The path specifications can be explicit paths (local path notation,
relative to /) or patterns that are compatible with fnmatch(3) and
glob(3).
For example:
---
badfuncs:
allowed:
/usr/sbin/somenetcmd:
- inet_aton
- gethostbyname
/usr/lib*/libsomething.so.*:
- inet_network
You can place this block in the package's …
=> [fix] Support per-file allowed lists for the badfuncs inspection

src/rpminspect.c
Because of the refactoring of how init_rpminspect() is called for
different config files, these two settings were being reset to
defaults after processing the command line options.  Move the command
line option handling to occur after all init_rpminspect() calls.
=> [cmd] Fix handling of the -s and -t command line options

test/baseclass.py
The |= syntax is only supported in Python 3.9 and later.
=> [tst] Use .update() rather than |= to merge dicts

osdeps/opensuse-leap/reqs.txt, osdeps/opensuse-tumbleweed/reqs.txt
Do not try to install yum or yum-downloadonly on opensuse-leap or
opensuse-tumbleweed.
=> [ci] opensuse does not use yum

lib/inspect_symlinks.c
In the symlinks inspection, if chdir fails the loop just continues on.
We don't need the warning here since we don't need to recover on that
particular entry.
=> [fix] Remove unnecessary warning from failed chdir() call

lib/paths.c
In data/generic.yaml, I note that for the per-inspection ignore lists
you can specify explicit paths using glob(7)-style syntax or you can
specify path prefixes to ignore everything in one subdirectory tree.
The path prefix syntax is sort of like rsync in that you specify the
path prefix with a trailing '/' and then rpminspect knows to treat it
that way.
The problem I've run in to is that everyone knows you can do
"/path/to/dir/*" on commands like cp or mv to mean everything in that
tree.  So this syntax keeps showing up in rpminspect.yaml files.
Rather than die on the hill of the original syntax I introduced, just
support the /* syntax too.  Easy.  (I don't even like the trailing /
syntax, I just didn't know what else to do.  I blame the glob(3) and
fnmatch(3) functions.)
Signed-off-by: …
=> [lib] In match_path(), honor common syntax of /path/to/dir/*

include/types.h, lib/strfuncs.c, src/rpminspect.c
Rather than calling the diagnostics results INFO as the result
severity, call them DIAGNOSTICS.
=> [lib] Define RESULT_DIAG for diagnostics results reporting

data/generic.yaml, lib/inspect_license.c
rpminspect needs the ability to have an externally-supplied licensedb
file.  And for that the program needs to honor an explicit path in the
licensedb setting in the config file.
=> [lib] Support explicit paths for licensedb in the config file

lib/strfuncs.c, osdeps/fedora-rawhide.i686/reqs.txt, osdeps/fedora-rawhide/reqs.txt, osdeps/fedora.i686/reqs.txt, osdeps/fedora/reqs.txt
Leave memory management to the caller, just modify the string in place
and shift the trimmed string to the beginning and return that pointer.
=> [lib] Remove realloc() call from strtrim()

doc/usage.rst, lib/builds.c, src/rpminspect.1
rpminspect requires a build NVR specification in order to download
packages from Koji.  In the case of scratch builds, rpminspect
requires the Koji task ID number because scratch builds do not get a
build NVR specification.  However, you cannot use a Koji task ID
number to reference a non-scratch build.  This patch changes that
behavior and allows the use of Koji task ID numbers for regular
builds.
=> [cmd] Support Koji task ID number for non-scratch builds

osdeps/opensuse-leap/post.sh
The /usr/lib/rpm/macros.d/macros.python_all file on OpenSUSE Leap sets
%vendor if you are not building Python 2 packages.  The system
otherwise allows you to define your own vendor.  With this file in
place, all packages show up as built by "SUSE LLC".
Remove any %vendor lines present in /usr/lib/rpm/macros.d/macros.*
files on OpenSUSE Leap.
=> [ci] Prevent RPMTAG_VENDOR override on OpenSUSE Leap jobs

lib/init.c
Previously librpminspect was reading in just the package name and file
path, but not the actual capabilities string.
=> [fix] Read in capabilities data files correctly

data/generic.yaml, lib/init.c, src/rpminspect.c
In addition to letting users specify the product release string on the
command line, also introduce a block in the config file where you can
do the same thing.  It would look like this:
environment:
product_release: el8
Use this in a per-package rpminspect.yaml file where rpminspect is
unable to detect the product release string from the dist tag.  Some
packages lack a dist tag.
Fixes: #819
=> [lib] Support a new config file block called 'environment'

data/generic.yaml, include/constants.h, include/rpminspect.h, include/types.h, lib/abi.c, lib/debug.c, lib/free.c, lib/init.c, lib/inspect_abidiff.c, lib/inspect_kmidiff.c
The abidiff(1) command line was incorrectly constructed.  It worked
for smaller packages where there tends to be a single debuginfo
package, but not larger builds with many subpackages.  Here's what has
changed:
* The debuginfo paths are collected and grouped per arch for the
before and after builds.
* When the abidiff command line is constructed in the abidiff
inspection, it selects the debuginfo path that is likely to contain
the debugging symbols for the file in questions.  By likely I mean
that I use a strstr() match and run with that.  There will probably
be edge cases that show up later that I will need to account for.
* Dropped all of the headers-dir handling for abidiff(1) because
that's impossible to determine.  I can only specify a single
argument to abidiff(1), but it's not …
=> [fix] Correctly build the abidiff(1) command line

include/constants.h, lib/inspect_abidiff.c
This is just simplifying things more and ensuring abidiff finds all
debugging data for its reporting.
The man page for abidiff(1) indicates multiple --d1 and --d2 arguments
can be specified, which I initially did, but they have to point
directly to the top of the debuginfo path.
=> [fix] Make sure abidiff can find all debuginfo type files

include/rpminspect.h, lib/abi.c, lib/inspect_abidiff.c, lib/inspect_kmidiff.c
Make these functions more clear that they are support functions for
use with abidiff(1) and not for the abi_t data type in the code.  I've
confused myself.
=> [lib] Rename abidiff-specific helper functions

include/constants.h, lib/abi.c, lib/inspect_abidiff.c
The previous method was not working, so modify things to pass the
correct paths to abidiff(1).  Now the inspection passes debuginfo
paths and header paths.
There may be some issues regarding private headers, but I'm not aware
of any package out there that ships private headers that are installed
on the system.  But I could be wrong.
=> [lib] Add headers dir support back to the the abidiff inspection

data/security/GENERIC
The package name in the security/PRODUCT_RELEASE files can use
wildcard glob(7) syntax.  The reason for this is that subpackages will
have different names but the same prefix (usually).
=> [cfg] Correct one small comment error in data/security/GENERIC

include/rpminspect.h, lib/abi.c, lib/inspect_abidiff.c
This function will be used by both the abidiff and kmidiff
inspections.
=> [lib] Move add_abidiff_arg() to abi.c and make non-static

lib/inspect_kmidiff.c
Use the add_abidiff_arg() function to build the kmidiff command line.
The abidiff and kmidiff inspections are similar with regards to how
the command lines are set up.
=> [fix] Use add_abidiff_arg() in the kmidiff inspection

include/types.h, lib/koji.c
There were a number of problems that had to be addressed.  The biggest
was around iterating over the structs returned in the XML-RPC
communication.  The second was the modulemd_str struct element
returned contains a very large string (usually).  If you use
xmlrpc_limit_set() when using libxmlrpc-c, which librpminspect was
doing, then you will have value reads truncated but then appended to
other strings since everything is still in the message.  libxmlrpc-c
does not consider this an error so no fault codes are registered.
What I found was that we can discontinue calling xmlrpc_limit_set()
and everything lines up fine.  I think a few years ago the situation
was different, but I have not checked older versions of the library.
Downloads of modules should work consistently now and rpminspect …
=> [fix] Get Koji module downloading working consistently

lib/builds.c
This is a side effect of the way rpminspect stores the module
information internally.  Regular Koji builds have one buildentry, but
modules have any number of them.  The download loop iterates over the
build entries and for each one displays the "Downloading..." message.
For regular Koji builds this just appears once, but for modules it
appears for each buildentry.  Modify the loop so it only displays once
for module downloads.
=> [lib] When downloading modules, only display Downloading msg once

src/rpminspect.c
Not much to say, just cleaning up valgrind findings.
=> [cmd] Small memory leak fix in rpminspect.c for the -w option

lib/rpm.c
Source packages report the rpmbuild runtime architecture when asking
for RPMTAG_NEVRA.  In rpminspect, we want to show "src" for the
architecture of source packages so handle that as a special case.
Fixes: #859
=> [fix] Handle source packages in get_nevra() (#859)

rpminspect.spec.in
Since the data package is so large, change it to a Recommends rather
than Requires.  People wanting or needing to run the virus inspection
can install the clamav-data package or manually download the data
files for libclamav.
Fixes: #856
=> [bld] Change clamav-data to Recommends in the spec file

lib/inspect_removedfiles.c
Previously only files with matching secrules in the data package would
get a reporting level other than RESULT_INFO, but we also need a
reporting severity if the waiverauth is set to WAIVABLE_BY_SECURITY.
=> [fix] Get reporting severity for removed files w/ WAIVABLE_BY_SECURITY

src/rpminspect.1
Explain how to construct local input directories for rpminspect and
how to specify single RPM and source RPM files.
Fixes: #857
=> [doc] Expand build input description in the rpminspect(1) man page

lib/koji.c
The default is 512K which has worked up until now.  xmlrpc-c uses a
size_t for this size, so just give it SIZE_MAX and let it run with
that.
Fixes: #864
=> [fix] Set XML-RPC size limit to SIZE_MAX

.github/workflows/slackware.yml
Rather than vbatts/slackware:current, use vbatts/slackware:latest which is the latest stable release.  The current branch is not always guaranteed to be working and I just noticed test failures because some of the packages were not built against the version of glibc in the tree.
=> [ci] Use vbatts/slackware:latest in GitHub Actions

lib/curl.c
Off by one for the progress bar message length.  Only noticeable on builds that have really long package names.
=> [lib] Minor fix for the download progress bar alignment

utils/gate.sh
While testing rpminspect against rpmdiff, we ran into some performance issues on the runner level. We have the kernel as a test in this list for the same reason, so I believe that adding Firefox is another valuable data point to capture when testing.
=> Add firefox into baseline testing.

include/types.h, lib/debug.c, lib/free.c, lib/init.c, lib/inspect_license.c
This is an internal library change to allow support for multiple license database files in the rpminspect configuration file.  The license inspection has been modified to work with a list of license databases.
=> [lib] Change licensdb to a string_list_t in struct rpminspect

data/generic.yaml, include/init.h, include/meson.build, lib/init.c
Support the 'licensedb' setting in the config file either indicating a single license database file or listing multiple files.
Fixes: #847
=> [lib] Support multiple license db files in the config file

lib/builds.c
If a build or task cannot be found in the configured Koji instance, rpminspect would exit -1 but there would be no error message.  This patch adds an error message on stderr when this happens so you at least have an idea of what happened.
Fixes: #877
=> [lib] Report Koji lookup error on stderr when searching

lib/inspect_subpackages.c
Similar to other inspections that succeed but have nothing to report, just add a blank "OK" message so users know it ran and succeeded.
Fixes: #879
=> [fix] When the subpackages inspection succeeds, report an OK message

test/meson.build, test/test_annocheck.py
Sorry for taking so long, however here is a proposal for adding the annocheck inspection integration test suite.
Eight integration tests are added that cover the annocheck inspection, testing following use-cases:
* Single binary RPM  (passing and failing case)
* Two binary RPMs to compare  (passing and failing case)
* A single Koji build  (passing and failing case)
* Two Koji builds to compare  (passing and failing case)
=> [tst] Add integration tests for annocheck inspection

TODO
The annocheck tests have been written, so remove that from the TODO list.
=> Update TODO file

lib/builds.c, lib/koji.c
When gathering a Koji build, stop if the build state is not BUILD_COMPLETED.  Likewise, when gathering a Koji task, stop if the task state is not TASK_CLOSED.  Any other state indicates a failed condition that either happened by itself or the user triggered.  In any of those cases, we do not want to try to fetch those artifacts.
Fixes: #881
=> [fix] Check for completed builds and closed tasks when fetching

test/test_removedfiles.py
Five integration tests are added that cover the removedfiles inspection,
testing following use-cases:
*  Two binary RPMs to compare (removed and not removed case)
* A single Security RPM  (removed case)
* Two Koji builds to compare  (removed and not removed case)
The tests check that the result and waiver_auth are as expected when a file is removed and not removed.
=> [tst] added integration test for removedfiles inspection

lib/init.c, lib/inspect_patches.c
Consistency across enums used in the library code and make some things static that were not.
=> [fix] Small enum and static variable declaration cleanups

osdeps/almalinux8/reqs.txt
The package name containing /usr/bin/annocheck changed.
=> [ci] Add annobin-annocheck to reqs.txt for almalinux8

test/test_annocheck.py
Add "-fstack-clash-protection -flto" to the needed CFLAGS in test_annocheck.py.
=> [tst] Add "-fstack-clash-protection -flto" in test_annocheck.py

test/test_annocheck.py
The annocheck inspection requires the 'annocheck' program.  If we don't have that, just skip the tests because it means a platform where annocheck is not available.
=> [tst] Skip annocheck tests if no 'annocheck' executable found

test/test_annocheck.py
The annocheck tests can still run, but additional options are required because of Slackware's toolchain.
=> [ci] Modify test_annocheck.py a bit for Slackware Linux

utils/determine-os.sh
I goofed this initially.  Also make the redhat-release section match the almalinux-release section for consistency.
=> [ci] Fix Alma Linux detection is utils/determine-os.sh

osdeps/amzn2/reqs.txt
Amazon Linux 2 is too old to run the annocheck tests at this point, so just skip them.
=> [ci] Disable annocheck tests on Amazon Linux 2

osdeps/centos7/reqs.txt
The version of gcc here is too old for the test cases we have in test_annocheck.py, so just disable them like we do for Amazon Linux 2.
=> [ci] Do not run annocheck inspection tests on CentOS 7

include/readelf.h, lib/readelf.c
Further expand readelf.c to distinguish between an ET_DYN and ET_EXEC, which is needed for some inspections.
=> [lib] Add is_elf_executable() to readelf.c

lib/inspect_upstream.c
When comparing two modules, the upstream inspection can hit a double free().  This commit eliminates that.
Fixes: #904
=> [fix] Remove free() with module input in the upstream inspection

include/rpminspect.h, include/types.h, lib/init.c, lib/inspect_changelog.c, lib/inspect_modularity.c, lib/koji.c, src/rpminspect.1, src/rpminspect.c, test/baseclass.py
Normally rpminspect autodetects the Koji build type of the inputs, but in some cases you may want to need to do that explicitly.  The -b or --build-type option on rpminspect now permits that.  The -l option displays supported Koji build types.
Also for the modularity and changelog inspections, when skipping due to the incorrect build type, leave an INFO result message explaining why.
Fixes: #798
=> Support specifying Koji build type as a command line option

lib/inspect_abidiff.c, test/test_abidiff.py
Two test cases require extra cmdline arguments on Alpine Linux.
=> Fix abidiff test cases on Alpine Linux

osdeps/slackware/post.sh
We install libabigail and annobin, so the library cache needs updating.
=> [ci] Run ldconfig as last command in post.sh on Slackware Linux

data/generic.yaml, include/constants.h, include/init.h, include/inspect.h, include/types.h, lib/free.c, lib/init.c, lib/inspect.c, lib/inspect_debuginfo.c, lib/meson.build, test/meson.build, test/test_debuginfo.py
In rpminspect's ancestor, this was called the "stripped" inspection.  It ensures built packages have debugging symbols stripped and debugdata sections linking them to the corresponding debuginfo packages.  It also ensures debuginfo packages carry debugging symbols.
=> Add the 'debuginfo' inspection and test cases

Makefile, test/baseclass.py
To retain intermediate and results files when debugging test cases, support running "make check KEEP=y" to keep those files.  Normally these are removed after each test case is run.
=> [tst] Support KEEP=y when running 'make check'

src/rpminspect.c
This is a followup to 704521fecfad00f7380a995f6e7749845badaea8.  Do the trimming after the matching rules from the config file are applied.
=> [cmd] Trim leading period(s) after product release string matching

data/generic.yaml, include/constants.h, include/init.h, include/types.h, lib/free.c, lib/init.c, lib/inspect_patches.c
The patches inspection looks for any defined Patch files that do not have a corresponding %patch macro.  It reports any missing a %patch macro as an error, unless it finds an auto patching macro.  Until this patch, that was just %autosetup or %autopatch.  But since auto patching macros can be defined at runtime in rpm macro files, move the list of auto patching macros to check for to the config file.
The config file section now adds an "automacros" list under the "patches" section.  Like this:
patches:
automacros:
- autopatch
- autosetup
- forgeautosetup
Now, when a new auto patching macro is created, only the vendor data package and rpminspect config file need to change rather than the rpminspect code.
Fixes: #921
=> [lib] Get list of %*auto* macros from the config file in 'patches'

include/constants.h, include/rpminspect.h, lib/files.c, lib/peers.c
Previously rpminspect would unpack each RPM in to its own subdirectory.  Lots of inspections need to examine the files inside an RPM, so this seemed like a reasonable way to do that.  However, some inspections need a view of the entire built package installed.  Things like abidiff want to see the debuginfo and libraries and headers. Depending on what the packager did, those files may all be in one package or multiple subpackages.  To make this easier for inspections that need to see all files extracted, rpminspect now extracts all RPMs for each build to the same root tree (technically one per architecture with src and noarch separated out).  rpminspect still has all of the RPM header information and knows what subpackage a file belongs to, so this is just an on-disk representation to make …
=> [lib] Change how RPMs are unpacked when peering happens

rpminspect.spec.in
Increase this from 1.8.2 to 2.1 in the spec file.  Newer major version so we should reset the lower bound for what rpminspect runs in Fedora, CentOS, and RHEL environments.
=> [bld] Increase libabigail version dependency to 2.1

include/types.h
These will be used for improving the reporting functions.  Allow an empty waiverauth so it does not show up in the results.  VERB_SKIP is for skipped things.  We need these defined before the other patches can come in.
=> [lib] Define VERB_SKIP and NULL_WAIVERAUTH in types.h

include/types.h, lib/output_json.c, lib/output_text.c, lib/output_xunit.c
waiverauth is technically optional.  I mean, it shouldn't even exist in the first place, but that's a discussion for another day.  In cases where an inspection is skipped or is otherwise OK, there's actually nothing to waive.  Not Waivable is not wrong, but also not correct. In these cases I just don't want it to show anything.  So modify the results reporting function to not assume waiverauth is actually set to anything.
=> [lib] Modify the result reporting functions so waiverauth is optional

include/constants.h, lib/inspect_abidiff.c
We do not need to pass --hd1 and --hd2 to abidiff as it can figure it out.
=> [lib] Drop ABI_HEADERS_DIR1 and ABI_HEADERS_DIR2

lib/inspect_removedfiles.c, test/test_removedfiles.py
These should have been reported as RESULT_BAD with WAIVABLE_BY_SECURITY, but instead they were RESULT_BAD with WAIVABLE_BY_ANYONE.
Also enable and fix the test_removedfiles.py test cases.
=> Fix unexpected removefiles findings reporting for security_path_prefix files

lib/init.c, src/rpminspect.1
Some users specify a profile as a full path to the file rather than the basename (minus the .yaml extension) in profiledir.  This is understandable considering how the -c option works.  The origin of rpminspect profiles is from early in its creation where I thought it would make sense to have profiles that describe the rpminspect rules for large categories of software.  That really didn't take off as I thought it would, but the support is still there.
This patch allows the -p option to find a profile by basename in the profiledir as well as allowing the user to specify a full path to a profile.
I have also updated the man page to explain how the options work.  In all cases, the -c option is required and rpminspect will fail if you do not provide a configuration file with the -c option. …
=> [lib] Allow profile specification by full path or basename

.mailmap, AUTHORS.md, Makefile
This is something I've been meaning to do for a while.  Add a .mailmap file to consolidate committers who have used multiple addresses over time.  Then modify the 'make authors' target to respect that so that I can just type 'make authors' to update the AUTHORS.md file.
=> Add .mailmap to consolidate contributors and update AUTHORS.md

data/generic.yaml, include/constants.h, include/init.h, include/results.h, include/types.h, lib/builds.c, lib/init.c, lib/inspect_modularity.c
Expand the modularity inspection to check the /data/static_context setting from the module metadata.  The value is collected and then checked against the configuration file setting.  Reporting is based on what is found vs. the configuration file setting.  For instance, if it is found set in modulemd.txt and the config file says static_context is forbidden, that is a VERIFY result.
Fixes: #803
=> [lib] Check /data/static_context in modulemd.txt in 'modularity'

test/baseclass.py, test/test_badfuncs.py, test/test_changelog.py, test/test_default.py, test/test_desktop.py, test/test_disttag.py, test/test_elf.py, test/test_emptyrpm.py, test/test_files.py, test/test_kmod.py, test/test_license.py, test/test_lostpayload.py, test/test_lto.py, test/test_manpage.py, test/test_metadata.py, test/test_ownership.py, test/test_pathmigration.py, test/test_runpath.py, test/test_shellsyntax.py, test/test_specname.py, test/test_symlinks.py, test/test_xml.py
This is a refactoring of TestKoji and TestCompareKoji so I can inherit from them to make module base classes.  Also, change all test cases to consistently use super().setUp() and super().tearDown().
=> Allow TestKoji and TestCompareKoji to be base classes; use super().setUp() and super.tearDown()

lib/inspect_modularity.c, test/baseclass.py, test/meson.build, test/test_modularity.py
A number of patches here.  It starts with adding base classes for module test cases, then adds test cases, then some fixes for baseclass.py debugging and some actual fixes for the modularity inspection.
=> module base classes for the test suite and modularity test cases

contrib/viewer.html
Keep it with a white background to convey emptiness. Draw a light border
around it to make the label actually visible in the legend and details.
Sort this before OK, as it's even less severe/important to look at than
that.
---
Fixes the non-styled state at https://msrb.github.io/viewer.html?url=https://msrb.github.io/results.json# . http://localhost:8000/viewer.html?url=https://msrb.github.io/results.json# looks like this now:
Of course, let the styling bikeshedding begin! :grin:
=> [cmd] Add SKIP result type to viewer

rpminspect.spec.in
Migrate the License tag over to SPDX license identifiers.
=> [bld] Use SPDX license identifiers in rpminspect.spec.in

lib/inspect_patches.c
Instead of "(null)", give the actual filename of the new patch.  It's more useful.
Fixes: #957
=> [fix] Do not report "New patch file (null) has appeared"

lib/init.c
This was unintentionally skipped, so make sure it's picked up.
=> [lib] Honor the 'ignore' block under 'abidiff' in rpminspect.yaml

include/constants.h, include/types.h, lib/debug.c, lib/diags.c, lib/free.c, lib/init.c, lib/inspect.c, lib/inspect_annocheck.c, lib/meson.build, meson.build, meson_options.txt, rpminspect.spec.in
Right now there are some target platforms that lack annobin that has libannocheck.  So for now add back in the old method of fork/exec annocheck(1) and let that be a build-time option.  Ideally libannocheck will be everywhere soon and I can remove this code [again].
=> [lib] Bring back support for annocheck(1) in the annocheck inspection

lib/paths.c
match_path() should have worked for ignore list entries that lacked a leading slash, but it turned out it didn't.  This patch gets that work for RPM and SRPM files.
=> [fix] Modify match_path() to work with paths without leading '/'

include/rpminspect.h, include/types.h, lib/builds.c, lib/fs.c, lib/humansize.c, lib/koji.c, lib/peers.c
When decomposing an XMLRPC_TYPE_INT librpminspect should use an int32_t and when decomposing an XMLRPC_TYPE_I8 librpminspect should use an int64_t.  This ensures the precision indicated in xmlrpc-c is correct given the differences in long int and long long int by platform.
For consistency, the existing XMLRPC_TYPE_INT values read by librpminspect now read in to an int32_t rather than an int.
Fixes: #966
=> [fix] Read XMLRPC_TYPE_INT and XMLRPC_TYPE_I8 correctly

lib/inspect_annocheck.c, meson_options.txt, rpminspect.spec.in
Due to some limitations in libannocheck, we need to switch back to using the executable.
=> Take rpminspect back to using /usr/bin/annocheck

osdeps/fedora-rawhide.i686/defs.mk, osdeps/fedora-rawhide/defs.mk, osdeps/fedora.i686/defs.mk, osdeps/fedora/defs.mk
We don't need the Rust stuff in the Python modules for what we are using them for, so just disable it in our CI jobs.
=> [ci] Add 'env CRYPTOGRAPHY_DONT_BUILD_RUST=1' to PIP_CMD for fedora

lib/inspect_annocheck.c
Rather than using the LIBANNOCHECK_VERSION macro, use the function so that at runtime we do not fail if the user has upgraded libannocheck to a newer version than we compiled against.
=> [fix] Use libannocheck_get_version() in libannocheck_init() call

lib/inspect_annocheck.c
Modify how the command string is created since the previous if block did not account for all possible inputs.  Lots of optionals.
Fixes: #983
=> [fix] Fix build_annocheck_cmd() in inspect_annocheck.c

data/generic.yaml, lib/inspect_license.c
What was previously happening is that rpminspect would check every license database rather than stop once it had matched every token.
=> Fix handling of license validation when multiple licensedb files are given

lib/builds.c
Inputs can be local Koji builds, local RPMs, local SRPMs, remote Koji buids, remote Koji tasks, remote RPMs, remote SRPMs...there's a lot. rpminspect will figure out where the inputs are and copy or download them to the working directory and then begin work.  In cases where an input cannot be located, gather_builds() returns -1 but it doesn't say what happened.  The most common case here is a user specifying a Koji build but Koji returns nothing.  Add a small message indicating the input could not be located.
=> [lib] When an input cannot be found anywhere, tell the user

lib/koji.c
Expand the xmlrpc fault reporting here for the initial getBuild and getTaskInfo operations.  This happens from time to time, especially if Koji returns a result where a struct member changes type.  This will hopefully make debugging in the future easier.
=> [lib] Expand xmlrpc fault reporting for getBuild and getTaskInfo

data/generic.yaml, include/constants.h, lib/init.c, lib/inspect_debuginfo.c, test/test_debuginfo.py
The logic in this inspection was half-right or half-wrong, depending on your perspective.  After going back through this and how the predecessor to rpminspect handled it, I realized I was doing the wrong thing on files in regular packages.
I refactored the inspection and updated the test cases and now things should be working as expected.
NOTE: This change does require an update to the vendor data package. Specifically the debuginfo_sections setting in the config file.
Fixes: #991
=> [fix] Correct how the debuginfo checks for missing sections

test/baseclass.py, test/test_metadata.py
This isn't perfect, but is probably sufficient for the purposes of the test suite.  In some instances the test system lacks fully configured DNS.  Instead of using socket.getfqdn(), do what librpm does which is gethostname() followed by getaddrinfo().  Go further in the test suite and if those fail, just skip the buildhost subdomain tests.
Fixes: #985
=> [tst] Handle buildhost subdomain detection more like librpm

rpminspect.spec.in
This license identifier was missing from the long list of licenses that apply to rpminspect's code base.
=> [bld] Add BSD-2-Clause to the License list in the spec file

lib/inspect_debuginfo.c
I need to do some more reading to understand what non-debuginfo ELF files should carry.  My initial understanding was that they should have .gnu_debuglink, but that does not always seem to be the case.
=> [lib] Disable the check for .gnu_debuglink in non-debuginfo

include/rpminspect.h, lib/fileinfo.c, lib/inspect_addedfiles.c, lib/inspect_capabilities.c, lib/inspect_ownership.c, lib/inspect_permissions.c, test/test_capabilities.py
Even when problems were reported by these inspections, the main driver would report "OK".  Fix up these inspections to report findings correctly.
Fixes: #1003
=> [fix] Correct results reporting for capabilities and permissions

lib/inspect_annocheck.c
Show the friendly string conversion, but also the actual code value.
=> [lib] Show error code value from libannocheck_run_tests()

include/inspect.h, include/types.h, lib/kmods.c, meson.build
OpenSUSE moved libkmod.h in to /usr/include/kmod.
=> [fix] Support systems with libkmod.h in /usr/include/kmod

include/inspect.h, include/results.h, include/types.h, lib/init.c, lib/inspect.c, lib/meson.build, meson.build, test/baseclass.py, test/test_modularity.py
This is a build time improvement for librpminspect and the test suite. If the version of librpm on the system lacks RPMTAG_MODULARITYLABEL, then do not include the modularity inspection or run any of those tests.
=> [lib] Disable the modularity inspection if librpm lacks support

lib/curl.c
I did have some preprocessor nonsense in here to handle CURLINFO_CONTENT_LENGTH_DOWNLOAD_T maybe not being there, but CURLINFO_CONTENT_LENGTH_DOWNLOAD_T and the deprecated one are part of an enum, so cpp doesn't work.  Going to try dropping the deprecated one now and see what old platform I am still trying to use and then figure out what to do.
=> [fix] Only use CURLINFO_CONTENT_LENGTH_DOWNLOAD_T in curl_get_size()

osdeps/alpine/post.sh, osdeps/alpine/reqs.txt
Some package names changed names on Alpine.  We also need to install debugedit in order to get /usr/bin/find-debuginfo.  And libabigail was not building because of the fts package changes on Alpine, so fixed that up too.
=> [ci] Fix up the Alpine Linux post.sh script and reqs.txt list

osdeps/slackware/post.sh, osdeps/slackware/reqs.txt
The big change is needing to install Rust from upstream and not use the package in Slackware.  The included package is now too old to build clamav, which we need but Slackware does not provide.
=> [ci] Fix Slackware Linux CI job

data/security/GENERIC
Commit dde6edc069 extended the security rule format to include path, increasing the number of fields from four to five.  The mention of the number of fields in the comment of the template file was missed and not updated.
=> Update secrule description comment

.github/workflows/fedora.yml, lib/curl.c, meson.build
At least on CentOS 7 and similar systems, the version of libcurl lacks CURLINFO_CONTENT_LENGTH_DOWNLOAD_T.  So add back support for that with detection in meson.build since they are part of an enum and not a macro.
=> [fix] Add back support for older libcurl versions

meson.build
Increase the warning level, change how RPMTAG_MODULARITYLABEL is checked, improve readability for other checks.
=> [bld] Some meson.build improvements

contrib/README.md, contrib/devel-rpminspect
This is a copy of the wrapper script I use when testing rpminspect locally.  I have a git clone of the rpminspect source repo where I do my work.  There's a Makefile so I can just type "make" and build the program.  Since I use meson, the build directory is set to 'build' which the wrapper script assumes.
When I need to test rpminspect against Fedora, I need it to use the rpminspect-data-fedora data, but I want it to use the git clone of that.  That's where this script can help.  I actually have copies of this script in my ~/bin directory, all edited to point to a different vendor data directory git clone.  I have one for fedora, one for centos, and one for redhat.
I can make vendor data changes to the git clone of that project at the same time I am working on rpminspect.  Sometimes a fix …
=> Add devel-rpminspect wrapper script to contrib/

meson.build
Don't treat warnings as errors in the modularity detection code.
There are unused variables (argc/argv) and thus the code fails to compile if -Wall flag is also used. For example Fedora and RHEL use the -Wall flag by default.
Signed-off-by: Michal Srb <michal@redhat.com>
=> [fix] Modularity support detection

osdeps/gentoo/post.sh, osdeps/gentoo/reqs.txt
The failure was in the debuginfo inspection.  The environment needed the dev-util/debugedit package installed.
=> [ci] Fix Gentoo Linux CI job

osdeps/alpine/post.sh, osdeps/arch/post.sh, osdeps/mageia/post.sh, osdeps/opensuse-tumbleweed/post.sh
Changing things like 'tar -xvf' to 'tar -xf' and 'git clone' to 'git clone -q'.  Just suppressing noise to make debugging failures easier.
=> [ci] Quiet some tar and git operations

.github/workflows/freebsd.yml
The default cc on FreeBSD is clang, but tell it to use gcc instead.
=> [ci] Use gcc for the FreeBSD CI job

.github/workflows/centos.yml
=> [ci] Do not run 'rpm --import /etc/pki/rpm-gpg/*' on CentOS jobs

.github/workflows/freebsd.yml, Makefile, lib/meson.build, meson.build, osdeps/freebsd/find-debuginfo.sh, osdeps/freebsd/post.sh, osdeps/freebsd/reqs.txt
Expand the meson.build file to disable the things that do not work on FreeBSD if FreeBSD is detected.  Add ca_root_nss to the list of ports to install and then that lets the pip install step run.
=> [ci] Fix the FreeBSD job

test/test_filesize.py
Like FreeBSD.  If you ask Python 3 on FreeBSD what kind of machine it's running on, it will say x86_64 but it sounds kind of like amd64. Adjust the filesize tests accordingly.
=> [tst] Handle systems that spell 'x86_64' as 'amd64'

lib/inspect_debuginfo.c, test/test_debuginfo.py
This patch fixes up the logic of the debuginfo inspection a bit.  It also handles compiled Guile object files, which all appear to exist in the wild as unstripped ELF objects.  So do not incorrectly report those as containing bad symbols.
Fixes: #1028
=> [fix] Do not incorrectly report missing debuginfo symbols

meson.build
Drop the builtin compiler args since this is a simple test to see what is in the enum.
=> [bld] Adjust the CURLINFO_CONTENT_LENGTH_DOWNLOAD_T test

include/constants.h, lib/inspect_abidiff.c
For the abidiff inspection, make sure abidiff(1) knows where the public header directories are for the before and after builds.  Use the --hd1 and --hd2 options on the command.
=> [fix] Pass public header directories to abidiff(1) for inspections

include/rpminspect.h, lib/inspect_abidiff.c, lib/pairfuncs.c
Change the way the header dir arguments are constructed to avoid generating really long command lines with duplicate directories.
=> [fix] Avoid duplicate --hd1/--hd2 args to abidiff

include/constants.h, lib/init.c
rpminspect starts by reading in a main configuration file.  That file provides the vendor data directory which is key to finding the second [optional] configuration file, the profile.  Lastly, rpminspect looks for an 'rpminspect.yaml' file in the current working directory.  Each read in overlays and modifies the configuration data already read in.
This patch extends the init_rpminspect() functionality to try reading in profile configuration files by *.yaml, *.json, and *.dson.  Any one by that name will fulfill the -p or --profile argument.  Like before, if you specify a profile and rpminspect cannot find it, the program exits with an error reported.
The functionality is further extended to support looking for a local rpminspect.yaml, rpminspect.json, or rpminspect.dson file in the …
=> [lib] Support initialization from YAML, JSON, or DSON files

README.md
New required library.  Without it, there is no DSON support.
=> [doc] Add cdson to the list of requirements in README.md

lib/parse_json.c
The json_object_object_get() function is deprecated in favor of the json_object_object_get_ex() function.
=> [fix] Use json_object_object_get_ex() in parse_json.c

lib/inspect_virus.c
`add_result_entry()` is reading non-NULL params and thus we might end up with random garbage in the final output. Virus inspection tests are currently failing on unicode decoding errors because of this.
Signed-off-by: Michal Srb <michal@redhat.com>
=> [fix] Nullify result params after they were freed

osdeps/alpine/post.sh, osdeps/amzn2/reqs.txt, osdeps/arch/post.sh, osdeps/mageia/post.sh, osdeps/opensuse-leap/post.sh
Install cdson on Alpine Linux, Amazon Linux 2, Arch Linux, Mageia Linux, and OpenSUSE Leap.  Install from git because none of these distributions offers cdson as a package.
=> [ci] Install cdson on various CI jobs

lib/curl.c
For redirects, make sure curl follows along in order to get the size of the file we're trying to download.
Fixes: #1059
=> [fix] Set CURLOPT_FOLLOWLOCATION in curl_get_size()

lib/curl.c
Pick 10 which seems more than reasonable (start the timer on when that is not reasonable).  The default is unlimited, which could result in improperly configured servers causing rpminspect to just sit and spin indefinitely if they bounce around each other.
=> [lib] Set CURLOPT_MAXREDIRS to prevent unlimited URL redirections

test/baseclass.py, test/test_virus.py
2 changes:
- virus tests are currently not recognized as tests due to the timeout decorator being used on the whole class
- decorating method instead fixes this problem
- switch to `check_results()` in `TestRPMs` as virus inspection results starts with information about the database and not actual virus scan result
=> Fix tests for virus inspection

lib/debug.c
The job definition list for the annocheck block was missing a level of indentation.
=> [lib] Adjust indentation when dumping config data

lib/parse_dson.c, lib/parse_json.c, lib/parse_yaml.c
Just some style cleanups in the lib/parse_*.c source files.  No functional changes.
=> [lib] Style cleanups and use warn*() functions from err.h

lib/debug.c, lib/parse_yaml.c
The configuration file parsing changes left this particular block unhandled.  It was reporting a malformed config file.  What is unique about this block in the YAML file is that it is dict of an array of dicts, so it's an extra sublevel.
Fixes: #1072
=> [fix] Parse the badfuncs->allowed section in YAML config files

lib/inspect_license.c, lib/local.c, lib/parse_json.c, src/rpminspect.c, test/data/licenses/test.json
This required a lot of work, which is why there are a lot of commits.  The business end of the PR is in inspect_license.c.  This preserves functionality of all existing test cases while making sure multiple license db files defined in the config file work as expected.
=> Fix handling with multiple license databases defined

src/rpminspect.c
If a user tries to compare a build of zsh with gcc, the function that determines the product release substring will crash.  Let's not do that.  The user was just confused probably.
=> [cmd] Do not crash when user tries to compare two incompatible builds

lib/inspect_virus.c
cl_cvdhead() can return NULL, in which case we want to stop the virus inspection and let the user program consider that an error.
Fixes: #1088
=> [fix] Check return value of cl_cvdhead() in virus inspection

osdeps/amzn2/post.sh
I needed this to build and install cdson and didn't pay close enough attention.  Make the ninja-build symlink early in the script.
=> [ci] Link ninja-build to ninja early in post.sh for Amazon Linux

lib/init.c, lib/parse_yaml.c
If a YAML config file is empty, rpminspect will get stuck in an infinite loop.  Make sure that doesn't happen.
Fixes: #1087
=> [fix] Do not infinite loop on an empty rpminspect.yaml file

lib/parse_yaml.c
Previously empty flow mappings in modulemd.txt files as found in flatpack modules:
buildopts:
rpms: {}
arches: [x86_64]
triggered a crash in y_free_tree():
$ /tmp/build/src/rpminspect -c /usr/share/rpminspect/redhat.yaml --debug --verbose --arches=x86_64 --keep --build-type=module --tests=modularity --format=summary firefox-flatpak-9020020230217074331.9bc4ec6c
Downloading module firefox-flatpak-9020020230217074331.9bc4ec6c
debug: curl_get_file (169): src=|https://download.devel.redhat.com/brewroot/packages/firefox/flatpak/9020020230217074331.9bc4ec6c/files/module/modulemd.txt|
dst=|/var/tmp/rpminspect/firefox-flatpak.lIwCPW/after/files/modulemd.txt|
=> modulemd.txt …
=> Initialize a dictionary on an empty flow YAML mapping

lib/init.c
With support for YAML, DSON, and JSON, look for user-specified profiles with any file ending.
Fixes: #1092
=> [fix] Look for user-specified profiles with any support file ending

lib/inspect_politics.c, osdeps/freebsd/post.sh, osdeps/freebsd/reqs.txt, test/test_debuginfo.py
The rpm4 prebuilt port is old at this point and the ports tree was updated a few weeks ago to fix the missing /usr/local/lib/rpm/elfdeps problem.  So install this port from source rather than the prebuilt package.  At some point we can probably go back to the prebuilt package.
=> [ci] Install rpm4 from source on FreeBSD CI job

lib/readelf.c
If elf_getscn() returns NULL, that's fine.  Just return NULL from this function.
Fixes: #1099
=> [fix] elf_getscn() can return NULL in get_elf_section_names()

osdeps/debian/defs.mk, osdeps/debian/pre.sh
Debian seems to have gotten a bit more picky about letting you install Python modules with pip.  Find the "push harder" command line option and run with that.
=> [ci] Fix Debian CI job and pip module installation

.github/workflows/almalinux.yml, .github/workflows/alpinelinux.yml, .github/workflows/amazonlinux.yml, .github/workflows/archlinux.yml, .github/workflows/debian.yml, .github/workflows/fedora-aarch64.yml, .github/workflows/fedora-ppc64le.yml, .github/workflows/fedora-s390x.yml, .github/workflows/fedora.yml, .github/workflows/gentoo.yml, .github/workflows/mageia.yml, .github/workflows/opensuse.yml, .github/workflows/oraclelinux.yml, .github/workflows/rockylinux.yml, .github/workflows/slackware.yml, .github/workflows/ubuntu.yml, Makefile, osdeps/fedora-rawhide.i686/defs.mk, osdeps/fedora-rawhide/defs.mk, osdeps/fedora.i686/defs.mk
These are for the CI jobs.  For the test suite, I want the CI jobs to run "make check" rather than using meson.  The reason is the Makefile target sets up the test environment and that's what I use to test things.
I have converted most workflows over to running "make debug" and "make check" in the GitHub workflow file, but I still have CentOS and FreeBSD to update.  Need to make sure these work first.
=> [ci] Add 'debug' and 'setup-debug' targets to Makefile

include/constants.h, include/results.h, include/rpminspect.h, lib/files.c, lib/inspect_annocheck.c, lib/inspect_patches.c, lib/koji.c, lib/macros.c, lib/paths.c, src/rpminspect.c
A lot in here, but it all started with fixing the annocheck inspection and it not finding the debuginfo path for i686 packages.  That began the yak shaving.
=> Handle 32-bit x86 architecture naming inconsistencies and patch file names with RPM macros

lib/inspect_virus.c
Or whatever the clamav database directory is.  If the system lacks that directory, report it in a meaningful way for the user.
Fixes: #1112
=> [lib] Improve the error reporting when missing /var/lib/clamav

lib/inspect_patches.c, test/test_patches.py
Patches can use spec file macros in their name definitions.  Support that as best as possible in the patches inspection.  Handles things like "patch-%{rpmversion}-vendor.patch"
Fixes: #1114
=> [fix] Handle patch files with spec file macros in the name

lib/inspect_changedfiles.c, lib/inspect_disttag.c, lib/inspect_elf.c, lib/inspect_javabytecode.c, lib/macros.c
The elf inspection had a file descriptor leak which, when comparing builds with many many many files, would hit the open file descriptor limit for the process.  This led to problems with a number of other inspections.  This PR addresses that whole chain of problems I found.
=> Fix leaking file descriptors which cause cascading failures through other inspections

osdeps/fedora-rawhide.i686/reqs.txt, osdeps/fedora.i686/reqs.txt
The clamav-update.i686 package does not exist anymore, so just install clamav-update.
=> [ci] clamav-update.i686 -> clamav-update on Fedora i386 jobs

lib/inspect_modularity.c
In the modularity inspection when reporting the setting for /data/static_context, do not translate the value string.  I did this originally, but I don't think it's correct because I don't think modulemd.txt files can carry translated values here.  It's either "true" or "false".
=> [fix] Do not translate the values of /data/static_context

data/generic.yaml, include/types.h, lib/debug.c, lib/init.c
Some configuration file blocks were missing from dump_cfg(), so make sure this function is complete when reporting.
=> Add missing config block reporting in dump_cfg()

lib/paths.c
This was necessary to get the per-inspection ignore list working for the upstream inspection.  If you want to list something like:
*.gem
To have the upstream inspection ignore all source files ending with '.gem', then fnmatch() must be used.  This is because of the nature of how SRPMs are unpacked.
Fixes: #1122
=> [fix] In match_path(), try an fnmatch() early

lib/inspect_capabilities.c, lib/inspect_ownership.c
I was not calling cap_free() on anything created with cap_from_text(). All I'll say is "instructions unclear".  But it seems a cap_t is a pointer and allocations are made and you need to call cap_free() when you're done.  Fine.
=> [fix] Call cap_free() on any allocations made by cap_from_text()

lib/init.c
The per-line format in the capabilities files is a little forgiving (this was inherited from rpminspect's ancestor) so we can end up with leading and trailing whitepsace.  Before using it, make sure to trim it.  Note, I can't use strcspn() here like in other places where I trim trailing whitespace because it would catch the first space after a leading '=' which is not what we want.
Fixes: #1041
=> [fix] Trim leading and trailing whitespace from capability strings

.github/workflows/freebsd.yml, Makefile, lib/debug.c, meson.build, osdeps/freebsd/post.sh, osdeps/freebsd/reqs.txt, test/test_elf.py, test/test_files.py, test/test_lto.py
Drop the requirement for gcc on FreeBSD.  This required an upstream patch to rpm:
https://github.com/rpm-software-management/rpm/pull/2459
And also modification of librpminspect, the build scripts, and some test scripts.
=> [ci] Get rpminspect building with clang on FreeBSD 13.1

data/security/GENERIC, include/rpminspect.h, include/secrules.h, lib/init.c, lib/inspect_virus.c, lib/secrule.c, test/data/security/GENERIC, test/test_virus.py
As described in #1026, this implements a 'virus' security rule type that can be SKIP, INFORM, VERIFY, or FAIL per file or path glob pattern.  This works for source and binary packages.
=> Implement the 'virus' security rule type

data/security/GENERIC, include/secrules.h, lib/inspect_unicode.c, lib/secrule.c, test/data/security/GENERIC, test/test_unicode.py
Notes in the individual commits.  This is similar to the PR that I did yesterday to add a virus security rule type.
Fixes: #996
=> Add support for the "unicode" security rule type

include/types.h, lib/free.c, lib/init.c, src/rpminspect.c
If a local rpminspect.yaml (or json or dson) file is present, add that to the DIAGNOSTICS reporting output so that users can see that rpminspect read in those settings.  The -D option dumps the effective configuration at runtime, which is the result of reading the main config file, optional profile, and optional local config file in that order.
Fixes: #925
=> [lib] Show local rpminspect config file in diagnostics output

lib/inspect_debuginfo.c, lib/inspect_unicode.c, lib/rpm.c
These are focused around forking and execing subprocesses and using librpm.
=> [fix] General memory management cleanups in librpminspect

.github/workflows/freebsd.yml, test/test_virus.py
The FreeBSD CI job on GitHub Actions is a VM in a macos guest which I think is a container in a VM itself.  The virus inspection nearly always times out, so just skip it on this platform.
=> [tst] Skip virus tests on FreeBSD

lib/init.c
Implicit definition is forbidden by C99.
=> [fix] Include libgen.h in init.c (for basename)

lib/arches.c, lib/init.c, lib/inspect_elf.c, lib/inspect_runpath.c
list_add() will initialize an empty list, so there's no need to do that before calling list_add().
=> [lib] Remove unnecessary lead up code before list_add() calls

lib/inspect_addedfiles.c, test/test_addedfiles.py, test/test_permissions.py
The fileinfo permissions checks were in both the permissions and addedfiles inspections.  We only need them in the permissions inspection.
Fixes: #1105
=> [PATCH] [fix] Drop duplicate fileinfo checks from 'addedfiles'

test/lib/test-humansize.c, test/meson.build
The TODO list mentions that one type of possible contributions are unit tests.
This PR introduces unit test for `human_size()` function.
I have purposely chosen the easiest possible C file to write unit tests to, to learn how unit tests work in rpminspect.
The test checks if conversion from bytes to human readable format is correct.
=> [tst] Add unit test for humansize.c

lib/inspect_virus.c
This just fixes a logical error that was accidentally introduced in 66b0953.
=> [fix] Load both *.cld and *.cvd virus database files, if they exist

lib/inspect_unicode.c
The unicode inspection works on SRPMs and needs to both look at the files in the SRPM itself as well as unpacked and patched source trees. Archives are unpacked to temporary directories and the code was not properly trimming this leading path so that matching against security/PRODUCT_RELEASE rules in the vendor data package would work.
Fixes: #1157
=> [fix] Handle manually unpacked source archives in unicode inspection

lib/curl.c
It is common to capture rpminspect output to log files.  In those cases, do not output curl progress bars since that makes the log files more difficult to read.
Fixes: #1162
=> [lib] Do not display curl progress bar on non-tty output

test/lib/test-arches.c, test/meson.build
The unit test in this PR in the end covers only `allowed_arch()`.
The allowed arches unit test adds one allowed arch and then checks if the added arch is indeed among allowed arches. It also checks, that a random not-allowed arch is indeed not allowed.
=> [tst] Add unit test for arches.c

include/results.h, lib/fileinfo.c, lib/inspect_ownership.c, lib/inspect_permissions.c, test/data/fileinfo/GENERIC, test/test_ownership.py
In the ownership inspection, do two new things:
* Any fileinfo rules that exist for a package are validated against what is found in the package.  Fileinfo rules do not have to be used for setuid or setgid files, so if any exist that cover non-standard owner and group info, check here.
* For setuid and setgid files, check the found owner and group against the fileinfo rule.
* I lied, there are three things.  For any setuid or setgid file, if the file lacks a fileinfo rule, report that as a security problem.  All of these types of files need a corresponding fileinfo rule.
=> Check file owner and group for setuid/setgid files in the ownership inspection

lib/inspect_unicode.c
Double the line buffer, if needed.
rpminspect started freezing in RHEL CI with the following error in logs:
"corrupted size vs. prev_size"
Doing just "sz += (i - sz);" is problematic as we would initially not increase the size of the buffer at all ("sz += 0").
=> [fix] Fix a memory bug in the unicode inspection

include/constants.h, include/inspect.h, include/results.h, lib/inspect_patches.c, test/test_patches.py
The %patchN macro has been deprecated by rpm, so many maintainers are switching to alternate syntax.  The preferred syntax is:
%patch -P N
Where N corresponds to the patch number as defined in the preamble. However, other syntax is supported.  rpminspect can now work with the following syntax:
%patchN
%patch -P N
%patch -PN
%patch N
Fixes: #1166
=> [fix] Honor additional %patch macro syntax in the patches inspection

rpminspect.spec.in
libabigail-2.3 fixes the problem where abidiff(1) runs would not finish for gcc or rust package builds.
Fixes: #987
=> [bld] rpminspect requires libabigail >= 2.3

include/constants.h, include/rpminspect.h, lib/deprules.c, lib/inspect_addedfiles.c, lib/inspect_capabilities.c, lib/inspect_config.c, lib/inspect_debuginfo.c, lib/inspect_doc.c, lib/inspect_elf.c, lib/inspect_kmidiff.c, lib/inspect_kmod.c, lib/inspect_removedfiles.c, lib/paths.c, lib/rpm.c
Previously librpminspect was checking the RPMTAG_NAME to see if it ended in -debuginfo or -debugsource.  This was done because there was not an obvious RPMTAG_* header tag to indicate if a package was a debuginfo or debugsource package.  This detection method usually works, but some packages change how the construct debuginfo or debugsource package names.
This commit adds two new functions called is_debuginfo_rpm() and is_debugsource_rpm() that inspections can use to determine if the current package is a debuginfo or debugsource package.  The check for debuginfo looks for a Provides rpmdep that says "debuginfo(build-id)" or a Provides name that contains the substring "-debuginfo".  If either condition matches, the package is considered a debuginfo package.  For debugsource detection it …
=> [fix] Improve debuginfo and debugsource package detection

test/lib/test-results.c, test/meson.build
Introduce unit tests for init_results(), add_result_entry(), add_result(), suppressed_results().
=> [tst] Add unit tests for results.c

.github/workflows/shellcheck.yml
It performs differential and full ShellCheck scans and reports results directly on GitHub.
`differential-shellcheck` Action produce reports in SARIF format. GitHub understands this format and is able to display it nicely as a PR comment, and on the `Files Changed` tab, such a defect is easier to spot and fix.
Documentation is available at [@redhat-plumbers-in-action/differential-shellcheck](https://github.com/redhat-plumbers-in-action/differential-shellcheck#readme). Let me know If you are missing some feature or setting. I'm always happy to extend functionality.
=> ci: use ShellCheck with SARIF support

lib/inspect_unicode.c, meson.build
If reallocarray() is not available, fall back on realloc().  glibc did not get reallocarray() until 2.26.
=> [bld] Check for reallocarray() and only use if available

lib/output_json.c
And then exit immediately.
json_object_to_json_string_ext() can return NULL if something goes wrong. If that happens, rpminspect would just print "(null)" and continue.
With this patch, the problem will be logged and rpminspect will exit immediately with RI_PROGRAM_ERROR status.
=> [fix] Log error if there was a problem converting JSON object to string

lib/inspect_modularity.c
In RPM 4.19, the internal representation of the rpmTagVal type has been changed from signed to unsigned.  That means, a plain check for the value of -1 (tag not found) returned from rpmTagGetValue() now produces a compiler warning.
In order to fix that, we have to either explicitly cast the literal -1 to (uint32_t)-1 or just use the RPMTAG_NOT_FOUND macro readily provided by RPM.
Choose the latter since that's the supported way, really, it's also now documented as such in the API docs for the rpmTagGetValue() function.
=> [fix] Use RPMTAG_NOT_FOUND macro instead of -1

GNUmakefile
Before we run determine-os.sh, short circuit the setting on REALPATH since we need that to get topdir.
=> [bld] Default to REALPATH=grealpath on NetBSD

osdeps/alpine/post.sh, osdeps/arch/post.sh, osdeps/centos7/post.sh, osdeps/debian-stable/post.sh, osdeps/debian-testing/post.sh, osdeps/freebsd/post.sh, osdeps/gentoo/post.sh, osdeps/mageia/post.sh, osdeps/opensuse-leap/post.sh, osdeps/opensuse-tumbleweed/post.sh, osdeps/slackware/post.sh, osdeps/ubuntu/post.sh
If mandoc.bsd.lv cannot be reached, pull source from the Debian pool. We just need roughly the latest version of mandoc sources to build from.  And surprisingly Debian has that.
=> [ci] Deal with mandoc upstream server being down

lib/inspect_xml.c, meson.build
Newer releases of libxml have deprecated initGenericErrorDefaultFunc in favor of xmlSetGenericErrorFunc, so make sure we handle building on those systems.
=> Handle initGenericErrorDefaultFunc -> xmlSetGenericErrorFunc

.github/workflows/almalinux.yml, .github/workflows/rockylinux.yml, AUTHORS.md, osdeps/amzn2/reqs.txt, test/test_patches.py
Skip the '%patch N' macro tests for systems with rpm < 4.18.  Also some other cleanups for CI control files.
=> Fix up the patches test for currently broken CI jobs

.github/workflows/fedora.yml, osdeps/fedora-rawhide.i686/defs.mk, osdeps/fedora-rawhide.i686/post.sh, osdeps/fedora-rawhide/defs.mk, osdeps/fedora-rawhide/post.sh
Our GitHub Action for Fedora rawhide builds needs to account for dnf5 presence.  Use that if we find it.  Currently the Fedora rawhide Docker images carry an unusable /etc/dnf/dnf.conf file that we have to remove to get dnf doing anything.
=> [ci] Account for dnf5 presence in Fedora rawhide

lib/builds.c
Drop the before/after notation referring to builds and just mention if it's an RPM, Koji task, or Koji build.  On failures, report the identifier and the Koji hub URL, if applicable.
Fixes: #1188
=> [lib] Rephrase the download failure messages

README.md, data/generic.json, data/generic.yaml, doc/usage.rst, include/constants.h, include/inspect.h, include/results.h, include/types.h, lib/debug.c, lib/diags.c, lib/free.c, lib/init.c, lib/inspect.c, lib/inspect_udevrules.c, lib/meson.build, rpminspect.spec.in, test/meson.build, test/test_udevrules.py
The udevrules inspection checks udev rules files syntax using "udevadm verify".  The latter is a new udevadm tool command introduced in systemd v254.
=> Introduce 'udevrules' inspection

src/rpminspect.c
This just adds one or two more results to the diagnostics section.  If only one build was given on the command line, there will be a diagnostics result that looks like this in JSON:
{
"result": "DIAGNOSTICS",
"message": "Build",
"details": "NAME-VERSION-RELEASE"
}
If there are two build specified, you will see two entries in the diagnostics section like this:
{
"result": "DIAGNOSTICS",
"message": "Before Build",
"details": "NAME-VERSION-RELEASE"
},
{
"result": "DIAGNOSTICS",
"message": "After Build",
"details": "NAME-VERSION-RELEASE"
}
Fixes: #982
=> [cmd] Add build NVRs to the diagnostics output section

lib/diags.c, lib/free.c
This came in through the udevrules PR and CI was broken because of the rawhide change with dnf5 and I just merged everything anyway, but it needed two list_free() call updates.
=> [fix] Correct two list_free() calls; missing third argument

lib/pic_bits.sh, meson.build
I'm working on packaging rpminspect for NixOS (https://github.com/NixOS/nixpkgs/compare/master...evan-goode:nixpkgs:evan-goode/rpminspect) and ran into a couple things that I had to tweak.
1. For systems that don't have /usr/, the path to elf.h should be overrideable by an environment variable. Though who know whether any of pic_bits.sh will work/be relevant on NixOS :)
2. We should add additional include directories only if they exist on the system. Nix has its own way of telling Meson the right include paths to search.
=> Portability fixes for packaging on NixOS

data/generic.yaml, include/results.h, include/types.h, lib/free.c, lib/init.c, lib/inspect_modularity.c, test/baseclass.py, test/test_modularity.py
In module package builds it is possible that Release tag values will be constructed in a specific way that embeds module-specific substrings.  This commit extends the modularity inspection to handle this if the config file contains regular expressions for the Release tag per product release.
For example, if the product release you have builds for is 'el8', then the rpminspect configuration needs to carry:
modularity:
release_regexp:
el8: \.module+el8\.[0-9]+\.[0-9]+
Or whatever the appropriate regular expression would be.  The modularity inspection will then check RPMTAG_RELEASE on modular package builds to ensure they generate a match on the regular expression.  Those that fail will be reported as having a non-conformant Release tag value.
Resolves: #801
=> [lib] In module package builds check for a Release tag value substring

lib/inspect_rpmdeps.c, test/test_command.py
=> [fix] Handle empty peers list in rpmdeps inspection

osdeps/alpine/post.sh, osdeps/arch/defs.mk, osdeps/arch/post.sh, osdeps/debian-stable/post.sh, osdeps/debian-testing/post.sh, osdeps/slackware/post.sh, osdeps/ubuntu/post.sh
Non-Fedora derived systems probably lack a %dist tag defined for rpmbuild, so simulate one via ~/.rpmmacros for the purposes of running the test suite.  This PR should fix all but the Gentoo Linux CI jobs.  Gentoo is failing for another reason right now and it appears to be their own emerge dependency stuff.
=> CI job fixes for recent modularity inspection update

include/constants.h
Small change when identifying debuginfo and debugsource packages.  The substring should begin and end with hyphens, otherwise we will pick up elfutils-debuginfod-client as a debuginfo package and that's incorrect.
Fixes: #1209
=> [fix] Adjust DEBUGINFO_SUFFIX and DEBUGSOURCE_SUFFIX

include/constants.h, lib/deprules.c, lib/rpm.c
Commit 6eb60aa8332c4d8a9d02f885df26d112f7beb5e5 was almost correct. Still check these as suffixes, but change it over to strsuffix() rather than strstr().
=> [fix] Check for debuginfo and debugsource package name suffixes

include/rpminspect.h, lib/init.c, lib/inspect_abidiff.c, lib/inspect_annocheck.c, lib/inspect_javabytecode.c, lib/inspect_kmidiff.c, lib/inspect_patches.c, lib/runcmd.c, osdeps/fedora-rawhide.i686/post.sh, osdeps/fedora-rawhide/post.sh
This is a portability change.  I have run in to some systems that have execvp() but not execvpe().  That's easy enough to deal with, so don't assume we have execvpe().
=> [lib] Use execvp() rather than execvpe() in run_cmd()

TODO, lib/diags.c
Some commands are optional, so if they error out trying to get information just skip listing them in the diagnostics output.
=> [lib] Ignore missing optional commands in gather_diags()

include/rpminspect.h, lib/files.c, lib/inspect_capabilities.c, lib/inspect_ownership.c, lib/rpm.c
I was doing this for the owner and group, but not the modes.  I was just lifting that from the cpio stream.  But RPM keeps the file modes in the RPM header under the RPMTAG_FILEMODES array.  So read those and use that value for st.st_mode in extract_rpm().
Fixes: #1219
=> Get file modes from the RPM header and not the cpio stream

lib/inspect_rpmdeps.c
When checking for explicit named Requires in packages when an autogenerated shared library dependency was found, skip debuginfo and debugsource packages since those are all automated anyway.  We only care about the explicit named Requires for the regular packages.
Fixes: #1208
=> [fix] Skip debuginfo and debugsource packages for explicit deps

include/parser.h, lib/init.c, lib/parse_dson.c, lib/parse_json.c, lib/parse_yaml.c
Add a .havesection function to the config file parsers and extend read_cfgfile() to know if it is reading a system-wide config file or a user config file.
Fixes: #1150
=> Ignore 'unicode' config file section from user config files and display a warning

lib/parse_json.c
This was a temporary thing that I did not mean to commit.
=> [lib] Drop debugging warnx() from json_parse_file()

lib/inspect_runpath.c
There was one result finding in the runpath inspection that was not setting the header field.  That led to a SIGSEGV in add_result_entry().
Fixes: #1239
=> [fix] Set missing result params header in the runpath inspection

lib/builds.c, lib/koji.c
wrapperRPM build types are new to me, but one was reported and after digging in to the specifics it looked like something rpminspect can support.  From what I can see, a wrapperRPM build is a build submitted to Koji where the source is a git repo URL (like with a commit ID or tag).  The git repo contains a spec file and the other content for the RPM and Koji will construct the SRPM and do the mock build from that. The example I was given is for a qcow2 image in an RPM.  I don't know what we're using these for, but it's an RPM and rpminspect can read those.  The trick was extending the Koji XML-RPC communication in librpminspect to handle wrapperRPM builds.
Fixes: #1241
=> [lib] Add support for 'wrapperRPM' builds in Koji

include/rpminspect.h, lib/results.c
This is something I can use to look at a specific result where there are bug reports in the reporting functions.
=> [lib] Add debug_print_result() to librpminspect for results debugging

lib/inspect_shellsyntax.c
Some of these were too generic or copied from another result type. Make these more specific so you know what you're looking at in the results.  These are only for the 'summary' output format.
=> [fix] Improve the shellsyntax noun/verb result messages

lib/inspect_rpmdeps.c
I had this in place but lost it in the refactoring.
=> [fix] Skip peers missing an after build in rpmdeps

lib/runcmd.c
Move the find_cmd() call in to the child process so we don't leak in the parent.
=> [fix] Memory leak fix in run_cmd_vp()

rpminspect.spec.in
The %autorelease macro has moved in Fedora 39+ and rpminspect is failing the %{dist} check as a result. Use the generic form of the Provides instead of depending on the package name.
See also https://src.fedoraproject.org/rpms/rpminspect/pull-request/2
=> Use rpm_macro(autorelease) for Recommends

include/constants.h, lib/inspect_disttag.c
This is now a thing that is allowed in Release tags in spec files, so look for it and if we find it, be ok with it.
Fixes: #1258
=> [fix] Allow %autorelease as the value in a Release tag

data/generic.yaml, include/init.h, include/types.h, lib/debug.c, lib/free.c, lib/init.c, lib/inspect_desktop.c
Allow the desktop configuration block to allow users to list paths to .desktop files to skip either the Exec= check or Icon= check.  This allows the desktop inspection to still run desktop-file-validate but skip the Exec and Icon checks when the subpackages do not carry either the application or icon file.
=> [lib] Expand the desktop inspection with more configuration opts

lib/files.c, lib/inspect_filesize.c
When extracting the RPM payload, hard links will have a zero length but a link count > 1.  In the filesize inspection, the size of hard links is incorrectly read as 0.  In the case of hard links, stat(2) the file to pick up the actual size and store that in the rpmfile_entry_t for use in other inspections.  Only give it one try as the actual extracted file may also be zero length.
Fixes: #1252
=> [fix] Read and cache the st_size for hard links

data/generic.dson, data/generic.json, data/generic.yaml
These were the __pycache__, *.pyc, and *.pyo globs.  But now the block is empty in the example config files.
=> [cfg] Drop entries from the example global ignore list

utils/git-hooks/pre-push
This script runs flake8, black, and shellcheck before pushing changes. I rely on this because once I push, I will make a PR for the main project and that's going to run flake8, black, and shellcheck anyway. I want to make sure I have not introduced any problems.
To use this script, copy it to your ~/.git/hooks subdirectory.
=> Add the pre-push git hook I use before pushing changes

include/rpminspect.h, lib/inspect_patches.c
The reporting in the patches inspection notes how many file(s) and/or line(s) a particular patch touches.  Handle the plural form of the result strings with the ngettext() function so that other languages can be translated correctly.
Fixes: #1268
=> Use N_() for result strings in the patches inspection

osdeps/freebsd/defs.mk, osdeps/freebsd/post.sh, osdeps/freebsd/pre.sh, osdeps/freebsd/reqs.txt, test/test_capabilities.py
FreeBSD CI job needed some updates.
There were some tests in test_capabilities.py that were not guarded by the skipUnless check to see that rpm has %caps support.
=> FreeBSD CI fixes and skip test_capabilities tests if rpm lacks %caps

.github/workflows/centos.yml, osdeps/centos7/post.sh, osdeps/centos7/reqs.txt
Needed some more build dependencies for installation of Python modules.  And the python3-rpm rebuild stopped working, so simplify that so we get it installed in the test environment against a more recent Python.
=> [ci] Small fixes for the CentOS 7 job

utils/gate.sh
I mean, it _might_ be another architecture.  Maybe sparc64, maybe alpha, maybe m68k....perhaps ia64?
=> [bld] Don't assume x86_64 in utils/gate.sh

osdeps/centos7/post.sh
The CentOS 7 job installs a newer Python in to /usr/local.  That's now 3.12, which has removed distutils.  Since the python3-rpm package on CentOS 7 uses rpm-4.11, the Python bindings have "from distutils.core" in the setup.py, we need to patch that so it builds with Python 3.12.
=> [ci] Can't use distutils with Python 3.12 on CentOS 7

lib/output_summary.c
The 'summary' output format is deprecated and will be removed in a future release.  I never really finished this output mode and no one seems to care, so I am going to remove it.
=> [lib] Note the summary output mode is now deprecated

include/constants.h, meson.build, meson_options.txt, src/rpminspect.c
Previously the vendor data directory and the working directory were hardcoded and defined in the constants.h file.  The vendor data directory was set to /usr/share/rpminspect and the working directory was set to /var/tmp/rpminspect.  Those are still the defaults, but allow those locations to change at build time.
=> [bld] Allow vendor data dir and work dir to be set at build time

lib/strfuncs.c
In some cases the strtrim() function would not clear out characters as it shifted everything to the left.
=> [fix] Fix a small error in the strtrim() function

lib/inspect_subpackages.c
If a subset of architectures including "src" was passed to rpminspect (e.g. -a x86_64,noarch,src), a subpackages test would fail if the source packages were built on different architectures (e.g. aarch64 and x86_64):
Skipping specname inspection...      skip
Running subpackages inspection...    FAIL
Skipping symlinks inspection...      skip
The cause is that a source RPM package quotes an architecture where it was built in RPMTAG_ARCH tag, while rpminspect expected "src".
This patch fixes it by special-casing source packages.
In addition, if the source package was built on an unnamed (-a) architecture, the test logic reported an error without any details. This patch does not address this underreporting issue. A possible approach is moving "result = false" assignements into the …
=> [fix] Recognize source RPM packages in subpackages test

include/rpminspect.h, lib/array.c, lib/init.c, lib/inspect_license.c, lib/listfuncs.c, lib/meson.build, lib/parse_dson.c, lib/parse_json.c, lib/parse_yaml.c, meson_options.txt, test/data/licenses/test.json, test/test_annocheck.py, test/test_license.py
The fedora-license-data project wants to change the JSON data format:
https://gitlab.com/fedora/legal/fedora-license-data/-/issues/387
The format of the config file is effectively an API.  There's no versioning and there's no way to tell what config file format you are looking at.  I personally view this as an inappropriate change.  However, I don't control fedora-license-data and that was the whole point of getting that project going.
This massive patch set splits out some JSON handling from init.c in public API so it can be used by the license inspection.  I have modified the license inspection to try reading license db blocks in the new format first and if that fails, fall back on the old format.  Without any versioning information obtainable from the config file, there does not appear …
=> Support new license DB format in the license inspection

lib/inspect_arch.c
If a subset of architectures including "src" was passed to rpminspect (e.g. -a x86_64,noarch,src), an arch test would fail if the source packages were built on different architectures (e.g. aarch64 and x86_64):
Skipping annocheck inspection...     skip
Running arch inspection...           FAIL
Skipping badfuncs inspection...      skip
The cause is that a source RPM package quotes an architecture where it was built in RPMTAG_ARCH tag, while rpminspect expected "src".
This patch fixes it by using get_rpm_header_arch() which handles source packages correctly. This is similar to
79cbb84f3bd60889dbcf4ddfc7d1d2a714cf5442 commit.
<https://centos.softwarefactory-project.io/zuul/t/centos/build/be28da8c6aa7440780e5dc8cf5d36b67>
=> [fix] Recognize source RPM packages in arch test

lib/inspect_license.c
Some allowed categories are more finegrained, so the license needs to account for this in the license database.
=> [fix] Make sure the license check honors "allowed-*" licenses

lib/inspect_license.c, lib/inspect_udevrules.c, test/data/licenses/test.json, test/test_license.py
The license database can carry an optional list of source package names that are exceptions to licenses marked as "not-allowed".  This patch checks to see if a not-allowed license is present in a package listed in packages_with_exceptions and considers that passing.
Fixes: #1286
=> [lib] Honor packages_with_exceptions in the license database file

lib/inspect_license.c, lib/listfuncs.c
Can't iterate over a tailq if you free the current entry.  Change how list_trim() works.  Also plug some memory leaks in lib_cb().
=> Fix segfault in license inspection and close memory leaks

lib/init.c
=> [fix] Close small memory leak in the secrule reading code

.github/workflows/fedora.yml, include/compat/meson.build, include/constants.h, include/init.h, include/inspect.h, include/internal/callbacks.h, include/internal/tyranny.h, include/meson.build, include/output.h, include/parser.h, include/queue.h, include/readelf.h, include/results.h, include/rpminspect.h, include/secrules.h, include/types.h, lib/deprules.c, lib/init.c, lib/inspect_license.c, lib/inspect_rpmdeps.c, lib/parse_yaml.c, meson.build, test/lib/test-cpp.cpp, test/lib/test-main.h, test/meson.build
These changes should make it possible to have a C++ project link with librpminspect and work.  I went ahead and added the extern C stuff to the public librpminspect headers.  I split the internal-only headers out in to a subdirectory.  And I also added a simple test case that builds a C++ program linking with librpminspect so we can see if any changes down the road break things.
=> Modify headers to work with C++ projects; add C++ test case

lib/inspect_symlinks.c, lib/rpm.c, test/test_symlinks.py
The symlinks inspection was only checking the current subpackage for relative symlink resolution, but packages are allowed to have relative symlinks to other subpackages.  This patch fixes the symlinks inspection to correctly handle that case and report at the correct level (INFO, VERIFY, BAD).
Fixes: #1295
=> Correctly resolve relative symlinks across subpackages

lib/inspect_rpmdeps.c, test/test_rpmdeps_requires.py
A package with automatic shared library dependencies usually require an explicit Requires on the %{name} = %{version}-%{release}.  This is done to ensure subpackages don't drift from the main package when performing upgrades.  However, it is also possible to have those explicit Requires handled by transitive Requires.  That is having an explicit Requires on a package that then itself has an explicit Requires on the package you need.  This commit implements that check when looking for explicit Requires and treats it as satisifed.
Fixes: #1231
=> [fix] In the symlinks inspection, honor transitive Requires

meson.build, osdeps/alpine/pip.txt, osdeps/alpine/post.sh, osdeps/alpine/reqs.txt
The debuginfo and unicode test cases were failing on Alpine Linux. This patch gets those working again.
=> [ci] Fix CI test cases on Alpine Linux

osdeps/alpine/defs.mk
pip continues to be more and more difficult to use with a system that has packaged software.
=> [ci] Add '--break-system-packages' to PIP_CMD on Alpine Linux

lib/inspect_udevrules.c
The udevrules inspection was always failing for me because of the way I was checking for the presence of a working udevadm command with the 'verify' operation.  Simplify this and get it working again.
=> [fix] Correctly check for a working 'udevadm' command in udevrules

rpminspect.spec.in
Specify the package name rather than the executable for the dependency.  Path dependencies do not work with DNF 5/
=> [bld] (Requires|Recommends): /usr/bin/annocheck -> annobin-annocheck

test/test_symlinks.py
We get ENOENT, which happens for allowed dangling symlinks so rpminspect ends up reporting the too many case as INFO rather than BAD.  Looking at the system, it appears to work so maybe reporting it as INFO is sufficient.  It reports as dangling at least.
=> [ci] OpenSUSE Leap does not give ELOOP on the too many symlinks check

lib/rpm.c
On some systems this function would return false when looking at a debuginfo package that meets the criteria.
=> [lib] Adjust _is_debug_rpm_helper() for other distributions

test/test_symlinks.py
More systems that have a modern enough RPM that we don't need to check these conditions.
=> [tst] Exclude Oracle Linux and AlmaLinux from the symlinks ELOOP tests

lib/joinpath.c
=> [lib] Remove unused 'extralen' variable in joinpath.c

lib/files.c, lib/inspect_removedfiles.c
In some cases there are version-release substrings in paths that do not contain the dist tag.  What rpminspect does when finding before and after build file peers is it tries to substitute out the RPMTAG_VERSION and RPMTAG-RELEASE as those are commonly used in doc paths or other shared data paths.  Some packages trim the RPMTAG_RELEASE to not include the dist tag.  This is observed on the kernel package appearing in Fedora and other distributions.
I have expanded the file peering code to try and handle this somewhat corner case of version-release substitution so that peering works.  It is working now for at least the builds where I have observed the problem.  No existing peering functionality was affected.
Fixes: #1319
=> [fix] Expand file peering code to support VER-REL without dist tag

lib/inspect_unicode.c, lib/magic.c
Yeah, this can happen.  Add more checks for NULL.
Fixes: #1329
=> [fix] Prevent a SIGSEGV in the unicode inspection

.github/workflows/fedora-ppc64le.yml, .github/workflows/fedora-s390x.yml
The [version v2.7.1][v2.7.1] of uraimo/run-on-arch-action removed Dockerfiles for Fedora's s390x and ppc64le architecture (see https://github.com/uraimo/run-on-arch-action/commit/18a5cd7958b1f33f6a8f10b48fdbcbf02ccda003). Other Dockerfiles were removed, then readded (Fedora wasn't for some reason), but they will not be part of next v3.0.0.
So, either pin specific version for the action or remove these workflow files. This PR's commit proposes to pin the version.
See my test workflow runs: [fedora-ppc64le.yml][ppc64le] and [fedora-s390x.yml][s390x]
[v2.7.1]: https://github.com/uraimo/run-on-arch-action/commits/v2.7.1
[ppc64le]: https://github.com/rffontenelle/rpminspect/actions/runs/7704873344/job/20997913888
[s390x]: https://github.com/rffontenelle/rpminspect/actions/runs/7704872976
=> Pin version of run-on-arch action for some fedora arches

include/results.h, lib/inspect_license.c, po/rpminspect.pot, test/test_license.py
SPDX license names can be case-insensitive, but the boolean terms must be uppercase (thanks, spec!).  Ensure the license inspection honors this.
Fixes: #1335
=> [fix] Honor case-insensitive SPDX names

lib/inspect_elf.c
This just terminates the function earlier.  The rest of the function requires the presence of after_execstack so since we don't have that, just go ahead and return.
=> [lib] End execstack testing early if there is no after_execstack

osdeps/almalinux8/post.sh, osdeps/almalinux9/post.sh, osdeps/alpine/post.sh, osdeps/amzn2/post.sh, osdeps/centos7/post.sh, osdeps/centos8/post.sh, osdeps/centos9/post.sh, osdeps/debian-stable/post.sh, osdeps/debian-testing/post.sh, osdeps/freebsd/post.sh, osdeps/mageia/post.sh, osdeps/opensuse-leap/post.sh, osdeps/opensuse-tumbleweed/post.sh, osdeps/oraclelinux8/post.sh, osdeps/ubuntu/post.sh
I'm wondering if this is the ideal libtoml library to use.  Other distributions have libtoml++ and I think I saw another one out there. This one has no releases tagged, so I might bundle it like I do with libxdiff but if the system provides libtoml, let it use that.
=> [ci] libtoml lacks a 'make install' target; install manually

meson.build
The default is C90, but that won't work here.
=> [bld] Set c_std='gnu99' so toml_parse.c will compile

lib/init.c
=> [fix] Do not crash if a user-provided config file is empty

.github/workflows/freebsd.yml, meson.build
FreeBSD builds using clang and with the addition of libtoml we are using C11 rather than C99.
=> [ci] Fix failing FreeBSD CI job

data/generic.yaml
libpython3.so doesn't contain any compiled code
and it's there to point applications to the versioned libpython library where the compiled code is. Hence we cannot strip debug symbols from there.
See also: https://bugzilla.redhat.com/show_bug.cgi?id=2144553#c16
Cherry-picked from https://github.com/rpminspect/rpminspect-data-fedora/commit/fb53cacddcc8f72ee475b5e83b8d41851cbd7c85
This does not only affect Fedora.
=> Exclude libpython3.so from the debuginfo tests

data/generic.dson, data/generic.json
Apply the change in 172d0b30efbde3984a27ba39557c43ca39fcf560 to generic.dson and generic.json.
=> [cfg] Exclude libpython3.so from the debuginfo tests

rpminspect.spec.in
This BR is no longer needed as the libtoml source code has been added to the repository in 6577ec61.
This should fix the FTBFS problem for EPEL buildroots in COPR.
=> [fix] Drop libtoml-devel BR from the spec file

lib/remedy.c
The remedies array needed an entry for REMEDY_NULL.
Fixes: #1360
=> [fix] Pick the correct remedy string when displaying findings

include/readelf.h, include/types.h, lib/files.c, lib/inspect_abidiff.c, lib/inspect_annocheck.c, lib/inspect_badfuncs.c, lib/inspect_changedfiles.c, lib/inspect_debuginfo.c, lib/inspect_dsodeps.c, lib/inspect_elf.c, lib/inspect_kmidiff.c, lib/inspect_lto.c, lib/inspect_removedfiles.c, lib/inspect_runpath.c, lib/readelf.c
Add four flag fields to rpmfile_entry_t struct to save the information such as "is it an ELF archive?"
"is it ELF file?" and if yes, is it executable, or shared lib. (the fields are "signed char" to keep the struct compact, we have 100 thousands of those when running on kernel packages).
get_elf() attempts to open the file only if
"is it ELF file?" flag is "don't know".
It sets the flag to yes/no.
Future get_elf()'s on file which is known to not be an ELF immediately return NULL with no file operations attempted.
get_elf_archive() does the same with "is it an ELF archive?" flag.
This is the key speedup. It stops us from opening files and testing them for ELFness some 100+ million times for kernel packages.
is_elf_file() uses get_elf()'s cached result if it is present (therefore does not …
=> Cache the result of "is it an ELF file?" checks

include/helpers.h, include/meson.build, include/rpminspect.h, libtoml/toml.c, libtoml/toml.h, libtoml/toml_private.c
Compiler complains about the return value of `asprintf()` being ignored, and -Werror flag causes the build to fail because of that.
`xasprintf()` makes this warning to go away.
However, `xasprintf()` was previously defined in `include/rpminspect.h`, and there were conflicts between this header file and `ccan/list/list.h`. Therefore I moved the `xasprintf()` definition to a separate header file -- `include/helpers.h`. See the commit message for more details.
=> [fix] Replace asprintf() with xasprintf() in libtoml source code

libtoml/toml.h, meson.build
I was incorrectly using 'inc' twice.  That refers to the include/ directory here, but I was using it first for system includes.  So rename the latter to sysinc for various checks in meson.build.
I did this to fix the #include problem with libtoml/toml.h, which should not use relative includes.  It should just name the file and let it get picked up via the -I search paths.
=> [bld] Fix the include subdirectories variables in meson.build

.github/workflows/oraclelinux.yml, osdeps/alpine/post.sh, osdeps/arch/post.sh, osdeps/centos7/post.sh, osdeps/debian-stable/post.sh, osdeps/debian-testing/post.sh, osdeps/fedora-rawhide.i686/post.sh, osdeps/fedora-rawhide/post.sh, osdeps/fedora.i686/post.sh, osdeps/fedora/post.sh, osdeps/freebsd/post.sh, osdeps/gentoo/post.sh, osdeps/mageia/post.sh, osdeps/opensuse-leap/post.sh, osdeps/opensuse-tumbleweed/post.sh, osdeps/oraclelinux8/defs.mk, osdeps/oraclelinux8/pip.txt, osdeps/oraclelinux8/post.sh, osdeps/oraclelinux8/pre.sh, osdeps/oraclelinux8/reqs.txt, osdeps/oraclelinux9/defs.mk, osdeps/oraclelinux9/post.sh, osdeps/ubuntu/post.sh, regress/all-inspections-kernel.sh, regress/indiv-inspections-kernel.sh, utils/determine-os.sh, utils/find-ninja.sh, utils/gate.sh, utils/mkannounce.sh, utils/submit-koji-builds.sh
Also do a bit of shell script cleanup work.  For CentOS 7, had to adjust the way pip modules were installed and then python-rpm was rebuilt.  For Oracle, we're using 2 different versions of Python 3, but that's ok.
=> [ci] Fix up failing CentOS 7 and Oracle Linux CI jobs

osdeps/oraclelinux8/reqs.txt
This package does not exist on Oracle Linux 8.  It was already listed in pip.txt, but I forgot to remove it from reqs.txt.
=> [ci] Remove python3.11-timeout-decorator from OEL8 reqs.txt

data/generic.yaml
Entries in a list (prefixed with '-') that use glob(7) characters need to wrap themselves in single quotes.
=> [cfg] Note entries with file globbing need single quotes

lib/unpack.c
With some versions of libarchive, it is possible to receive ARCHIVE_FATAL from archive_read_next_header() in a loop where you are unpacking an archive.  From all of my testing, it appears to be data at the end of the stream that libarchive is unable to handle.  Since you can't recover from ARCHIVE_FATAL, just break out of the loop and close everything down.  In the example I have been using to test this locally, I have found that on the problematic version of libarchive and a working version of libarchive, this patch causes all files to be correctly extracted.
The only place where I have seen ARCHIVE_FATAL returned by archive_read_next_header() are on RHEL UBI9 containers with libarchive-3.5.3.  Regular RHEL-9 installs, recent Fedora releases, and regular CentOS Stream installs all work …
=> [fix] Stop unpacking archive when we receive ARCHIVE_FATAL

meson.build
Builds on systems with older versions of libcurl were failing.  I was using the check incorrectly.  All I needed to do was just test to see that source compiles with a defined macro so I have changed it to that.
=> [bld] Correct the check for CURLINFO_CONTENT_LENGTH_DOWNLOAD_T

lib/flags.c
There were already protections in place for individual file paths and inspections named on the command line, but this picks up local config files that have disabled an inspection with security checks in it.
Fixes: #1374
=> [fix] Do not allow skipping of security checks via config file

lib/permissions.c
params.msg may be NULL, which is fine.  Default to file->localpath if it's NULL for reporting purposes.
Fixes: #1381
=> [fix] Handle params.msg == NULL in permissions inspection

test/test_disttag.py, test/test_patches.py
Use packaging.version's parse() and Version() instead.
=> [tst] LooseVersion from distutils.version is deprecated; replace it

data/remedy/generic.toml, include/remedy.h, lib/inspect_license.c, lib/remedy.c, po/POTFILES, po/rpminspect.pot, test/test_license.py
Some legacy license abbreviations match SPDX abbreviations.  In these cases, do not assume the license expression is SPDX unless the other tokens are SPDX tokens.  This happens in a handful of cases with license abbreviations like "Zlib" or "MIT" and maybe a few others.
Fixes: #1378
=> [fix] Properly handle license abbrevs that match SPDX and legacy

test/test_disttag.py, test/test_patches.py
I was using LooseVersion from distutils, but that's deprecated in more recent releases.  Since the CI jobs run on a variety, still handle cases where we should still use LooseVersion.
=> [tst] Handle older Python 3.x releases without 'packaging' module

.github/workflows/ubi.yml
I think this was messing up the various dnf commands I run to get the environment set up in the CI job.
=> [ci] Fix the RHEL UBI9 job; drop 'cost' from c9s repo definitions

lib/init.c, lib/inspect_license.c, test/data/licenses/test.json, test/test_license.py
The license inspection was incorrectly handling license identifiers that appear as both legacy identifiers in the license database as well as SPDX expressions.  The core problem is that under the legacy system, there was a lot of identifier reuse.  This patch refactors how the license inspection notes the dual licenses so that the inspection passes on packages that have migrated to SPDX.
Fixes: #1387
=> [fix] Correctly handle dual SPDX/legacy license identifiers

lib/inspect_annocheck.c
If debuginfod is running and the environment where rpminspect runs has DEBUGINFOD_URLS set, then it will start trying to download debuginfo RPMs when you get to the annocheck inspection.
Fixes: #1399
=> [fix] Unset DEBUGINFOD_URLS to prevent downloading debuginfo rpms

include/meson.build, include/parallel.h, include/rpminspect.h, lib/inspect_virus.c, lib/io.c, lib/meson.build, lib/parallel.c, src/rpminspect.c
On a 8-thread CPU (Intel Tigerlake laptop), in test run a-la
rpminspect -c /usr/share/rpminspect/fedora.yaml -p rawhide
-Dv -k -t VERIFY -a x86_64,noarch,src -T virus kernel-6.8.10-200.fc39
this cuts "virus inspection" run time from 19 to 8 minutes.
On a larger machine the benefits should be proportionately larger.
=> Run clamav virus check on all CPUs, not on just one

include/types.h, lib/checksums.c, lib/fileinfo.c, lib/files.c, lib/inspect_abidiff.c, lib/inspect_addedfiles.c, lib/inspect_badfuncs.c, lib/inspect_changedfiles.c, lib/inspect_config.c, lib/inspect_desktop.c, lib/inspect_doc.c, lib/inspect_dsodeps.c, lib/inspect_elf.c, lib/inspect_filesize.c, lib/inspect_kmidiff.c, lib/inspect_kmod.c, lib/inspect_lto.c, lib/inspect_manpage.c, lib/inspect_patches.c, lib/inspect_politics.c, lib/inspect_removedfiles.c, lib/inspect_runpath.c, lib/inspect_symlinks.c, lib/inspect_types.c, lib/inspect_udevrules.c, lib/inspect_virus.c, lib/inspect_xml.c, lib/ownership.c, lib/permissions.c
On x86_64, struct stat st is 128 bytes, but we use ony three fields in it. Replacing it with
off_t st_size;
mode_t st_mode;
unsigned st_nlink;
in rpmfile_entry_t reduces the latter from 240 bytes to 112 bytes.
In test run a-la
rpminspect -c /usr/share/rpminspect/fedora.yaml -p rawhide
-Dv -k -t VERIFY -a x86_64,noarch,src -T virus kernel-6.8.10-200.fc39
after rpm unpacking memory consupmtion of the process fell from ~130 to ~100 megabytes.
=> [lib] reduce struct size of rpmfile_entry_t

test/test_patches.py
The latest releases of rpm are now erroring out on the older syntax. The now preferred syntax of '%patch -P N' has actually been supported forever, so this is safe to use on older releases too.  Update the test suite to use this syntax.
=> [tst] Use newer %patch syntax in test_patches.py

.github/workflows/ubi.yml
Without this, we hit a package conflicts problem.
=> [ci] Remove openssl-fips-provider in UBI9 before updating everything

lib/inspect_shellsyntax.c, test/test_shellsyntax.py
Expand the shellsyntax inspection to ignore scripts that invoke 'exec PROG' where PROG is another interpreter that reloads the script you're in and starts running it.  This is commonly used for Tcl scripts using /usr/bin/wish or /usr/bin/tclsh.
What this patch does is check to see if PROG is a shell we know about and can check syntax for.  If it is, it adjusts the shell from what was originally found on the #! line to the one found with exec.  This assumes that the exec command is loading the script we're looking at, which is not required but at least is somewhat common from what I am seeing.
The end result is that tclsh and wish scripts that use exec should be skipped now if they start with #!/bin/sh or something like that.
Fixes: #1411
=> [lib] Expand shellsyntax to ignore scripts that use 'exec PROG'

data/generic.yaml, include/rpminspect.h, include/types.h, lib/inspect_changelog.c, lib/output_summary.c, lib/results.c, lib/strfuncs.c, test/test_changelog.py
I'm not sure the exact reason why missing changelogs or formerly present and then removed changelogs were reported as either RESULT_VERIFY or RESULT_BAD.  Reporting these changes that way is inconsistent with current best practices and guidelines, but also with have automatic changelog generators and stuff like that.  So continue to report findings but just use RESULT_INFO.
For the missing changelog sections, make use of the new VERB_MISSING verb for findings.
VERB_MISSING is a new verb_t type that can be used by inspections when reporting.  strverb() takes a verb_t and returns a string describing the verb, similar to strseverity().
=> Report all %changelog differences as RESULT_INFO now

lib/inspect_removedfiles.c, test/test_removedfiles.py
Unless a removed file is tied to a security path prefix or has a defined security rule, report the change as INFO.
Fixes: #1409
=> [fix] Report removedfile findings as INFO except for security paths

lib/inspect_disttag.c, test/test_disttag.py
The %autorelease macro may have options.  The disttag inspection sees %autorelease, but was not handling options.  This patch fixes that for packages that may be using %autorelease with options.
=> Recognize %autorelease in Release field with options

test/test_manpage.py
The %{_mandir} macro expands to a different default than other systems.
=> [ci] Fix manpage test cases on Gentoo Linux CI jobs

.github/workflows/amazonlinux.yml, .github/workflows/centos7.yml
The previous actions/checkout@v2 fails to run now.  Complains of glibc symbol mismatches.
=> [ci] Use actions/checkout@v4 in amazonlinux.yml and centos8.yml

.github/workflows/amazonlinux.yml
The problem with the git clone action is that is uses node and node20 wants a glibc newer than what the environment offers.  Trying this trick I found online to see if it will work with an older release.
=> [ci] Try forcing use of node16 on Amazon Linux job

osdeps/fedora-rawhide.i686/post.sh, osdeps/fedora-rawhide/post.sh
The '%%global __debug_package 1\' causes the debuginfo test suite to fail, so if it's present we want to remove the line.
=> [ci] On Fedora rawhide, remove duplicate __debug_package in macros

lib/inspect_virus.c
By default libclamav enforces file size and scan size limits.  I assume this is to cover most file types by default and not appear to hang or stall.  We want to scan all files and some files that appear in RPMs may be beyond that limit.  So disable those limits when we run the virus inspection.
=> [lib] Disable file and scan size limits in clamav

data/generic.yaml, lib/init.c, lib/inspect.c, lib/inspect_unicode.c
This functionality has been requested numerous times.  Developers need the ability to ignore files known to fail this inspection.  Sometimes they appear in test suites, or known broken test cases, or documentation, and so on.
This patch honors an ignore list under the unicode inspection in a local rpminspect.yaml file, such as:
---
unicode:
ignore:
- 'sourcecode-*/test/cases/some/file/with/codepoints.txt'
It is recommended that you document your local rpminspect.yaml file to explain why you are adjusting how an inspection runs so that other people and your future self know why the change had to be made.
Fixes: #1434
=> [lib] Honor locally defined ignore list for the 'unicode' inspection

test/test_debuginfo.py
rpmfluff does not function correctly in some cases on Arch Linux right now, but it's fine things.
=> [tst] Work around a limitation on Arch Linux in test_debuginfo

lib/inspect_unicode.c, test/test_unicode.py
This patch fixes a problem where the directory where sources are unpacked were not stripped properly causing ignore rules to not match, because the branch where this adjustment was done was never reached.
Fixes: #1440
=> [fix] Strip UNPACK_BASE directory in unicode inspection

rpminspect.spec.in
This dependency is picked up as a shared library dependency automatically.
=> [bld] Remove explicit requires on libtoml

osdeps/alpine/post.sh, osdeps/alpine/reqs.txt, osdeps/debian-testing/post.sh
These had some build failures and missing dependencies so the test suite passes again on these platform.
=> [ci] Fix broken Debian Testing and Alpine Linux CI jobs

lib/fileinfo.c, lib/paths.c, lib/secrule.c
rpminspect has a series of rule files with per-file rules.  Files can be specified with shell-style globbing syntax.  Internally rpminspect uses both fnmatch(3) and glob(3) to match paths to these rule definitions.  When using fnmatch(), rpminspect set the FNM_PATHNAME flag.  When this flag is set, slashes are only matched with explicit slashes in the pattern.  They are not matched by as asterisk or question mark.  Unsetting this flag causes the matching to be more greedy and an asterisk now can consume many levels of subdirectories.
Note this is opposite of typical shell behavior, but may work fine for the purposes of rpminspect per-file rule pattern matching.  If this becomes too much of a problem and we cannot get around it with more explicit rule definitions then I may need to …
=> [lib] Drop FNM_PATHNAME for path matching from rule files

lib/inspect_license.c
These can be either AND, OR, WITH -or- and, or, with.  They cannot be AnD, oR, With.  Make sure to handle them correctly.
Fixes: #1454
=> [fix] Correctly handle SPDX special keywords: AND, OR, WITH

lib/arches.c
Sometimes a build may place i686 RPMs in an i386 subdirectory. rpminspect handles that using fnmatch().  In some cases the RPMs would be downloaded, but then skipped in inspections because fnmatch() was not used.  This patch fixes that so the i686 packages are included in inspections even if they appear in an i386 subdirectory.
Fixes: #1464
=> [fix] Match 32-bit x86 RPMs when performing inspections

lib/files.c
We were solely relying on st_nlink, but we should also check the link destination to make sure it is not NULL.
=> [fix] Add extra guards for hardlink handling in extract_rpm()

lib/builds.c, lib/files.c, osdeps/fedora-rawhide/pre.sh, osdeps/fedora-rawhide/reqs.txt, osdeps/fedora/reqs.txt
If you compare one or more Koji tasks that you have not previously downloaded, rpminspect will download the SRPM at least twice.  It is only written to disk once because the path is the same, but you do end up with multiple file entries.  So the upstream inspection fails because there could be 3 SRPMs.  One before and two after, so one of the after build SRPMs fails to peer and that causes the upstream inspection to fail.
This patch cleans up how Koji tasks are downloaded so we only download the SRPM once which then fixes up the upstream inspection.
=> [fix] Prevent duplicate SRPMs in file lists when comparing tasks

lib/rpm.c
archive_write_close does not check whether archive is NULL before dereferencing it. archive may be NULL if extract_rpm_payload fails to open the package or the payload.
=> [fix] Check if archive exists before closing it

CONTRIBUTING.md
(Lifted from rpm's commit:
https://github.com/rpm-software-management/rpm/commit/2e4b7d7d135c4e5706863e10dffdb1422742de52)
The license of anything AI generated is questionable at best, as is the content itself. Poisoning this well with AI slop is just not acceptable.
The last straw driving us to add this is GitHub now advertising Copilot Agent in each and every ticket in "click here to fix this" style. The last thing we want is "helpful" folken submitting AI generated "fixes".
The times. Sigh.
=> Add an AI-policy to contributing guidelines

.github/workflows/fedora.yml, test/data/derp-kmod-aliases/Makefile, test/data/derp-kmod-aliases/derp.c, test/data/derp-kmod-depends/Makefile, test/data/derp-kmod-depends/derp.c, test/data/derp-kmod-params/Makefile, test/data/derp-kmod-params/derp.c, test/test_kmod.py
The 6.15 kernel removed the long deprecated EXTRA_CFLAGS (and other) variables so you now need to use other Kbuild syntax.  I just split up the derp testing module in to all the different ones I needed to test so hopefully this is less complicated and just remains simple source for the purposes of test cases.
=> [tst] Adjust test_kmod to account for EXTRA_CFLAGS removal in 6.15

lib/files.c
For some reason this one did not always show up, but I think that may have had something to do with the underlying filesystem (or any layer of emulation).  At any rate, this was a bug and should have been found earlier.  Better late than never!
Fixes: #1475
=> [fix] Properly handle hard links on RPM payload extraction

utils/determine-os.sh
This is the helper script to help the instreqs target know what OS we are on so we know how to set up the system to build and test rpminspect.
=> [ci] Recognize newer operating systems in determine-os.sh

osdeps/centos10/post.sh
For some reason this directory is not owned by clamupdate:clamupdate so freshclam fails.  Run chown before running freshclam.
=> [ci] Set /var/lib/clamav ownership on CentOS 10 CI job

lib/inspect_filesmatch.c
These types of packages do not have %files definitions, so we cannot check them.
=> [fix] Skip debuginfo and debugsource packages in filesmatch
