rpminspect/rpminspect

- src/librpminspect/files.c
- src/librpminspect/inspect_elf.c
- src/librpminspect/peers.c
- src/librpminspect/readelf.c
- src/librpminspect/results.h
- src/librpminspect/rpminspect.h
- src/librpminspect/types.h
Add simple file peer matching, and finish the ELF tests as a proof-of-concept.
> File peers

- src/librpminspect/files.c
- src/librpminspect/inspect_elf.c
- src/librpminspect/inspect_manpage.c
- src/librpminspect/inspect_xml.c
- src/librpminspect/rpminspect.h
- src/librpminspect/strfuncs.c
- src/librpminspect/types.h
- tests/librpminspect/Makefile.am
- tests/librpminspect/test-badwords.c
- tests/librpminspect/test-init.c
- tests/librpminspect/test-inspect_elf.c
- tests/librpminspect/test-koji.c
- tests/librpminspect/test-main.c
- tests/librpminspect/test-main.h
- tests/librpminspect/test-strfuncs.c
- tests/librpminspect/test-tty.c
Substitute VERSION and VERSION-RELEASE in the paths when attempting to find file peer matches. Also fix some issues with the tests I found along the way.
> Improve file peer matching

- contrib/README.md
- contrib/report-json2html.py
> Add contrib report-json2html.py

- tests/test_default.py
The best Python practice is to follow the PEP 8 -- Style 
https://www.python.org/dev/peps/pep-0008/
> Follow the pep8 style test_default

- README
How to run and debug python integration tests in a virtual environment
> How to run and debug integration tests

- Dockerfile.test
- tests/test_shellsyntax.py
@dcantrell Some tests are failed. 
Please, take a look.
Thanks.
> Add tests for shellsyntax for /bin/rc

- test/baseclass.py
- test/test_ownership.py
Please review as this is my first rpminspect test; there's a lot of repetition, so there's always a chance I copied the wrong rpm style or test somewhere on accident.
> Add tests to validate file ownership and capabilities tests

- .git-blame-ignore-revs
- contrib/report-json2html.py
- test/baseclass.py
- test/test_changelog.py
- test/test_command.py
- test/test_default.py
- test/test_desktop.py
- test/test_disttag.py
- test/test_elf.py
- test/test_emptyrpm.py
- test/test_files.py
- test/test_kmod.py
- test/test_license.py
- test/test_lostpayload.py
- test/test_lto.py
- test/test_manpage.py
- test/test_metadata.py
- test/test_ownership.py
- test/test_pathmigration.py
- test/test_shellsyntax.py
- test/test_specname.py
- test/test_symlinks.py
- test/test_types.py
- test/test_upstream.py
- test/test_xml.py
This is a large commit, which is unfortunate for review, but its advantage is only one commit needs to be added to the revision ignore list for blame.
> Style the Python code with Black

- test/test_metadata.py
A few tests were broken by some bad copy/pasting on my part, and another test never worked, but wasn't run because its name was shadowed by a second test case.
> Fix tests broken by PR #165

- lib/inspect_filesize.c
- test/meson.build
- test/test_filesize.py
Feel free to squash these if you'd prefer all commits to have passing tests, they're broken up mainly so it's easy to git-revert and verify the tests begin passing with the change.
> Add basic filesize inspection tests and fix a bug they revealed

- lib/inspect_filesize.c
- test/baseclass.py
- test/test_filesize.py
Fill out the filesize tests for shrinking files and add some assertions about the messages being presented to users.
> A few more filesize tests and tweaks

- lib/inspect_changedfiles.c
If the changedfiles inspection only ever reports INFO messages, make
sure the inspection reports as 'pass' and the exit code is 0.
> Only fail 'changedfiles' for VERIFY and higher results

- lib/inspect_doc.c
Similar to the recent fixes for the 'config' inspection, make sure
RPMFILE_DOC is checked correctly in the 'doc' inspection.
> Correctly check RPMFILE_DOC flags in the 'doc' inspection

- include/inspect.h
- include/output.h
- include/results.h
- include/rpminspect.h
- include/types.h
- lib/inspect.c
- lib/inspect_manpage.c
- lib/meson.build
- lib/output.c
- lib/output_json.c
- lib/output_xunit.c
- src/rpminspect.c
Add support to rpminspect for outputting results in XUnit format.
> Add 'xunit' output format support to librpminspect

- osdeps/debian/pre.sh
- osdeps/ubuntu/pre.sh
- utils/determine-os.sh
Make sure the latest pip and setuptools are available.
> [ci] Update pip and setuptools on debian and ubuntu CI jobs

- README.md
> [doc] Typo fix in README.md

- .github/workflows/style.yml
> [ci] Restrict style checks to specific directories

- lib/listfuncs.c
> [lib] Change tsearch/twalk use to uthash

- contrib/README.md
> Advertise of rpminspect-report in the contrib README.

- lib/inspect_virus.c
In the virus inspection, report an INFO message that gives the
libclamav version number and the version and date string of each .cvd
file.
> [fix] Report libclamav version and CVD versions (#258)

- lib/init.c
- meson.build
- po/rpminspect.pot
Fix this warn() usage and enable werror=true and raise the warning level to 3.  Also update the translation template.  And put more science stuff around!
> Fix -Werror failure with warn(errbuf)

- lib/inspect_elf.c
Report the sh_flags that are invalid for ET_REL objects rather than
just printing the value.
> [fix] Improve 'has invalid execstack flags' reporting

- lib/inspect_patches.c
The INFO reporting level should be used by the patches inspection for
all reporting, unless the package is not a rebase AND the file or line
count changes are above either threshold.  In that case report the
result as VERIFY.
> [fix] Report INFO level for patches findings by default

- test/test_abidiff.py
> Python black fixes in test/test_abidiff.py

- test/test_patches.py
The patches inspection reporting levels changed, so update the test
cases to comply.
> [tst] Update the test/test_patches.py cases for patches changes

- README.md
- src/rpminspect.1
- src/rpminspect.c
> [doc] Update license table in README.md

- lib/inspect_license.c
Not great, but at least better.  Using this function to parse the
license database allows for reporting when the JSON file fails.  I'm
thinking this isn't the best file format going forward because it's
really easy to make mistakes with hand edits.
> [fix] Use json_tokener_parse_ex() to get better error reporting

- TODO
> [doc] Update TODO list

- lib/inspect_changedfiles.c
This one took a while to show up, but the reproducer is qtbase (or a
subpackage of it) that includes test suite files.  Among the files is
a corrupted gzipped file.  In changedfiles, I try to uncompress
compressed files to compare the uncompressed content.  This is done to
handle changes in the compression level from build to build.  I was
failing to account for deliberately corrupted compressed files.  This
patch adjusts changedfiles so if a compressed file is corrupted, it
falls back to byte by byte comparison.
> [fix] Handle corrupt compressed files in 'changedfiles' (#382)

- meson.build
> Increment version number to 1.6

- lib/inspect_capabilities.c
Since the data files show the text representation of the capabilities,
I thought I needed to use cap_to_text() and then do a string
comparison.  The problem is that later versions of libcap compose
slightly different looking strings even though the underlying cap_t
data is the same.
Doing a bit of digging I found I could use cap_compare() and compare
two cap_t values directly.  This is much more reliable and ignores the
changes in the human readable output generated by cap_to_text().  The
only time this might be confusing is if rpminspect finds a file is
missing an expected capability(7) and then it generates a result and
prints the string as it appears in the data file for the product.  The
format of that string may or may not match what libcap currently
outputs, even if cap_from_text() …
> [fix] Use cap_compare() when comparing file capabilities (#410)

- .gitignore
- Makefile
- doc/Makefile
- doc/conf.py
- doc/configuration.rst
- doc/development.rst
- doc/index.rst
- doc/installation.rst
- doc/intro.rst
- doc/release.rst
- doc/reporting.rst
- doc/testing.rst
- doc/usage.rst
The beginning of documentation for rpminspect.  This will publish to
readthedocs.io.  I am starting with user documentation and will expand
to librpminspect API documentation.
> [doc] Add readthedocs rst source files

- lib/inspect_runpath.c
Based on recent developer feedback, I have modified the runpath
inspection to allow DT_RPATH and DT_RUNPATH paths that are directories
in the package itself or any subpackage in the build.  This fits with
existing packaging policy and is common for many packages.  For
example, if a package provides /usr/lib64/package, then that path can
be in DT_RPATH or DT_RUNPATH in an executable and we should not
require modification of rpminspect.yaml to allow it.
> [lib] Allow directories owned by the build in 'runpath'

- include/rpminspect.h
- lib/builds.c
- lib/strfuncs.c
- src/rpminspect.c
When running 'rpminspect -v', show a download progress bar when fetching packages.
> libcurl progress bars

- .github/workflows/extra-ci.yml
> [ci] Try using i386 command for the i386 jobs

- .github/workflows/extra-ci.yml
> [ci] Install util-linux for /usr/bin/i386

- .github/workflows/extra-ci.yml
> [ci] Just handle i386 build in the qemu job

- lib/builds.c
Two problems:
1) Sort of an off-by-one error on the bar width and SIGWINCH changes.
The progress bar displayed, but not consistently within the '[' and
']' boundaries.  This has been resolved.
2) Lost the setting of CURL_NOPROGRESS to 0.  This setting is a bit
confusing.  You need to set it to zero in order to *get* the progress
callback function called.
> [cmd] Fix the progress bar display problems for '-f -v' mode.

- lib/inspect_xml.c
Adjust the reporting of the xml inspection.  XML that is not
well-formed will result in a VERIFY reporting.  If the XML document is
well-formed but invalid, the result is reporting at the INFO level.
This restricts the inspection to ensuring all XML files are
well-formed.  Hopefully this gets rid of false reports from this
inspection.  Invalid XML is also hard to detect because we have to
make sure we have all of the DTDs or other definitions in order to
gain meaning from the file, and that simply may not be available in
every package.
Fixes: #455
> [fix] Non well-formed XML fails xml, but invalid is info

- po/POTFILES
- po/rpminspect.pot
> [doc] Update translation template

- .github/workflows/extra-ci.yml
> [ci] Correct Amazon Linux name in extra-ci.yml

- .github/workflows/extra-ci.yml
> [ci] Must use dnf on Mageia Linux, not yum

- osdeps/mageia/reqs.txt
> [ci] clamav-dd -> clamav-db on Mageia Linux

- README.md
> [doc] Mention readthedocs.io in README.md

- .github/workflows/ci.yml
- .github/workflows/extra-ci.yml
> [ci] Ignore top level docs in CI jobs

- osdeps/altlinux/pip.txt
- osdeps/altlinux/reqs.txt
> [ci] Install gcovr via pip for Alt Linux

- po/LINGUAS
- po/ru.po
> Add Russian language

- .github/workflows/ci.yml
Currently not building, so temporarily disabling rawhide in CI.
> [ci] Disable fedora:rawhide in ci.yml

- utils/determine-os.sh
All the operating systems keep changing!
> [ci] Support Alt Linux p10 (platform 10)

- README.md
> [doc] Update list of CI Linux distributions in README.md

- .copr/Makefile
> [bld] s/\.gz/.xz/ in .copr/Makefile

- .copr/Makefile
> [bld] Additional Copr build fixes

- .copr/Makefile
> [bld] Adjust %autosetup line for Copr builds

- utils/mkannounce.sh
> [bld] Fix output formatting in utils/mkannounce.sh

- lib/inspect_disttag.c
- lib/macros.c
Just some housekeeping after I ran valgrind.
> Memory leak fixes

- lib/inspect_desktop.c
> [fix] TryExec= line parsing for .desktop files

- lib/inspect_annocheck.c
In the Details section of the annocheck inspection reporting, include
the generated annocheck command lines for before and after builds as
well as their exit codes.  The intent here is to make it easier for
users to interpret annocheck results.
> [lib] In 'annocheck', report the commands and exit codes

- lib/inspect.c
> [fix] addedfiles requires a before and after build

- include/results.h
> [fix] Minor improvement to the text in REMEDY_ADDEDFILES

- lib/inspect_unicode.c
The unicode inspection looks at source code in the SRPM.  It does this
by setting things up to run through %prep in the same way that
rpmbuild would.  The problem is that rpminspect does not enforce
BuildRequires or other build system specifics, so %prep execution may
fail.  In cases where it fails, have the unicode inspection fall back
on manually extracting any source archives it finds in the SRPM and
inspecting all of those.
The inspection already looks at all text files in the SRPM, so this
will ensure we get reasonable coverage even when the source tree
cannot be set up the same way as %prep would do it.
Fixes: #548
> [fix] Handle unexecutable %prep sections in 'unicode'

- lib/output_json.c
- lib/output_text.c
- lib/output_xunit.c
> [fix] Code formatting

- po/POTFILES
- po/rpminspect.pot
> Update translation template

- src/rpminspect.c
> [cmd] Fix two small memory leaks in rpminspect(1)

- lib/inspect_shellsyntax.c
In the shellsyntax Details output, make sure to strip the working
directory when reporting files in packages.  Just use the localpath
throughout, otherwise it will look confusing to users.
Fixes: #581
> [fix] Strip workdir from the Details in shellsyntax reports

- src/rpminspect.c
> [cmd] Fix -Werror=use-after-free findings from gcc 12

- lib/inspect_subpackages.c
- lib/inspect_unicode.c
- lib/inspect_virus.c
- lib/readelf.c
- lib/strfuncs.c
- src/rpminspect.c
These showed up in a number of valgrind runs I did of rpminspect while
investigating other bugs.
> [fix] Close a number of non-fatal memory leaks

- src/rpminspect.c
In instances where you were running against a single build and not
performing a comparison, rpminspect would fail to correctly match the
right product release name.  The problem was the code path was only
entered for comparison jobs.  But there was a further problem with the
regexp matching.  Some unnecessary checks were in place that I have
removed and now everything behaves as expected.
This problem was first reported here:
https://gitlab.com/redhat/centos-stream/ci-cd/rpminspect-data-centos/-/issues/1
> [cmd] Fix get_product_release() for single build jobs

- lib/inspect_rpmdeps.c
Improve the way the rpmdeps inspection detects whether or not a
dependency rule change was expected or not, especially for subpackages
where the version-release specified matches that of the build.
Fixes: #605
> Correct expected explicit dependency changes in subpackages

- data/generic.yaml
- include/results.h
- lib/inspect_addedfiles.c
Some of these had (null) substrings and did not really read quite
right.
> [fix] Correct the addedfiles reporting messages

- lib/deprules.c
- lib/inspect_rpmdeps.c
This commit contains partial support for rich dependency syntax in the
rpmdeps inspection.  I am committing this now as it addresses some
other failures.
> [lib] Begin handling of rich dependency syntax in 'rpmdeps'

- lib/deprules.c
> [fix] Memory management fixes with trim_rich_dep() function

- po/rpminspect.pot
> Update the translation template

- doc/usage.rst
> [doc] Update usage.rst to reflect current inspections

- lib/delta.c
> [fix] Change = -> == in an if expression

- lib/init.c
> [fix] Fix three small memory leaks originating in init.c

- include/rpminspect.h
- include/types.h
- lib/delta.c
- lib/inspect_badfuncs.c
- lib/inspect_changedfiles.c
- lib/readelf.c
- lib/rpm.c
- src/rpminspect.c
These were showing up on a few large build comparisons and were easy
enough to fix up.
> [fix] Patch a number of non-fatal valgrind findings

- lib/rmtree.c
> Code formatting changes

- libxdiff/xdiffi.c
- libxdiff/xemit.c
- libxdiff/xutils.c
> [fix] Variable initialization fixes for libxdiff

- lib/inspect_arch.c
- lib/strfuncs.c
> Code reformatting

- include/readelf.h
- lib/readelf.c
Slowly getting through API documentation for librpminspect.
> [doc] Add Doxygen comments for include/readelf.h

- TODO
> Update TODO list

- include/uthash.h
Just an update from the author of uthash.h.
> [lib] Update to uthash 2.3.0

- lib/init.c
- lib/rpm.c
> [lib] Simplify the librpm initialization call

- lib/inspect_addedfiles.c
The addedfiles inspection was not taking in to account the previous
build and was incorrectly reporting files with a security-related path
as new and needing Security Team review.
Fixes: #708
> [fix] Do not incorrectly report security-related files as new

- include/rpminspect.h
- lib/inspect_addedfiles.c
- lib/secrule.c
- test/test_addedfiles.py
This inspection was a bit incomplete, so I have expanded it some.  I
also added 24 new test cases to cover all of these edge cases.  This
patch does work for issue #708 which is what originally led me down
this path.
> [fix] Correctly handle addedfiles edge cases

- src/rpminspect.c
A problem can happen when you are performing a build comparison and
the after build contains an extra architecture not present in the
before build.  The product release detection block looks at the
package peers and takes the first one to check for the product
release.  The problem is the code expects the first peer to have a
before and after build, but that may not be the case.
This patch shifts to using a for loop which looks at each peer and
stops when it find a before and after peer present.  If the loop ends
without getting a before or after release value, then it reports the
builds do not have enough matching peers.
> [cmd] Improve product release detection for build comparisons

- lib/deprules.c
- lib/inspect_rpmdeps.c
- lib/peers.c
- test/test_rpmdeps_conflicts.py
- test/test_rpmdeps_enhances.py
- test/test_rpmdeps_obsoletes.py
- test/test_rpmdeps_provides.py
- test/test_rpmdeps_recommends.py
- test/test_rpmdeps_requires.py
- test/test_rpmdeps_suggests.py
- test/test_rpmdeps_supplements.py
This is multiple days coming and it was really a chore to track down.  This should also fix #709
> Fix up the deprule peering code for the rpmdeps inspection

- lib/inspect_kmidiff.c
The kmidiff inspection was reporting "comparison ended unexpectedly".
This patch fixes how rpminspect handles the return codes for kmidiff.
Fixes: #726
> [fix] Correct handling of kmidiff(1) exit codes

- lib/inspect_addedfiles.c
The check for forbidden directory entries made some assumptions about
the RPM payload.  The addedfiles inspection has been modified to check
each path for any forbidden directory as a subdirectory in the full
path.  If that is found, rpminspect reports it.  So you could have an
entry like /usr/lib/.git/something and rpminspect will walk that
backwards and see /usr/lib/.git as a directory and report that.  This
works even if the RPM payloads lacks an explicit /usr/lib/.git entry.
> [fix] Correctly check for forbidden directories in RPM payloads

- lib/inspect_patches.c
Still hitting a few issues with reading Patch and %patch lines from
spec files in source RPMs.  This patch makes some changes to ensure
that on those lines, a split gives at least 2 fields (in the case of
%patch it's 2 or more) which makes things more predictable with
regards to storing the data and matching it up.
> [fix] Address some additional Patch and %patch line reading issues

- lib/inspect_types.c
The types inspection is intended to catch things like /usr/bin/program
was an executable, but did you know it's now a JPEG file in this
build?  But the libmagic database changes frequently enough for this
to be a bit pedantic.  For example, a recent build of the kernel had
this inspection failing because Makefiles now show up as
"text/x-makefile" instead of "text/plain".  So the magic database got
a little more finegrained.  That's fine, but it should not fail
rpminspect.
What the types inspection does now is break apart the MIME type at the
'/' and compares the first part and the second part.  It's only a
failure if both parts fail to match.  So since 'text' is present in
both of these, it's not a failure.  But it will report something like
text/plain changing to …
> [fix] Relax the 'types' inspection a bit

- lib/paths.c
This is a common thing as package maintainers have been adding files
to ignore lists. The glob(3) rules do not automatically match a string
like /usr/libexec/ksamples/* as a directory prefix. Technically the *
there will only match one level within /usr/libexec/ksamples. What
I've done to address this is use fnmatch() with FNM_LEADING_DIR in the
flags when the ignore pattern ends with * or ?. I feel this is easier
than asking package maintainers to continually update this list any
time there's another subdirectory added to a full path to ignore. Plus
it's also easier than coming up with some new syntax like ** (used in
Python and rsync and others) or something like
dir:/usr/libexec/ksamples. We can just try the fnmatch() method here
and go with that since it's what the package maintainer …
> [fix] Try FNM_LEADING_DIR matches when patterns end in wildcard

- lib/delta.c
The callback function for generating the unified diff style output can
be passed as a parameter.  Not sure why I didn't do that initially.
Rearrange things so we make valgrind slightly more happy.
> [fix] Memory management fix for the changelog inspection

- lib/inspect_annocheck.c
The reporting severity which can be set in the rpminspect.yaml file
was not properly tied to the actual result of the threshold.  The
result was still based on the pre-config-file threshold setting
method.
> [fix] Tie the annocheck inspection result to reporting severity

- lib/inspect_desktop.c
In the desktop inspection, account for leading executables, variables,
and other parameters on the Exec= line.  Do not just assume you have a
path to a program or a program name that can exec within $PATH.
Fixes: #764
> [fix] Account for leading executables in Exec= (e.g., "env VAR=VAL")

- lib/inspect_permissions.c
Security-related changes need to be RESULT_VERIFY or higher,
non-security-related changes are informational only.
> [fix] Adjust reporting severity in the permissions inspection

- lib/inspect_permissions.c
> [fix] Correct results reporting for the permissions inspection

- lib/inspect_filesize.c
> [fix] Correct results reporting for the filesize inspection

- include/constants.h
- include/rpminspect.h
- include/types.h
- lib/checksums.c
Use macros where it makes more sense.
> Style changes; non-functional

- test/test_rpmdeps_requires.py
When a shared library moves between subpackages between builds, make
sure rpminspect handles that and sees that the library requirement is
still valid even if the actual library moves to a new subpackage.
Fixes: #21
> [tst] Verify automatic ELF Requires handle subpackage changes

- AUTHORS.md
> Update AUTHORS.md list

- lib/curl.c
> [fix] Round the width variable for the curl progress bar

- lib/inspect_patches.c
> [fix] Small fixes to the 'patches' inspection

- lib/inspect_patches.c
The patches inspection performs a number of checks on patch files in
SRPMs.  The last thing it does is report any removed patches when
comparing two builds.  However, this removal check was done checking
the entire list of files in the SRPM rather than just looking at the
RPMTAG_PATCH files from the SRPM header.  This patch corrects that
error.
Fixes: #802
> [fix] Report removed patches by checking RPMTAG_PATCHES list

- lib/inspect_rpmdeps.c
In the rpmdeps inspection, a check is performed to ensure subpackages
with automatic shared library dependencies carry an explicit named
dependency on the subpackage providing that shared library.  Part of
that comparison trims the ISA substring that appears in the
requirement strings, but that was making the assumption that all
substrings in parens were ISA substrings.  That's not the case.  This
patch takes care to leave any paren substrings in place and only
remove the ISA substrings.
The ISA substrings are matched using a regular expression.  This is
done to avoid listing out all possible ones as defined in
/usr/lib/rpm/platform/*/macros since that may change from time to
time.
Fixes: #799
> [fix] Do not remove all () substrings from requirements in rpmdeps

- TODO
Explain the test suite layout more and how to write integration tests.
> Update the TODO file

- lib/koji.c
There were a handful of errors and subsequent memory leaks when downloading module builds from Koji.  This patch addresses those cases and gets all module build types downloading.
> [fix] Fix errors downloading some module builds

- utils/determine-os.sh
> [ci] Add detection of Alma Linux 9 to utils/determine-os.sh

- lib/init.c
Some config file blocks need to override previous settings from other config files rather than append.  Expand process_table() to handle this and implement it for 'javabytecode' allowing per-package overrides.
Fixes: #897
> [fix] When reading config files, allow value overrides

- lib/koji.c
> [fix] Handle Koji XML-RPC failure code 1 when using getTaskInfo

- lib/abi.c
- lib/abspath.c
- lib/arches.c
- lib/builds.c
- lib/init.c
- lib/inspect_arch.c
- lib/inspect_dsodeps.c
- lib/inspect_elf.c
- lib/inspect_kmod.c
- lib/inspect_lto.c
- lib/inspect_rpmdeps.c
- lib/inspect_runpath.c
- lib/kmods.c
- lib/koji.c
- lib/listfuncs.c
- lib/macros.c
- lib/readelf.c
- lib/rpm.c
- lib/strfuncs.c
- src/rpminspect.c
Refactor a lot of code to make better use of list_add() where possible.  This is just a function I wrote to handle adding a new 'char *' to a string_list_t.  No reason not to use it, but I think when I wrote list_add() it was after all of the other stuff had been written.
> [lib] Refactor code to make better use of list_add()

- lib/builds.c
- lib/init.c
- lib/inspect_arch.c
- lib/inspect_badfuncs.c
- lib/inspect_elf.c
- lib/koji.c
- lib/listfuncs.c
- lib/readelf.c
Things found by staring at code, by staring at valgrind output, and just running through different use cases.
> [fix] Various and assorted bug fixes

- lib/inspect_patches.c
This is not worth noting in the CHANGES file.
> Add missing \n to DEBUG_PRINT line in inspect_patches.c

- .mailmap
> Add my gmail address to .mailmap

- lib/inspect_abidiff.c
I can't remember why, but I was driving over the actual result for abidiff(1) with a bogus message that abidiff exited unexpectedly. Fixed.
> [fix] Correctly report abidiff(1) results in the abidiff inspection

- lib/inspect_symlinks.c
Add readlink() call to get the symlink destination and report that in the results rather than the same path again.
Fixes: #978
> [fix] Report symlink destination via readlink() in results

- lib/inspect_annocheck.c
The libannocheck code path supports setting an annocheck profile based on the product release.  This patch adds that functionality for the annocheck code path that forks and exec annocheck(1).  Since the fork/exec code path will eventually go away, I am not too concerned with the if block that has the XXX comment.  It's hardcoded to the profiles available now, but I think that's fine.
Fixes: #977
> [fix] When building with '-D with_annocheck=true', pass --profile

- lib/builds.c
Followup to last week's patch.  This rearranges how the program attempts to figure out what you asked it to download so it can report failures more intelligently.  Or at least appear that way.
> [lib] Improve the failure reporting from gather_builds()

- lib/inspect_lostpayload.c
This inspection was not giving enough details in the reporting, so include the architecture in the messages.
Fixes: #1001
> [fix] Improve lostpayload inspection reporting by including arch

- .github/workflows/almalinux.yml
- .github/workflows/alpinelinux.yml
- .github/workflows/altlinux.yml
- .github/workflows/amazonlinux.yml
- .github/workflows/archlinux.yml
- .github/workflows/centos.yml
- .github/workflows/debian.yml
- .github/workflows/freebsd.yml
- .github/workflows/gentoo.yml
- .github/workflows/mageia.yml
- .github/workflows/opensuse.yml
- .github/workflows/oraclelinux.yml
- .github/workflows/rockylinux.yml
- .github/workflows/slackware.yml
- .github/workflows/ubuntu.yml
> [ci] Do not make the gcovr step fail for the rest of the CI jobs

- README.md
> [doc] Add FreeBSD to the list of CI platforms

- osdeps/debian/post.sh
- osdeps/debian/pre.sh
- osdeps/debian/reqs.txt
Fix ups to the container set up steps.  Also need to install elfutils for the debuginfo tests.
> [ci] Fix Debian stable and testing CI jobs

- osdeps/ubuntu/post.sh
- osdeps/ubuntu/pre.sh
- osdeps/ubuntu/reqs.txt
> [ci] Fix Ubuntu latest CI job

- .github/workflows/centos.yml
- osdeps/centos7/post.sh
- osdeps/centos7/reqs.txt
- osdeps/centos9/pip.txt
- osdeps/centos9/post.sh
- osdeps/centos9/reqs.txt
> [ci] Fix CentOS 7 and CentOS Stream 8 jobs; add CentOS Stream 9

- .github/workflows/freebsd.yml
> [ci] Update the FreeBSD repo catalog before running the CI job

- lib/inspect_permissions.c
When a file becomes a directory, for instance, the permissions inspection reports this as "permissions relaxed from 0644 to 0755". That's not very user friendly, so add in some text that also says it became a directory.  Try to handle all the file type changes while preserving the existing information reported.
Fixes: #1030
> [fix] Report file type changes in the permissions inspection

- TODO
Paste in a copy of the desired rpmlint (rpmdiff) output as requested by the community.  This is not impossible, but will just take me some time to sort out.
> Update the TODO list

- lib/inspect_elf.c
The elf inspection was not properly handling kernel packages.  Most notably kernel modules.  Also, debuginfo packages were historically skipped by this test in rpminspect's ancestor, so we do that here too.
> [fix] Handle kernel and debuginfo packages in 'elf' correctly

- lib/koji.c
- rpminspect.spec.in
- src/rpminspect.c
There are two commits here, but they are unrelated.
> Stuff and things

- lib/init.c
- lib/parse_yaml.c
> [lib] Whitespace changes

- osdeps/debian/post.sh
- osdeps/ubuntu/post.sh
Not currently a package, so install it from git.
> [ci] Install cdson from git on Debian and Ubuntu CI jobs

- lib/inspect_virus.c
- test/test_virus.py
Fixes: #1025
Signed-off-by: Michal Srb <michal@redhat.com>
> Make virus inspection failures WAIVABLE_BY_SECURITY.

- osdeps/alpine/post.sh
- osdeps/arch/post.sh
- osdeps/debian/post.sh
- osdeps/mageia/post.sh
- osdeps/opensuse-leap/post.sh
- osdeps/oraclelinux8/post.sh
- osdeps/oraclelinux8/reqs.txt
- osdeps/ubuntu/post.sh
- rpminspect.spec.in
> Various CI and build fixes

- osdeps/alpine/post.sh
- osdeps/arch/post.sh
- osdeps/debian/post.sh
- osdeps/mageia/post.sh
- osdeps/opensuse-leap/post.sh
- osdeps/oraclelinux8/post.sh
- osdeps/ubuntu/post.sh
I'm terrible at this.  Do I run meson or ninja?  Yes!  No!  Sometimes! All the time!  Maybe!
> [ci] Use ninja instead of meson when building cdson

- lib/init.c
In the config file reader, make sure to handle the rpmdeps section correctly.  The code was not updating the data structure.  The per-inspection ignores were mishandled because the code was looking for the substring "ignores" rather than "ignore".  rpminspect now allows either "ignores" or "ignore" for per-inspection ignore lists.
Fixes: #1069
> [fix] Correctly read rpmdeps section and per-inspection ignores

- lib/parse_dson.c
- lib/parse_json.c
- lib/parse_yaml.c
Just another thing about the way I like to write for loops.
> [lib] Small coding style changes in parse_*.c files

- lib/inspect_unicode.c
In the unicode inspection, the full paths to files in the SRPM were included in failure messages.  This was not the case for files in the prepped and extracted source tree.  I was lacking handling for source files directly in the SRPM.
Fixes: #1073
> [fix] Strip temporary working dir from SRPM files in 'unicode'

- lib/inspect_abidiff.c
abidiff should only run on public shared libraries, so add a little additional code in there to skip not just ET_EXEC ELF objects but also ET_DYN objects with DT_SONAME.  The reason for the latter is that any ELF executable built with -fPIE is ET_DYN, which is also the type for shared libraries.  ELF shared executables do not carry DT_SONAME, so ensure that is missing in order to rule it an ELF shared executable that can be skipped.
Fixes: #1077
> [fix] Do not run abidiff inspection on ELF ET_DYN executables

- include/rpminspect.h
- lib/builds.c
- lib/debug.c
- lib/deprules.c
- lib/init.c
- lib/inspect_rpmdeps.c
- lib/peers.c
Forgot to actually hook this up.  Ooops.  Also make sure the -D output (dump config) shows the ignore rules found in the config files.
> Hook up the ignore part of the rpmdeps config file block

- .github/workflows/centos.yml
- .github/workflows/freebsd.yml
- Makefile
- osdeps/fedora/defs.mk
More things as I clean up the failing jobs.  A lot of this is just Makefile restructuring and job refactoring in the GitHub syntax.
> Assortment of CI job fixes

- lib/inspect_modularity.c
Previously, if both old and new module build had the same static_context value, the test ignored the value and reported a pass or a failure regadrless of the value.
This patch splits a check for the static_context change from a check for the desired value of the "after" module build. That makes the logic and the code simpler at the expense of gluing two sentences together.
Since the two senteces are independent, I don't think it's a problem for translators. It's similar to separating messages by a new line. But rpminspect uses single-line reports.
Fixes #1118
> [fix] Handle unchanged static_context in modularity test correctly

- lib/inspect_modularity.c
Just cleanups for my own style preferences.
> [lib] Initialize after_compliance to NULL

- include/rpminspect.h
- include/types.h
- lib/inspect.c
- lib/inspect_addedfiles.c
- lib/inspect_annocheck.c
- lib/inspect_changedfiles.c
- lib/inspect_ownership.c
- lib/inspect_permissions.c
- lib/paths.c
- lib/strfuncs.c
See #995 for more information.
> Make sure security checks ignore the global and per-inspection ignore lists

- .github/workflows/centos.yml
- include/types.h
> CentOS 7 CI fix

- .github/workflows/gentoo.yml
- osdeps/gentoo/defs.mk
- osdeps/gentoo/post.sh
Needed some additional settings in /etc/portage/make.conf and a modification to how Python modules get installed with pip.
> [ci] Fix the Gentoo Linux CI job

- lib/inspect_disttag.c
- lib/inspect_unicode.c
- lib/llvm.c
> Assorted cleanups and fixes

- data/generic.dson
- data/generic.json
- data/generic.yaml
- data/security/GENERIC
Strike some non-applicable blocks from example config files and add a little more text to security/GENERIC explaining things.
> [cfg] Update config file examples with latest security rules

- utils/determine-os.sh
> [bld] shellcheck fixes for utils/determine-os.sh

- lib/inspect_capabilities.c
Eliminate some duplicate messages and also note what subpackage an impacted file is part of (not just the architecture).
> [lib] Improve the capabilities inspection reporting

- lib/inspect_unicode.c
- lib/runcmd.c
Work through a handful of issues that valgrind reported in the unicode inspection.
> [fix] Some valgrind fixes in the unicode inspection

- src/rpminspect.c
> [cmd] Error out on invalid -w values if wordexp() and/or stat() fail

- lib/inspect_unicode.c
- lib/magic.c
The unicode inspection can skip files by MIME type.  This is used to skip things like HTML files or .po translation files.  The two functions used to get the MIME type were behaving differently.  One was stripping the text in the MIME type string from the first ';' to the end while the other was not.  What was happening is that the function called by nftw() on the extracted source tree was not skipping excluded MIME types because the string contained the ; part. I have rearranged things so that the same behavior is used in both places in the unicode inspection.
Fixes: #1213
> [fix] Correct the MIME type exclusion check for the unicode inspection

- osdeps/gentoo/post.sh
A small comment correction is included as well
> [ci] Define a %dist tag on Gentoo Linux systems

- lib/builds.c
Add an additional check in gather_local_build function to infer which type of build we are testing. This prevents some inspections to be skipped, as they need to know the buildtype.
This PR aims to fix #1247
> [fix] local builds don't have buildtype set

- .github/workflows/almalinux.yml
- .github/workflows/alpinelinux.yml
- .github/workflows/amazonlinux.yml
- .github/workflows/archlinux.yml
- .github/workflows/centos.yml
- .github/workflows/debian.yml
- .github/workflows/fedora-aarch64.yml
- .github/workflows/fedora-ppc64le.yml
- .github/workflows/fedora-s390x.yml
- .github/workflows/fedora.yml
- .github/workflows/freebsd.yml
- .github/workflows/gentoo.yml
- .github/workflows/mageia.yml
- .github/workflows/opensuse.yml
- .github/workflows/oraclelinux.yml
- .github/workflows/python.yml
- .github/workflows/slackware.yml
- .github/workflows/ubuntu.yml
- utils/determine-os.sh
> Various CI job improvements and tidyments

- lib/inspect_rpmdeps.c
Ensure that, when requesting an explicit package requires for a shared library, both provider and requester packages come from the same SRPM.
This PR aims to prevent these false possitives described in #1246.
> [fix] Prevent false positives in rpmdeps inspection for modules

- lib/inspect_rpmdeps.c
Sometimes subpackages in one SRPM will carry different Epoch values that other subpackages or the main package.  This is allowed but the rpmdeps inspection was going with the old practice of "all subpackages will be on the same Epoch".  Now rpminspect will verify if an explicit Epoch value is needed in a deprule based on whether that named subpackage has a Epoch value greater than zero.  When no Epoch is specified, rpm assumes 0 and in those cases rpminspect does not care what the deprule carries in the version field.
Fixes: #984
> [fix] Handle subpackages with different Epoch values in rpmdeps

- lib/inspect_xml.c
Things were ending up on stderr, so clean up the reporting a bit and make better use of ctxt->lastError.
> [lib] Clean up libxml2 output in the xml inspection

- .mailmap
- AUTHORS.md
- MISSING
Just some minor doc updates.  And mailmap since some of us can't figure out how to consistently name ourselves in git commit messages.
> Update AUTHORS.md, MISSING, and .mailmap

- lib/inspect_doc.c
When rebased builds are compared, docs will probably change. Sometimes a lot.  The doc inspection reports changes at the INFO level, but always includes the diff output.  This can lead to gigabytes of data if you are comparing a very large package (say, rust).  This patch changes the inspection so the diff output is not reported when the builds compared are a rebase.  If the builds compared are not a rebase, it will report the results as it previously did.
Fixes: #1233
> [lib] Do not include diff output in doc inspection for rebased builds

- osdeps/almalinux9/post.sh
- osdeps/alpine/post.sh
- osdeps/arch/post.sh
- osdeps/centos7/post.sh
- osdeps/debian-stable/post.sh
- osdeps/debian-testing/post.sh
- osdeps/fedora-rawhide.i686/post.sh
- osdeps/fedora-rawhide/post.sh
- osdeps/fedora.i686/post.sh
- osdeps/fedora/post.sh
- osdeps/freebsd/post.sh
- osdeps/gentoo/post.sh
- osdeps/mageia/post.sh
- osdeps/opensuse-leap/post.sh
- osdeps/opensuse-tumbleweed/post.sh
- osdeps/slackware/post.sh
- osdeps/ubuntu/post.sh
- regress/all-inspections-kernel.sh
- regress/indiv-inspections-kernel.sh
- utils/determine-os.sh
- utils/find-ninja.sh
- utils/gate.sh
- utils/mkannounce.sh
- utils/submit-koji-builds.sh
Do a bit of housekeeping on the shell scripts used in CI jobs and the release process.
> [ci] Run shellcheck on all scripts and fix up common errors

- include/results.h
- po/POTFILES
- po/rpminspect.pot
> [fix] Fix the REMEDY_RUNPATH string

- .github/workflows/almalinux.yml
- .github/workflows/alpinelinux.yml
- .github/workflows/amazonlinux.yml
- .github/workflows/archlinux.yml
- .github/workflows/centos.yml
- .github/workflows/debian.yml
- .github/workflows/fedora-aarch64.yml
- .github/workflows/fedora-ppc64le.yml
- .github/workflows/fedora-s390x.yml
- .github/workflows/fedora.yml
- .github/workflows/freebsd.yml
- .github/workflows/gentoo.yml
- .github/workflows/mageia.yml
- .github/workflows/opensuse.yml
- .github/workflows/oraclelinux.yml
- .github/workflows/pre-commit.yml
- .github/workflows/shellcheck.yml
- .github/workflows/slackware.yml
- .github/workflows/ubuntu.yml
There's a new one and I hope it has fixed the safe.directory workaround.
> [ci] Use actions/checkout@v4 for the git check part in CI jobs

- osdeps/gentoo/pre.sh
- osdeps/gentoo/reqs.txt
- test/test_symlinks.py
> More CI and test case fixes

- .github/workflows/freebsd.yml
- osdeps/freebsd/post.sh
- osdeps/freebsd/pre.sh
Looks like this can now run on Linux rather than MacOS in the VM, so change that.  Also update to FreeBSD 14 and make other changes for the instreqs files so they work on FreeBSD 14.
> [ci] Update the FreeBSD CI job

- lib/inspect_symlinks.c
It is possible to have before RPMs but no matching after RPM peer. Other inspections handle this loss, but the symlinks inspection was not properly handling it.  This patch corrects that.
Fixes: #1336
> [fix] Handle peers with only before RPMs in the symlinks inspection

- lib/inspect_annocheck.c
The latest annobin release already supports el10.
> [lib] annocheck: Map el10 product release to the corresponding profile

- lib/paths.c
> [fix] annocheck: fix the debuginfo package lookup

- lib/badwords.c
- lib/humansize.c
- lib/inspect_changedfiles.c
- lib/inspect_filesize.c
- meson.build
Some things were incorrect but the compiler didn't complain loudly enough.  I also changed a few things to work better with different compilers and systems.
> [fix] Small fixes and refactorings

- osdeps/debian-stable/post.sh
- osdeps/debian-stable/pre.sh
- osdeps/debian-stable/reqs.txt
- osdeps/debian-testing/post.sh
- osdeps/debian-testing/pre.sh
- osdeps/debian-testing/reqs.txt
Needed to update the package lists and scripts a bit to run without error.
> [tst] Fix the Debian testing and stable GitHub Actions CI jobs

- lib/inspect_javabytecode.c
The javabytecode inspection is one of the early ones, which came before foreach_peer_file().  Guess I never went back and updated the inspection to use foreach_peer_file().  Doing so now lets the ignore lists work for javabytecode from rpminspect.yaml files.
I also made sure the test is enforcing a minimum required JVM major version, not a maximum allowed JVM major version.
Fixes: #1395
> [fix] Use foreach_peer_file() in inspect_javabytecode()

- utils/determine-os.sh
For about another month, so leave it in place.
> [ci] We can still do test jobs on CentOS 7

- include/rpminspect.h
- lib/inspect_license.c
- lib/listfuncs.c
> Fix license ID detection when they appear on both the legacy and SPDX lists

- data/licenses/generic.json
> [cfg] Drop 'id' from the example license JSON database

- rpminspect.spec.in
Install docs and licenses correctly, switch thr %autorelease.
> [bld] Fix FTBFS errors in the spec file for home.

- osdeps/alpine/post.sh
- osdeps/alpine/reqs.txt
- osdeps/arch/post.sh
- osdeps/arch/pre.sh
- osdeps/debian-stable/defs.mk
- osdeps/debian-stable/pip.txt
- osdeps/debian-stable/pre.sh
- osdeps/debian-stable/reqs.txt
- osdeps/debian-testing/defs.mk
- osdeps/debian-testing/pip.txt
- osdeps/debian-testing/post.sh
- osdeps/debian-testing/pre.sh
- osdeps/debian-testing/reqs.txt
- osdeps/gentoo/post.sh
- osdeps/gentoo/pre.sh
Environments have changed a bit, so pull in updates for CI jobs.
> [ci] Fixes for some failing CI jobs

- lib/spec.c
Some packages use the %{load} macro to load additional macro definitions that are included in the package.  These are expected to live in %{_sourcedir}, but that was not defined so librpm was using the default location.  For rpminspect, define _sourcedir to be the same directory where the spec file lives since that how it unpacks RPM packages.
> [fix] Allow %{load} macros to work when calling rpmSpecParse()

- lib/inspect_filesmatch.c
- lib/spec.c
Debug reporting and function calls.
> [lib] Minor cleanups for the filesmatch inspection

- lib/inspect_filesmatch.c
- lib/spec.c
What I originally wrote was a bit too long and difficult to follow so I shortened it and made a helper function.
> [lib] Refactor how %doc and %license lines are processed in filesmatch

- lib/inspect_filesmatch.c
During the expansion of %doc and %license lines, add in handling for %dir as well as any of the modifiers that may appear (like %attr, %lang, and others).
> [fix] Handle %dir and %files modifiers in %doc & %license lines
